// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_am_1.4.0.bmm.json + openehr_base_1.3.0.bmm.json

package aom14

import "encoding/json"

// BMM package: org.openehr.am.aom14.archetype.assertion — canonical-JSON MarshalJSON companions

type AssertionJSONMarshaller struct {
	Class string `json:"_type"`
	// Tag Expression tag, used for differentiating multiple assertions.
	Tag *string `json:"tag,omitempty"`
	// StringExpression String form of expression, in case an expression evaluator taking String expressions is used for evaluation.
	StringExpression *string `json:"string_expression,omitempty"`
	// Expression Root of expression tree.
	Expression ExprItem `json:"expression"`
	// Variables Definitions of variables used in the assertion expression.
	Variables []AssertionVariable `json:"variables,omitempty"`
}

// MarshalJSON emits canonical openEHR JSON for Assertion with `_type`
// (value "ASSERTION") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (a *Assertion) MarshalJSON() ([]byte, error) {
	return json.Marshal(&AssertionJSONMarshaller{
		Class:            "ASSERTION",
		Tag:              a.Tag,
		StringExpression: a.StringExpression,
		Expression:       a.Expression,
		Variables:        a.Variables,
	})
}

type AssertionVariableJSONMarshaller struct {
	Class string `json:"_type"`
	// Name Name of variable.
	Name string `json:"name"`
	// Definition Formal definition of the variable.
	Definition string `json:"definition"`
}

// MarshalJSON emits canonical openEHR JSON for AssertionVariable with `_type`
// (value "ASSERTION_VARIABLE") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (a *AssertionVariable) MarshalJSON() ([]byte, error) {
	return json.Marshal(&AssertionVariableJSONMarshaller{
		Class:      "ASSERTION_VARIABLE",
		Name:       a.Name,
		Definition: a.Definition,
	})
}

type ExprBinaryOperatorJSONMarshaller struct {
	Class string `json:"_type"`
	// PrecedenceOverridden True if the natural precedence of operators is overridden in the expression represented by this node of the expression tree. If True, parentheses should be introduced around the totality of the syntax expression corresponding to this operator node and its operands.
	PrecedenceOverridden *bool `json:"precedence_overridden,omitempty"`
	// Operator Code of operator.
	Operator OperatorKind `json:"operator"`
	// Type Type name of this item in the mathematical sense. For leaf nodes, must be the name of a primitive type, or else a reference model type. The type for any relational or boolean operator will be “Boolean”, while the type for any arithmetic operator, will be “Real” or “Integer”.
	Type string `json:"type"`
	// LeftOperand Left operand node.
	LeftOperand ExprItem `json:"left_operand"`
	// RightOperand Right operand node.
	RightOperand ExprItem `json:"right_operand"`
}

// MarshalJSON emits canonical openEHR JSON for ExprBinaryOperator with `_type`
// (value "EXPR_BINARY_OPERATOR") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (e *ExprBinaryOperator) MarshalJSON() ([]byte, error) {
	return json.Marshal(&ExprBinaryOperatorJSONMarshaller{
		Class:                "EXPR_BINARY_OPERATOR",
		PrecedenceOverridden: e.PrecedenceOverridden,
		Operator:             e.Operator,
		Type:                 e.Type,
		LeftOperand:          e.LeftOperand,
		RightOperand:         e.RightOperand,
	})
}

type ExprLeafJSONMarshaller struct {
	Class string `json:"_type"`
	// Type Type name of this item in the mathematical sense. For leaf nodes, must be the name of a primitive type, or else a reference model type. The type for any relational or boolean operator will be “Boolean”, while the type for any arithmetic operator, will be “Real” or “Integer”.
	Type string `json:"type"`
	// ReferenceType Type of reference: “constant”, “attribute”, “function”, “constraint”. The first three are used to indicate the referencing mechanism for an operand. The last is used to indicate a constraint operand, as happens in the case of the right-hand operand of the ‘matches’ operator.
	ReferenceType string `json:"reference_type"`
	// Item The value referred to; a manifest constant, an attribute path (in the form of a String), or for the right-hand side of a ‘matches’ node, a constraint, often a C_PRIMITIVE_OBJECT.
	Item any `json:"item"`
}

// MarshalJSON emits canonical openEHR JSON for ExprLeaf with `_type`
// (value "EXPR_LEAF") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (e *ExprLeaf) MarshalJSON() ([]byte, error) {
	return json.Marshal(&ExprLeafJSONMarshaller{
		Class:         "EXPR_LEAF",
		Type:          e.Type,
		ReferenceType: e.ReferenceType,
		Item:          e.Item,
	})
}

type ExprUnaryOperatorJSONMarshaller struct {
	Class string `json:"_type"`
	// PrecedenceOverridden True if the natural precedence of operators is overridden in the expression represented by this node of the expression tree. If True, parentheses should be introduced around the totality of the syntax expression corresponding to this operator node and its operands.
	PrecedenceOverridden *bool `json:"precedence_overridden,omitempty"`
	// Operator Code of operator.
	Operator OperatorKind `json:"operator"`
	// Type Type name of this item in the mathematical sense. For leaf nodes, must be the name of a primitive type, or else a reference model type. The type for any relational or boolean operator will be “Boolean”, while the type for any arithmetic operator, will be “Real” or “Integer”.
	Type string `json:"type"`
	// Operand Operand node.
	Operand ExprItem `json:"operand"`
}

// MarshalJSON emits canonical openEHR JSON for ExprUnaryOperator with `_type`
// (value "EXPR_UNARY_OPERATOR") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (e *ExprUnaryOperator) MarshalJSON() ([]byte, error) {
	return json.Marshal(&ExprUnaryOperatorJSONMarshaller{
		Class:                "EXPR_UNARY_OPERATOR",
		PrecedenceOverridden: e.PrecedenceOverridden,
		Operator:             e.Operator,
		Type:                 e.Type,
		Operand:              e.Operand,
	})
}
