// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_am_1.4.0.bmm.json + openehr_base_1.3.0.bmm.json

package aom14

import (
	"encoding/xml"
	"fmt"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
	"github.com/cadasto/openehr-sdk-go/openehr/serialize/canxml"
)

// BMM package: org.openehr.am.aom14.archetype.assertion — canonical-XML UnmarshalXML companions

// UnmarshalXML decodes canonical openEHR XML into Assertion.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
func (a *Assertion) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "tag":
				var _v string
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				a.Tag = &_v
			case "string_expression":
				var _v string
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				a.StringExpression = &_v
			case "expression":
				_v, _err := canxml.DecodeAs[ExprItem](_dec, _t)
				if _err != nil {
					return _err
				}
				a.Expression = _v
			case "variables":
				var _v AssertionVariable
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				a.Variables = append(a.Variables, _v)
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// UnmarshalXML decodes canonical openEHR XML into AssertionVariable.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
func (a *AssertionVariable) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "name":
				if _err := _dec.DecodeElement(&a.Name, &_t); _err != nil {
					return _err
				}
			case "definition":
				if _err := _dec.DecodeElement(&a.Definition, &_t); _err != nil {
					return _err
				}
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// UnmarshalXML decodes canonical openEHR XML into ExprBinaryOperator.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
func (e *ExprBinaryOperator) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "precedence_overridden":
				var _v bool
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				e.PrecedenceOverridden = &_v
			case "operator":
				if _err := _dec.DecodeElement(&e.Operator, &_t); _err != nil {
					return _err
				}
			case "type":
				if _err := _dec.DecodeElement(&e.Type, &_t); _err != nil {
					return _err
				}
			case "left_operand":
				_v, _err := canxml.DecodeAs[ExprItem](_dec, _t)
				if _err != nil {
					return _err
				}
				e.LeftOperand = _v
			case "right_operand":
				_v, _err := canxml.DecodeAs[ExprItem](_dec, _t)
				if _err != nil {
					return _err
				}
				e.RightOperand = _v
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// UnmarshalXML decodes canonical openEHR XML into ExprLeaf.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
func (e *ExprLeaf) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "type":
				if _err := _dec.DecodeElement(&e.Type, &_t); _err != nil {
					return _err
				}
			case "reference_type":
				if _err := _dec.DecodeElement(&e.ReferenceType, &_t); _err != nil {
					return _err
				}
			case "item":
				if _err := _dec.DecodeElement(&e.Item, &_t); _err != nil {
					return _err
				}
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// UnmarshalXML decodes canonical openEHR XML into ExprUnaryOperator.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
func (e *ExprUnaryOperator) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "precedence_overridden":
				var _v bool
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				e.PrecedenceOverridden = &_v
			case "operator":
				if _err := _dec.DecodeElement(&e.Operator, &_t); _err != nil {
					return _err
				}
			case "type":
				if _err := _dec.DecodeElement(&e.Type, &_t); _err != nil {
					return _err
				}
			case "operand":
				_v, _err := canxml.DecodeAs[ExprItem](_dec, _t)
				if _err != nil {
					return _err
				}
				e.Operand = _v
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

var (
	_ = typereg.ErrMissingType
	_ = fmt.Sprintf
	_ = canxml.NSDefault
)
