// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_am_1.4.0.bmm.json + openehr_base_1.3.0.bmm.json

package aom14

import (
	"encoding/json/jsontext"
	"fmt"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
)

// BMM package: org.openehr.am.aom14.archetype.ontology — canonical-JSON UnmarshalJSONFrom companions

// UnmarshalJSONFrom decodes canonical openEHR JSON into ArchetypeOntology.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError — keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (a *ArchetypeOntology) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if a == nil {
		return fmt.Errorf("canjson: ARCHETYPE_ONTOLOGY: %w", typereg.ErrNilReceiver)
	}
	return typereg.DecodeInto(dec, "ARCHETYPE_ONTOLOGY", &struct {
		Type string `json:"_type"`
		*rawArchetypeOntology
	}{rawArchetypeOntology: (*rawArchetypeOntology)(a)})
}

// UnmarshalJSONFrom decodes canonical openEHR JSON into ArchetypeTerm.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError — keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (a *ArchetypeTerm) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if a == nil {
		return fmt.Errorf("canjson: ARCHETYPE_TERM: %w", typereg.ErrNilReceiver)
	}
	return typereg.DecodeInto(dec, "ARCHETYPE_TERM", &struct {
		Type string `json:"_type"`
		*rawArchetypeTerm
	}{rawArchetypeTerm: (*rawArchetypeTerm)(a)})
}
