// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_am_1.4.0.bmm.json + openehr_base_1.3.0.bmm.json

package aom14

import (
	"encoding/xml"

	"github.com/cadasto/openehr-sdk-go/openehr/serialize/canxml"
)

// BMM package: org.openehr.am.aom14.openehr_archetype_profile — canonical-XML MarshalXML companions

// BMMName returns "C_CODED_TEXT" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (c *CCodedText) BMMName() string { return "C_CODED_TEXT" }

// MarshalXML emits canonical openEHR XML for CCodedText. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
func (c *CCodedText) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("C_CODED_TEXT")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if c.AssumedValue != nil {
		if err := _e.EncodeElement(*c.AssumedValue, xml.StartElement{Name: xml.Name{Local: "assumed_value"}}); err != nil {
			return err
		}
	}
	if err := _e.EncodeElement(c.RMTypeName, xml.StartElement{Name: xml.Name{Local: "rm_type_name"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(&c.Occurrences, xml.StartElement{Name: xml.Name{Local: "occurrences"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(c.NodeID, xml.StartElement{Name: xml.Name{Local: "node_id"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(c.Terminology, xml.StartElement{Name: xml.Name{Local: "terminology"}}); err != nil {
		return err
	}
	if c.CodeList != nil {
		if err := _e.EncodeElement(c.CodeList, xml.StartElement{Name: xml.Name{Local: "code_list"}}); err != nil {
			return err
		}
	}
	if c.Reference != nil {
		if err := _e.EncodeElement(*c.Reference, xml.StartElement{Name: xml.Name{Local: "reference"}}); err != nil {
			return err
		}
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "C_ORDINAL" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (c *COrdinal) BMMName() string { return "C_ORDINAL" }

// MarshalXML emits canonical openEHR XML for COrdinal. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
func (c *COrdinal) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("C_ORDINAL")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if c.AssumedValue != nil {
		if err := _e.EncodeElement(*c.AssumedValue, xml.StartElement{Name: xml.Name{Local: "assumed_value"}}); err != nil {
			return err
		}
	}
	if err := _e.EncodeElement(c.RMTypeName, xml.StartElement{Name: xml.Name{Local: "rm_type_name"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(&c.Occurrences, xml.StartElement{Name: xml.Name{Local: "occurrences"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(c.NodeID, xml.StartElement{Name: xml.Name{Local: "node_id"}}); err != nil {
		return err
	}
	for _idx := range c.List {
		if err := _e.EncodeElement(&c.List[_idx], xml.StartElement{Name: xml.Name{Local: "list"}}); err != nil {
			return err
		}
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "C_QUANTITY" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (c *CQuantity) BMMName() string { return "C_QUANTITY" }

// MarshalXML emits canonical openEHR XML for CQuantity. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
func (c *CQuantity) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("C_QUANTITY")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if c.AssumedValue != nil {
		if err := _e.EncodeElement(*c.AssumedValue, xml.StartElement{Name: xml.Name{Local: "assumed_value"}}); err != nil {
			return err
		}
	}
	if err := _e.EncodeElement(c.RMTypeName, xml.StartElement{Name: xml.Name{Local: "rm_type_name"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(&c.Occurrences, xml.StartElement{Name: xml.Name{Local: "occurrences"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(c.NodeID, xml.StartElement{Name: xml.Name{Local: "node_id"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(c.Property, xml.StartElement{Name: xml.Name{Local: "property"}}); err != nil {
		return err
	}
	for _idx := range c.List {
		if err := _e.EncodeElement(&c.List[_idx], xml.StartElement{Name: xml.Name{Local: "list"}}); err != nil {
			return err
		}
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "C_QUANTITY_ITEM" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (c *CQuantityItem) BMMName() string { return "C_QUANTITY_ITEM" }

// MarshalXML emits canonical openEHR XML for CQuantityItem. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
func (c *CQuantityItem) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("C_QUANTITY_ITEM")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeElement(&c.Magnitude, xml.StartElement{Name: xml.Name{Local: "magnitude"}}); err != nil {
		return err
	}
	if c.Units != nil {
		if err := _e.EncodeElement(*c.Units, xml.StartElement{Name: xml.Name{Local: "units"}}); err != nil {
			return err
		}
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "ORDINAL" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (o *Ordinal) BMMName() string { return "ORDINAL" }

// MarshalXML emits canonical openEHR XML for Ordinal. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
func (o *Ordinal) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("ORDINAL")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeElement(&o.Symbol, xml.StartElement{Name: xml.Name{Local: "symbol"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(o.Value, xml.StartElement{Name: xml.Name{Local: "value"}}); err != nil {
		return err
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}
