// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_am_1.4.0.bmm.json + openehr_base_1.3.0.bmm.json

package aom14

import (
	"encoding/json"
	"fmt"

	"github.com/cadasto/openehr-sdk-go/openehr/rm"
	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
)

// BMM package: org.openehr.am.aom14.openehr_archetype_profile — canonical-JSON UnmarshalJSON companions

type CCodedTextJSONUnmarshaller struct {
	Class string `json:"_type"`
	// AssumedValue Value to be assumed if none sent in data.
	AssumedValue *any `json:"assumed_value,omitempty"`
	// RMTypeName Reference model type that this node corresponds to.
	RMTypeName string `json:"rm_type_name"`
	// Occurrences Occurrences of this object node in the data, under the owning attribute. Upper limit can only be greater than 1 if owning attribute has a cardinality of more than 1).
	Occurrences rm.Interval[Integer] `json:"occurrences"`
	// NodeID Semantic identifier of this node, used to distinguish sibling nodes. All nodes must have a node_id; for nodes under a container C_ATTRIBUTE, the id must be an id-code must be defined in the archetype terminology. For valid structures, all node ids are at-codes.
	// For C_PRIMITIVE_OBJECTs, it will have the special value Primitive_node_id.
	NodeID string `json:"node_id"`
	// Terminology Terminology identifier.
	Terminology string `json:"terminology"`
	// CodeList Optional list of codes from the terminology. No list means any code from the terminology is allowed.
	CodeList  *[]string `json:"code_list,omitempty"`
	Reference *string   `json:"reference,omitempty"`
}

// UnmarshalJSON decodes canonical openEHR JSON into CCodedText.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (c *CCodedText) UnmarshalJSON(data []byte) error {
	var aux CCodedTextJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: C_CODED_TEXT: %w", err)
	}
	if aux.Class != "" && aux.Class != "C_CODED_TEXT" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "C_CODED_TEXT", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	c.AssumedValue = aux.AssumedValue
	c.RMTypeName = aux.RMTypeName
	c.Occurrences = aux.Occurrences
	c.NodeID = aux.NodeID
	c.Terminology = aux.Terminology
	c.CodeList = aux.CodeList
	c.Reference = aux.Reference
	return nil
}

type COrdinalJSONUnmarshaller struct {
	Class string `json:"_type"`
	// AssumedValue Value to be assumed if none sent in data.
	AssumedValue *any `json:"assumed_value,omitempty"`
	// RMTypeName Reference model type that this node corresponds to.
	RMTypeName string `json:"rm_type_name"`
	// Occurrences Occurrences of this object node in the data, under the owning attribute. Upper limit can only be greater than 1 if owning attribute has a cardinality of more than 1).
	Occurrences rm.Interval[Integer] `json:"occurrences"`
	// NodeID Semantic identifier of this node, used to distinguish sibling nodes. All nodes must have a node_id; for nodes under a container C_ATTRIBUTE, the id must be an id-code must be defined in the archetype terminology. For valid structures, all node ids are at-codes.
	// For C_PRIMITIVE_OBJECTs, it will have the special value Primitive_node_id.
	NodeID string `json:"node_id"`
	// List Value set of allowed Ordinals in the constraint.
	List []Ordinal `json:"list,omitempty"`
}

// UnmarshalJSON decodes canonical openEHR JSON into COrdinal.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (c *COrdinal) UnmarshalJSON(data []byte) error {
	var aux COrdinalJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: C_ORDINAL: %w", err)
	}
	if aux.Class != "" && aux.Class != "C_ORDINAL" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "C_ORDINAL", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	c.AssumedValue = aux.AssumedValue
	c.RMTypeName = aux.RMTypeName
	c.Occurrences = aux.Occurrences
	c.NodeID = aux.NodeID
	c.List = aux.List
	return nil
}

type CQuantityJSONUnmarshaller struct {
	Class string `json:"_type"`
	// AssumedValue Value to be assumed if none sent in data.
	AssumedValue *any `json:"assumed_value,omitempty"`
	// RMTypeName Reference model type that this node corresponds to.
	RMTypeName string `json:"rm_type_name"`
	// Occurrences Occurrences of this object node in the data, under the owning attribute. Upper limit can only be greater than 1 if owning attribute has a cardinality of more than 1).
	Occurrences rm.Interval[Integer] `json:"occurrences"`
	// NodeID Semantic identifier of this node, used to distinguish sibling nodes. All nodes must have a node_id; for nodes under a container C_ATTRIBUTE, the id must be an id-code must be defined in the archetype terminology. For valid structures, all node ids are at-codes.
	// For C_PRIMITIVE_OBJECTs, it will have the special value Primitive_node_id.
	NodeID string `json:"node_id"`
	// Property Name of physical property for Quantities being constrained.
	Property string `json:"property"`
	// List Value set of allowed individual Quantity item constraints in this Quantity constraint.
	List []CQuantityItem `json:"list,omitempty"`
}

// UnmarshalJSON decodes canonical openEHR JSON into CQuantity.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (c *CQuantity) UnmarshalJSON(data []byte) error {
	var aux CQuantityJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: C_QUANTITY: %w", err)
	}
	if aux.Class != "" && aux.Class != "C_QUANTITY" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "C_QUANTITY", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	c.AssumedValue = aux.AssumedValue
	c.RMTypeName = aux.RMTypeName
	c.Occurrences = aux.Occurrences
	c.NodeID = aux.NodeID
	c.Property = aux.Property
	c.List = aux.List
	return nil
}

type CQuantityItemJSONUnmarshaller struct {
	Class string `json:"_type"`
	// Magnitude Quantity magnitude constraint.
	Magnitude rm.Interval[Real] `json:"magnitude"`
	// Units Optional units constraint.
	Units *string `json:"units,omitempty"`
}

// UnmarshalJSON decodes canonical openEHR JSON into CQuantityItem.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (c *CQuantityItem) UnmarshalJSON(data []byte) error {
	var aux CQuantityItemJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: C_QUANTITY_ITEM: %w", err)
	}
	if aux.Class != "" && aux.Class != "C_QUANTITY_ITEM" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "C_QUANTITY_ITEM", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	c.Magnitude = aux.Magnitude
	c.Units = aux.Units
	return nil
}

type OrdinalJSONUnmarshaller struct {
	Class string `json:"_type"`
	// Symbol Terminology code providing the Ordinal's symbol.
	Symbol rm.CodePhrase `json:"symbol"`
	// Value Ordinal value.
	Value Integer `json:"value"`
}

// UnmarshalJSON decodes canonical openEHR JSON into Ordinal.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (o *Ordinal) UnmarshalJSON(data []byte) error {
	var aux OrdinalJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: ORDINAL: %w", err)
	}
	if aux.Class != "" && aux.Class != "ORDINAL" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "ORDINAL", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	o.Symbol = aux.Symbol
	o.Value = aux.Value
	return nil
}
