// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_am_1.4.0.bmm.json + openehr_base_1.3.0.bmm.json

package aom14

import (
	"encoding/json/jsontext"
	"fmt"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
)

// BMM package: org.openehr.am.aom14.openehr_archetype_profile — canonical-JSON UnmarshalJSONFrom companions

// UnmarshalJSONFrom decodes canonical openEHR JSON into CCodedText.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError — keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (c *CCodedText) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if c == nil {
		return fmt.Errorf("canjson: C_CODED_TEXT: %w", typereg.ErrNilReceiver)
	}
	return typereg.DecodeInto(dec, "C_CODED_TEXT", &struct {
		Type string `json:"_type"`
		*rawCCodedText
	}{rawCCodedText: (*rawCCodedText)(c)})
}

// UnmarshalJSONFrom decodes canonical openEHR JSON into COrdinal.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError — keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (c *COrdinal) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if c == nil {
		return fmt.Errorf("canjson: C_ORDINAL: %w", typereg.ErrNilReceiver)
	}
	return typereg.DecodeInto(dec, "C_ORDINAL", &struct {
		Type string `json:"_type"`
		*rawCOrdinal
	}{rawCOrdinal: (*rawCOrdinal)(c)})
}

// UnmarshalJSONFrom decodes canonical openEHR JSON into CQuantity.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError — keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (c *CQuantity) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if c == nil {
		return fmt.Errorf("canjson: C_QUANTITY: %w", typereg.ErrNilReceiver)
	}
	return typereg.DecodeInto(dec, "C_QUANTITY", &struct {
		Type string `json:"_type"`
		*rawCQuantity
	}{rawCQuantity: (*rawCQuantity)(c)})
}

// UnmarshalJSONFrom decodes canonical openEHR JSON into CQuantityItem.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError — keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (c *CQuantityItem) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if c == nil {
		return fmt.Errorf("canjson: C_QUANTITY_ITEM: %w", typereg.ErrNilReceiver)
	}
	return typereg.DecodeInto(dec, "C_QUANTITY_ITEM", &struct {
		Type string `json:"_type"`
		*rawCQuantityItem
	}{rawCQuantityItem: (*rawCQuantityItem)(c)})
}

// UnmarshalJSONFrom decodes canonical openEHR JSON into Ordinal.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError — keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (o *Ordinal) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if o == nil {
		return fmt.Errorf("canjson: ORDINAL: %w", typereg.ErrNilReceiver)
	}
	return typereg.DecodeInto(dec, "ORDINAL", &struct {
		Type string `json:"_type"`
		*rawOrdinal
	}{rawOrdinal: (*rawOrdinal)(o)})
}
