package rminfo

import (
	"slices"
	"sync"
)

// Lookup answers structural questions about RM classes from the
// pinned BMM. All inputs and outputs use BMM class names (UPPER_CASE,
// e.g. "COMPOSITION", "DV_QUANTITY") and BMM attribute names
// (lower_case, e.g. "category", "events"). Codegen output:
// see lookup_gen.go (generated by internal/bmmgen).
type Lookup interface {
	// RequiredAttributes returns the names of attributes the RM
	// declares as mandatory on the given RM type, including
	// inherited attributes from ancestors. Order is BMM declaration
	// order (own attributes follow ancestors). Returns nil when
	// rmType is unknown.
	RequiredAttributes(rmType string) []string

	// AttributeRMType returns the RM type of an attribute on a
	// parent type (e.g. AttributeRMType("OBSERVATION", "data") =
	// "HISTORY"). For container properties the element type is
	// returned (i.e. the type inside the list). The second return
	// is false when parentRMType is unknown or attrName is not
	// declared on parentRMType (own or inherited).
	AttributeRMType(parentRMType, attrName string) (string, bool)

	// IsContainer reports whether the named attribute is multi-valued
	// (a container property in the BMM, e.g. COMPOSITION.content,
	// SECTION.items). The second return is false when the attribute
	// is unknown.
	IsContainer(parentRMType, attrName string) (bool, bool)

	// KnownRMTypes returns all RM class names this Lookup recognises,
	// sorted alphabetically. Used by validators that need to walk the
	// universe of types (e.g. discovery probes).
	KnownRMTypes() []string
}

// AttributeLister is an optional extension of [Lookup]: it enumerates a
// type's attributes in BMM declaration order. It is kept off the Lookup
// interface so adding it does not break external Lookup implementers
// (idiom.md § Public-API stability — prefer a new interface plus a runtime
// type-assertion to introduce optional behaviour). [Default] implements it;
// consumers walking the RM graph without an OPT — e.g. the template-less
// validation floor (REQ-112) — assert for it.
type AttributeLister interface {
	// AttributeNames returns every attribute on the given RM type in BMM
	// declaration order (ancestors first, then own), including inherited
	// attributes. Returns nil when rmType is unknown.
	AttributeNames(rmType string) []string
}

// Default is the package-level Lookup populated by the generated
// data tables (see lookup_gen.go). Tests and consumers should use
// this value; New is provided for unit testing with synthetic data.
var Default Lookup = &lookup{data: defaultData}

// New constructs a Lookup over a caller-supplied data set. Intended
// for unit tests that need to substitute synthetic RM shapes.
// Production callers should use [Default].
func New(data map[string]ClassMeta) Lookup {
	return &lookup{data: data}
}

// ClassMeta is the per-class data the Lookup consults. It is
// exported only to allow tests to construct synthetic data; the
// production tables live in lookup_gen.go.
type ClassMeta struct {
	// Attributes is the effective attribute set (own + inherited)
	// keyed by attribute name.
	Attributes map[string]AttrMeta
	// AttrOrder is Attributes' iteration order (BMM declaration
	// order; ancestors first, then own).
	AttrOrder []string
}

// AttrMeta is the per-attribute data the Lookup consults.
type AttrMeta struct {
	// TypeName is the BMM RM type name of the attribute value. For
	// container properties this is the element type (the type
	// inside the list). Never empty.
	TypeName string
	// Required reports whether the BMM declares the attribute as
	// mandatory (the `is_mandatory` flag, or — for containers —
	// `cardinality.lower >= 1`).
	Required bool
	// Container reports whether the attribute is multi-valued
	// (declared as a container property in the BMM).
	Container bool
}

// lookup is the concrete Lookup backed by a data map.
type lookup struct {
	data      map[string]ClassMeta
	knownOnce sync.Once
	known     []string
}

func (l *lookup) RequiredAttributes(rmType string) []string {
	meta, ok := l.data[rmType]
	if !ok {
		return nil
	}
	out := make([]string, 0, len(meta.AttrOrder))
	for _, name := range meta.AttrOrder {
		if meta.Attributes[name].Required {
			out = append(out, name)
		}
	}
	return out
}

func (l *lookup) AttributeRMType(parentRMType, attrName string) (string, bool) {
	meta, ok := l.data[parentRMType]
	if !ok {
		return "", false
	}
	attr, ok := meta.Attributes[attrName]
	if !ok {
		return "", false
	}
	return attr.TypeName, true
}

func (l *lookup) AttributeNames(rmType string) []string {
	meta, ok := l.data[rmType]
	if !ok {
		return nil
	}
	return slices.Clone(meta.AttrOrder)
}

func (l *lookup) IsContainer(parentRMType, attrName string) (bool, bool) {
	meta, ok := l.data[parentRMType]
	if !ok {
		return false, false
	}
	attr, ok := meta.Attributes[attrName]
	if !ok {
		return false, false
	}
	return attr.Container, true
}

func (l *lookup) KnownRMTypes() []string {
	l.knownOnce.Do(func() {
		l.known = make([]string, 0, len(l.data))
		for k := range l.data {
			l.known = append(l.known, k)
		}
		slices.Sort(l.known)
	})
	// Return a copy so callers may sort/mutate without corrupting the cache.
	return slices.Clone(l.known)
}
