package rminfo

import (
	"slices"
	"sync"
)

// Lookup answers structural questions about RM classes from the
// pinned BMM. All inputs and outputs use BMM class names (UPPER_CASE,
// e.g. "COMPOSITION", "DV_QUANTITY") and BMM attribute names
// (lower_case, e.g. "category", "events"). Codegen output:
// see lookup_gen.go (generated by internal/bmmgen).
type Lookup interface {
	// RequiredAttributes returns the names of attributes the RM
	// declares as mandatory on the given RM type, including
	// inherited attributes from ancestors. Order is BMM declaration
	// order (own attributes follow ancestors). Returns nil when
	// rmType is unknown.
	RequiredAttributes(rmType string) []string

	// AttributeRMType returns the RM type of an attribute on a
	// parent type (e.g. AttributeRMType("OBSERVATION", "data") =
	// "HISTORY"). For container properties the element type is
	// returned (i.e. the type inside the list). The second return
	// is false when parentRMType is unknown or attrName is not
	// declared on parentRMType (own or inherited).
	AttributeRMType(parentRMType, attrName string) (string, bool)

	// IsContainer reports whether the named attribute is multi-valued
	// (a container property in the BMM, e.g. COMPOSITION.content,
	// SECTION.items). The second return is false when the attribute
	// is unknown.
	IsContainer(parentRMType, attrName string) (bool, bool)

	// KnownRMTypes returns all RM class names this Lookup recognises,
	// sorted alphabetically. Used by validators that need to walk the
	// universe of types (e.g. discovery probes).
	//
	// The set is every class the RM generation target emits a Go type
	// for, which since REQ-048 includes the abstract and attribute-less
	// ones (DATA_VALUE, PATHABLE, the support service classes): a class
	// absent here cannot be asked about at all, and a descendant
	// expansion rooted at an abstract class needs that class present.
	// It is therefore NOT a list of instantiable types — see
	// [Hierarchy.IsAbstract] and, for what is decodable, the type
	// registry in openehr/rm/typereg (REQ-040).
	KnownRMTypes() []string
}

// AttributeLister is an optional extension of [Lookup]: it enumerates a
// type's attributes in BMM declaration order. It is kept off the Lookup
// interface so adding it does not break external Lookup implementers
// (idiom.md § Public-API stability — prefer a new interface plus a runtime
// type-assertion to introduce optional behaviour). [Default] implements it;
// consumers walking the RM graph without an OPT — e.g. the template-less
// validation floor (REQ-112) — assert for it.
type AttributeLister interface {
	// AttributeNames returns every attribute on the given RM type in BMM
	// declaration order (ancestors first, then own), including inherited
	// attributes. Returns nil when rmType is unknown.
	AttributeNames(rmType string) []string
}

// Compile-time guarantee that the backing concrete type satisfies both the
// stable Lookup interface and the optional AttributeLister. Consumers assert
// Default.(AttributeLister) at runtime; this turns a future signature drift on
// AttributeNames into a build break rather than a silently-failing assertion.
var (
	_ Lookup          = (*lookup)(nil)
	_ AttributeLister = (*lookup)(nil)
)

// Default is the package-level Lookup populated by the generated
// data tables (see lookup_gen.go for the class universe, absence_gen.go
// for the names outside it). Tests and consumers should use
// this value; New is provided for unit testing with synthetic data.
//
// As an [AbsenceReporter] it answers from the generated absence table, so an
// out-of-universe name gets the reason it is out rather than a blanket
// [AbsenceUndeclared] (REQ-049).
//
// Default is safe for concurrent use by multiple goroutines, including on
// first use: the derived indexes it builds lazily are published under
// [sync.Once].
var Default Lookup = &lookup{data: defaultData, absence: absenceData}

// New constructs a Lookup over a caller-supplied data set. Intended
// for unit tests that need to substitute synthetic RM shapes.
// Production callers should use [Default].
//
// The returned Lookup RETAINS data rather than copying it, and derives indexes
// from it on first use. Callers MUST NOT mutate data afterwards: doing so races
// with those indexes and leaves the derived answers permanently stale, with no
// diagnostic. Like [Default], the result is otherwise safe for concurrent use.
//
// The result carries no absence table, so as an [AbsenceReporter] it reports
// [AbsenceUndeclared] for every name outside data (REQ-049). To exercise the
// other absence reasons on synthetic data, use [NewWithAbsence].
func New(data map[string]ClassMeta) Lookup {
	return &lookup{data: data}
}

// ClassMeta is the per-class data the Lookup consults. It is
// exported only to allow tests to construct synthetic data; the
// production tables live in lookup_gen.go.
//
// Construct with field NAMES. Fields may be added in a minor release
// (REQ-048 added Abstract and Parents), which breaks positional literals —
// idiom.md § Public-API stability.
type ClassMeta struct {
	// Attributes is the effective attribute set (own + inherited)
	// keyed by attribute name.
	Attributes map[string]AttrMeta
	// AttrOrder is Attributes' iteration order (BMM declaration
	// order; ancestors first, then own).
	AttrOrder []string
	// Abstract mirrors the BMM is_abstract flag verbatim: the model
	// forbids instantiating the class, so naming it denotes its concrete
	// descendants rather than one instantiable class. It is NOT a
	// verdict on whether a stored instance can carry the name as _type
	// — see [Hierarchy.IsAbstract] (REQ-048).
	Abstract bool
	// Parents lists the class's immediate parents in BMM declaration
	// order, filtered to the classes this data set defines. A BMM
	// ancestor outside the class universe — the foundation typing layer
	// (Any, Ordered, Interval, the Iso8601_* types) — is dropped, which
	// makes its child a root rather than an edge pointing at a name no
	// method can answer for (REQ-048).
	Parents []string
}

// AttrMeta is the per-attribute data the Lookup consults.
//
// Construct with field NAMES, for the same reason as [ClassMeta]: REQ-048
// added DeclaredIn, and a positional literal would no longer compile.
type AttrMeta struct {
	// TypeName is the BMM RM type name of the attribute value. For
	// container properties this is the element type (the type
	// inside the list). Never empty.
	TypeName string
	// Required reports whether the BMM declares the attribute as
	// mandatory (the `is_mandatory` flag, or — for containers —
	// `cardinality.lower >= 1`).
	Required bool
	// Container reports whether the attribute is multi-valued
	// (declared as a container property in the BMM).
	Container bool
	// DeclaredIn names the class whose BMM declaration supplied this
	// attribute — the owning class itself, or the ancestor the
	// inheritance fold took it from. It is recorded BY that fold, so
	// it cannot disagree with the TypeName / Required / Container
	// triple beside it (REQ-048).
	DeclaredIn string
}

// lookup is the concrete Lookup backed by a data map. It also implements the
// optional [AttributeLister], [Hierarchy] and [AbsenceReporter] capability
// interfaces.
type lookup struct {
	data map[string]ClassMeta
	// absence records why each declared-but-omitted class is outside data —
	// the universe's negative space (REQ-049, see absence.go). The GENERATED
	// table never overlaps data; a synthetic one from [NewWithAbsence] may,
	// and data wins. It may be nil: undeclared is computed, not stored.
	absence   map[string]AbsenceReason
	knownOnce sync.Once
	known     []string
	// childOnce/children memoise the inverted Parents edges the generated
	// tables do not carry — see childIndex in hierarchy.go.
	childOnce sync.Once
	children  map[string][]string
}

func (l *lookup) RequiredAttributes(rmType string) []string {
	meta, ok := l.data[rmType]
	if !ok {
		return nil
	}
	out := make([]string, 0, len(meta.AttrOrder))
	for _, name := range meta.AttrOrder {
		if meta.Attributes[name].Required {
			out = append(out, name)
		}
	}
	return out
}

func (l *lookup) AttributeRMType(parentRMType, attrName string) (string, bool) {
	meta, ok := l.data[parentRMType]
	if !ok {
		return "", false
	}
	attr, ok := meta.Attributes[attrName]
	if !ok {
		return "", false
	}
	return attr.TypeName, true
}

func (l *lookup) AttributeNames(rmType string) []string {
	meta, ok := l.data[rmType]
	if !ok {
		return nil
	}
	return slices.Clone(meta.AttrOrder)
}

func (l *lookup) IsContainer(parentRMType, attrName string) (bool, bool) {
	meta, ok := l.data[parentRMType]
	if !ok {
		return false, false
	}
	attr, ok := meta.Attributes[attrName]
	if !ok {
		return false, false
	}
	return attr.Container, true
}

func (l *lookup) KnownRMTypes() []string {
	l.knownOnce.Do(func() {
		l.known = make([]string, 0, len(l.data))
		for k := range l.data {
			l.known = append(l.known, k)
		}
		slices.Sort(l.known)
	})
	// Return a copy so callers may sort/mutate without corrupting the cache.
	return slices.Clone(l.known)
}
