package termgen

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
)

// SourceInfo is the provenance the generated file records: the pin's
// repo-relative path, the TERM release ref from its MANIFEST.txt, and the
// sha256 [Run] computed over the pin's bytes.
type SourceInfo struct {
	Path   string
	Ref    string
	SHA256 string
}

// Render emits openehr_gen.go: the generated-file header and its provenance,
// the Version and SourceSHA256 constants, one exported variable per group and
// per code set in the pin's document order, and the unexported groups /
// codeSets registry slices the package's accessors range over.
//
// The output is run through go/format, so it is gofmt-clean, and it depends
// on nothing but t and src, so it is byte-deterministic — both are what let
// `make termgen-verify` treat any difference from the committed file as
// drift.
func Render(t *Terminology, src SourceInfo) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by termgen; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: %s — openEHR TERM %s\n", src.Path, src.Ref)
	fmt.Fprintf(&b, "// (terminology version %s, sha256 %s).\n", t.Version, src.SHA256)
	b.WriteString("// Regenerate: make termgen. Verify: make termgen-verify.\n\n")
	b.WriteString("package terminology\n\n")

	b.WriteString("// Version is the openEHR Terminology release the tables below are generated from.\n")
	fmt.Fprintf(&b, "const Version = %s\n\n", strconv.Quote(t.Version))
	b.WriteString("// SourceSHA256 is the sha256 of the pinned openehr_terminology.xml the tables were generated from.\n")
	fmt.Fprintf(&b, "const SourceSHA256 = %s\n\n", strconv.Quote(src.SHA256))

	for _, g := range t.Groups {
		name := GoName(g.ID)
		fmt.Fprintf(&b, "// %s is the openEHR terminology group %s (openehr_id %s), %s.\n",
			name, strconv.Quote(g.Name), g.ID, plural(len(g.Concepts), "concept"))
		fmt.Fprintf(&b, "var %s = newGroup(%s, %s, []Concept{\n", name, strconv.Quote(g.ID), strconv.Quote(g.Name))
		for _, c := range g.Concepts {
			fmt.Fprintf(&b, "\t{Code: %s, Rubric: %s},\n", strconv.Quote(c.Code), strconv.Quote(c.Rubric))
		}
		b.WriteString("})\n\n")
	}

	for _, cs := range t.CodeSets {
		name := GoName(cs.ID)
		fmt.Fprintf(&b, "// %s is the openEHR terminology code set %s (openehr_id %s), %s.\n",
			name, strconv.Quote(cs.Name), cs.ID, plural(len(cs.Codes), "code"))
		fmt.Fprintf(&b, "var %s = newCodeSet(%s, %s, []string{", name, strconv.Quote(cs.ID), strconv.Quote(cs.Name))
		for i, c := range cs.Codes {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(strconv.Quote(c))
		}
		b.WriteString("})\n\n")
	}

	fmt.Fprintf(&b, "// groups is the pin's %s in document order — what Groups and GroupByID range over.\n",
		plural(len(t.Groups), "group"))
	b.WriteString("var groups = []*Group{")
	for i, g := range t.Groups {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(GoName(g.ID))
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(&b, "// codeSets is the pin's %s in document order — what CodeSets and CodeSetByID range over.\n",
		plural(len(t.CodeSets), "code set"))
	b.WriteString("var codeSets = []*CodeSet{")
	for i, cs := range t.CodeSets {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(GoName(cs.ID))
	}
	b.WriteString("}\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return b.Bytes(), fmt.Errorf("gofmt openehr/terminology/openehr_gen.go: %w", err)
	}
	return formatted, nil
}

// plural renders "1 concept" / "9 concepts" for a doc comment.
func plural(n int, noun string) string {
	if n == 1 {
		return "1 " + noun
	}
	return fmt.Sprintf("%d %ss", n, noun)
}
