package termgen

import (
	"bytes"
	"go/format"
	"strings"
	"testing"
)

// fixtureSource is the provenance the render tests pass in. Run derives the
// real one from the pin's bytes and its MANIFEST.txt.
var fixtureSource = SourceInfo{
	Path:   "resources/terminology/openehr_terminology.xml",
	Ref:    "Release-9.9.9",
	SHA256: "abc",
}

func TestRenderEmitsTheGeneratedTable(t *testing.T) {
	t.Parallel()
	term, err := Parse(strings.NewReader(fixture))
	if err != nil {
		t.Fatalf("Parse(fixture) = _, %v", err)
	}
	body, err := Render(term, fixtureSource)
	if err != nil {
		t.Fatalf("Render = _, %v", err)
	}
	out := string(body)

	// The first line is what .golangci.yml's `generated: lax` exclusion and
	// the editor save hook's *_gen.go skip both key off, so it is exact.
	const wantFirst = "// Code generated by termgen; DO NOT EDIT."
	if first, _, _ := strings.Cut(out, "\n"); first != wantFirst {
		t.Errorf("first line = %q, want %q", first, wantFirst)
	}

	// Substrings in the order the file must carry them.
	want := []string{
		"// Source: resources/terminology/openehr_terminology.xml — openEHR TERM Release-9.9.9",
		"sha256 abc",
		"// Regenerate: make termgen. Verify: make termgen-verify.",
		"package terminology",
		`const Version = "9.9.9"`,
		`const SourceSHA256 = "abc"`,
		`var AuditChangeType = newGroup("audit_change_type", "audit change type", []Concept{`,
		`{Code: "249", Rubric: "creation"},`,
		`{Code: "523", Rubric: "deleted"},`,
		`var NormalStatuses = newCodeSet("normal_statuses", "normal statuses", []string{"N", "H"})`,
		"var groups = []*Group{AuditChangeType}",
		"var codeSets = []*CodeSet{NormalStatuses}",
	}
	at := 0
	for _, w := range want {
		i := strings.Index(out[at:], w)
		if i < 0 {
			t.Errorf("rendered table is missing %q (or has it out of order)\n--- got ---\n%s", w, out)
			continue
		}
		at += i + len(w)
	}
}

func TestRenderOutputIsGofmtCleanAndDeterministic(t *testing.T) {
	t.Parallel()
	term, err := Parse(strings.NewReader(fixture))
	if err != nil {
		t.Fatalf("Parse(fixture) = _, %v", err)
	}
	first, err := Render(term, fixtureSource)
	if err != nil {
		t.Fatalf("Render = _, %v", err)
	}
	formatted, err := format.Source(first)
	if err != nil {
		t.Fatalf("format.Source(rendered) = _, %v — the rendered table is not valid Go", err)
	}
	if !bytes.Equal(first, formatted) {
		t.Errorf("rendered table is not gofmt-clean:\n--- got ---\n%s\n--- gofmt ---\n%s", first, formatted)
	}
	second, err := Render(term, fixtureSource)
	if err != nil {
		t.Fatalf("second Render = _, %v", err)
	}
	if !bytes.Equal(first, second) {
		t.Error("two Render calls over the same pin differ — the output must be byte-deterministic")
	}
}

func TestGoName(t *testing.T) {
	t.Parallel()
	tests := []struct{ id, want string }{
		{"audit_change_type", "AuditChangeType"},
		{"null_flavours", "NullFlavours"},
		{"property", "Property"},
		{"extract_update_trigger_event_type", "ExtractUpdateTriggerEventType"},
		{"normal_statuses", "NormalStatuses"},
	}
	for _, tc := range tests {
		if got := GoName(tc.id); got != tc.want {
			t.Errorf("GoName(%q) = %q, want %q", tc.id, got, tc.want)
		}
	}
}
