// Package bmmgen is the BMM-driven code generator for the SDK.
//
// It reads the pinned BMM files in resources/bmm/ via openehr/bmm and
// emits Go source under one or more target output directories — one
// file per BMM top-level package, plus a single typereg_gen.go per
// target whose init() calls typereg.Default.Register for every
// concrete class.
//
// # Targets
//
// A [Target] identifies one generation destination. Phase 2 emitted
// only the RM target ([TargetRM] → openehr/rm/). Phase 4 adds the
// AOM 1.4 target ([TargetAOM14] → openehr/aom/aom14/). The two
// targets share openehr_base_1.3.0 by include, but AOM does NOT
// duplicate base classes; instead it references them as `rm.<Name>`
// via a one-way `aom14 → rm` import. See
// docs/plans/2026-05-15-bmm-codegen.md Phase 4.
//
// # Layout deviation note
//
// The plan describes typereg registrations as living in
// `openehr/rm/typereg/registry_gen.go`. That location induces an
// import cycle (typereg → rm for the constructors, rm → typereg for
// the [typereg.Registry] type). The actual emission is
// `<package>/typereg_gen.go` — inside the target package — so the
// constructors `func() any { return &DVQuantity{} }` can refer to
// the target types directly. The typereg subpackage stays free of
// reverse dependencies. The semantics (`typereg.Default.Register`
// called once per concrete class at init time) are preserved.
//
// Both RM and AOM register with the SAME typereg.Default — the
// _type discriminator strings are disjoint between the two models
// (no `DV_QUANTITY` in AOM, no `ARCHETYPE` in RM).
//
// Generated files carry the standard header
// "// Code generated by bmmgen; DO NOT EDIT." and MUST NOT be
// hand-edited (REQ-042, REQ-044). Hand-written companions named
// `*_ext.go` are preserved untouched.
//
// Output is byte-identical across runs on the same inputs; CI runs
// the generator and fails the build if the working tree diverges
// from the regenerated output. Internal package — not part of the
// public SDK API.
//
// CLI: cmd/bmmgen. Conformance contract: specs/bmm-conformance.md.
package bmmgen

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
)

// Options controls a single generator invocation.
type Options struct {
	// ResourcesDir is the path to the directory containing the pinned
	// `*.bmm.json` files. Required.
	ResourcesDir string
	// OutDir is the module root the generator writes into. The
	// generator writes "<OutDir>/<Target.OutSubDir>/<file>_gen.go".
	OutDir string
	// Targets is the list of generation destinations. Defaults to
	// [DefaultTargets()] (RM + AOM 1.4) when empty.
	Targets []Target
	// RootID, when non-empty, overrides the RootID of the FIRST target
	// only. Retained for backwards compatibility with the Phase 2 CLI
	// which exposed only a single target. New callers should populate
	// [Targets] directly.
	RootID string
	// Verify, when true, causes the generator to compare what would
	// be written against what is already on disk and report drift
	// rather than mutating the tree.
	Verify bool
	// Verbose enables extra diagnostic output to Stderr.
	Verbose bool
	// Stderr is the writer for diagnostic output. Defaults to
	// os.Stderr if nil.
	Stderr interface {
		Write(p []byte) (int, error)
	}
}

// Result summarises a generator run.
type Result struct {
	// Files written (or, in verify mode, that would be written).
	Files []string
	// Drifts holds the file paths that differ from the regenerated
	// output. Populated only in verify mode.
	Drifts []DriftRecord
	// Notes propagates each Plan's notes verbatim.
	Notes []string
	// MethodStubsEmitted is the total number of Phase 3 function
	// method stubs emitted across all generated files (all targets).
	MethodStubsEmitted int
	// MethodTodoEscapes is the count of method stubs whose result
	// type fell back to `any` because the BMM return type referenced
	// a skipped class.
	MethodTodoEscapes int
	// PerTarget collects per-target diagnostic counters (file count
	// and method-stub tallies). Index aligns with Options.Targets
	// after default expansion.
	PerTarget []TargetResult
}

// TargetResult captures per-target diagnostic counters.
type TargetResult struct {
	Target             Target
	Files              []string
	MethodStubsEmitted int
	MethodTodoEscapes  int
}

// DriftRecord is a single drift detection result.
type DriftRecord struct {
	Path     string
	Got      []byte
	Want     []byte
	Existing bool // false if Got is missing (file doesn't exist)
}

// Run loads each Target's BMM, plans emission, and writes (or
// verifies) every generated file.
func Run(opts Options) (*Result, error) {
	if opts.ResourcesDir == "" {
		return nil, fmt.Errorf("bmmgen.Run: ResourcesDir is required")
	}
	if opts.OutDir == "" {
		opts.OutDir = "."
	}
	targets := opts.Targets
	if len(targets) == 0 {
		targets = DefaultTargets()
	}
	if opts.RootID != "" {
		// Legacy single-target path — override the first target only.
		targets = append([]Target(nil), targets...)
		targets[0].RootID = opts.RootID
	}

	resolver := wrappedResolver{root: opts.ResourcesDir}
	result := &Result{}

	for _, t := range targets {
		tr, err := runTarget(opts, t, resolver, result)
		if err != nil {
			return result, err
		}
		result.PerTarget = append(result.PerTarget, tr)
	}
	return result, nil
}

// runTarget generates (or verifies) one target. Returns the
// per-target diagnostic counters and appends to the global Result.
func runTarget(opts Options, t Target, resolver wrappedResolver, result *Result) (TargetResult, error) {
	tr := TargetResult{Target: t}
	plan, err := BuildPlanForTarget(context.Background(), t, resolver)
	if err != nil {
		return tr, err
	}
	result.Notes = append(result.Notes, plan.Notes...)

	outDir := filepath.Join(opts.OutDir, t.OutSubDir)
	for _, f := range plan.Files {
		body, err := RenderFile(plan, f)
		if err != nil {
			return tr, err
		}
		path := filepath.Join(outDir, f.FileBase+"_gen.go")
		tr.Files = append(tr.Files, path)
		result.Files = append(result.Files, path)
		if opts.Verify {
			drift, err := compareFile(path, body)
			if err != nil {
				return tr, err
			}
			if drift != nil {
				result.Drifts = append(result.Drifts, *drift)
			}
		} else {
			if err := writeAtomic(path, body); err != nil {
				return tr, err
			}
		}

		// Canonical-JSON marshaller companion. Skip files with no
		// concrete classes (RenderMarshalJSONFile returns nil bytes);
		// in verify mode, also reject a stale companion still on disk.
		marBody, err := RenderMarshalJSONFile(plan, f)
		if err != nil {
			return tr, err
		}
		marPath := filepath.Join(outDir, f.FileBase+"_jsonmar_gen.go")
		if marBody == nil {
			if opts.Verify {
				if _, statErr := os.Stat(marPath); statErr == nil {
					result.Drifts = append(result.Drifts, DriftRecord{Path: marPath, Existing: true})
				}
			}
		} else {
			tr.Files = append(tr.Files, marPath)
			result.Files = append(result.Files, marPath)
			if opts.Verify {
				drift, err := compareFile(marPath, marBody)
				if err != nil {
					return tr, err
				}
				if drift != nil {
					result.Drifts = append(result.Drifts, *drift)
				}
			} else {
				if err := writeAtomic(marPath, marBody); err != nil {
					return tr, err
				}
			}
		}

		// Canonical-JSON unmarshaller companion — one per marshaller
		// file (every concrete class). Same skip-when-empty +
		// drift-on-stale rules as the marshaller.
		unmarBody, err := RenderUnmarshalJSONFile(plan, f)
		if err != nil {
			return tr, err
		}
		unmarPath := filepath.Join(outDir, f.FileBase+"_jsonunmar_gen.go")
		if unmarBody == nil {
			if opts.Verify {
				if _, statErr := os.Stat(unmarPath); statErr == nil {
					result.Drifts = append(result.Drifts, DriftRecord{Path: unmarPath, Existing: true})
				}
			}
			continue
		}
		tr.Files = append(tr.Files, unmarPath)
		result.Files = append(result.Files, unmarPath)
		if opts.Verify {
			drift, err := compareFile(unmarPath, unmarBody)
			if err != nil {
				return tr, err
			}
			if drift != nil {
				result.Drifts = append(result.Drifts, *drift)
			}
		} else {
			if err := writeAtomic(unmarPath, unmarBody); err != nil {
				return tr, err
			}
		}
	}

	// Type-registry file lives in the target package, not in typereg/.
	regBody, err := RenderTypeRegFile(plan)
	if err != nil {
		return tr, err
	}
	regPath := filepath.Join(outDir, "typereg_gen.go")
	tr.Files = append(tr.Files, regPath)
	result.Files = append(result.Files, regPath)
	if opts.Verify {
		drift, err := compareFile(regPath, regBody)
		if err != nil {
			return tr, err
		}
		if drift != nil {
			result.Drifts = append(result.Drifts, *drift)
		}
	} else {
		if err := writeAtomic(regPath, regBody); err != nil {
			return tr, err
		}
	}

	tr.MethodStubsEmitted = plan.MethodStubsEmitted
	tr.MethodTodoEscapes = plan.MethodTodoEscapes
	result.MethodStubsEmitted += plan.MethodStubsEmitted
	result.MethodTodoEscapes += plan.MethodTodoEscapes
	return tr, nil
}

// compareFile reads path and returns nil if its content equals want.
// Returns a [DriftRecord] (existing=false) when the file is missing.
func compareFile(path string, want []byte) (*DriftRecord, error) {
	got, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return &DriftRecord{Path: path, Want: want, Existing: false}, nil
		}
		return nil, fmt.Errorf("bmmgen.compareFile read %s: %w", path, err)
	}
	if bytes.Equal(got, want) {
		return nil, nil
	}
	return &DriftRecord{Path: path, Got: got, Want: want, Existing: true}, nil
}

// writeAtomic writes body to path via a "<path>.tmp" rename. Skips
// writing entirely if path already contains byte-identical bytes —
// preserves the modification time and prevents IDEs from reloading
// unchanged files needlessly.
func writeAtomic(path string, body []byte) error {
	if existing, err := os.ReadFile(path); err == nil && bytes.Equal(existing, body) {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("bmmgen.writeAtomic mkdir %s: %w", filepath.Dir(path), err)
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, body, 0o644); err != nil {
		return fmt.Errorf("bmmgen.writeAtomic write %s: %w", tmp, err)
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("bmmgen.writeAtomic rename %s -> %s: %w", tmp, path, err)
	}
	return nil
}
