package bmmgen

import (
	"bytes"
	"fmt"
	"go/format"
	"slices"

	"github.com/cadasto/openehr-sdk-go/openehr/bmm"
)

// RenderRMInfoFile produces the `openehr/rm/rminfo/lookup_gen.go`
// data table from a planned RM emission. It walks every class in
// `plan.Classes`, computes the effective property set (own +
// inherited from ancestors, ancestor-order preserved, own overrides
// parent on same name), and emits a single `defaultData` map literal.
//
// Returns nil when the target is not the RM target (rminfo is only
// generated alongside RM). The caller is expected to gate by target
// before invoking.
//
// Output is deterministic: outer map keys sorted alphabetically,
// inner attribute maps sorted alphabetically, AttrOrder preserves
// the merged BMM declaration order (ancestors first, then own).
func RenderRMInfoFile(plan *Plan) ([]byte, error) {
	if plan.Target.GoPackage != "rm" {
		return nil, nil
	}

	type entry struct {
		className string
		attrs     map[string]rmAttr
		order     []string
	}

	classNames := make([]string, 0, len(plan.Classes))
	for name, pc := range plan.Classes {
		if pc.External || pc.IsPrimitive {
			continue
		}
		// Only carry classes that actually have an effective
		// property set — skip enums and pure markers.
		if _, ok := pc.Class.(*bmm.Enumeration); ok {
			continue
		}
		classNames = append(classNames, name)
	}
	slices.Sort(classNames)

	entries := make([]entry, 0, len(classNames))
	for _, name := range classNames {
		attrs, order := effectiveProperties(plan, name)
		if len(attrs) == 0 {
			continue
		}
		entries = append(entries, entry{className: name, attrs: attrs, order: order})
	}

	var body bytes.Buffer
	body.WriteString("// Code generated by bmmgen; DO NOT EDIT.\n")
	fmt.Fprintf(&body, "// Source: %s\n\n", plan.Target.SourceLabel)
	body.WriteString("package rminfo\n\n")
	body.WriteString("var defaultData = map[string]ClassMeta{\n")
	for _, e := range entries {
		fmt.Fprintf(&body, "\t%q: {\n", e.className)
		body.WriteString("\t\tAttributes: map[string]AttrMeta{\n")
		// Inner map deterministic on name.
		innerNames := make([]string, 0, len(e.attrs))
		for n := range e.attrs {
			innerNames = append(innerNames, n)
		}
		slices.Sort(innerNames)
		for _, n := range innerNames {
			a := e.attrs[n]
			fmt.Fprintf(&body, "\t\t\t%q: {TypeName: %q, Required: %t, Container: %t},\n",
				n, a.typeName, a.required, a.container)
		}
		body.WriteString("\t\t},\n")
		body.WriteString("\t\tAttrOrder: []string{")
		for i, n := range e.order {
			if i > 0 {
				body.WriteString(", ")
			}
			fmt.Fprintf(&body, "%q", n)
		}
		body.WriteString("},\n")
		body.WriteString("\t},\n")
	}
	body.WriteString("}\n")
	formatted, err := format.Source(body.Bytes())
	if err != nil {
		return body.Bytes(), fmt.Errorf("gofmt rminfo/lookup_gen.go: %w", err)
	}
	return formatted, nil
}

// rmAttr is an internal lightweight mirror of rminfo.AttrMeta used
// during plan walking. We avoid importing the rminfo package
// directly to keep the import direction one-way (rminfo does NOT
// depend on bmmgen).
type rmAttr struct {
	typeName  string
	required  bool
	container bool
}

// effectiveProperties returns the merged (own + inherited) property
// set of a BMM class. Properties are collected ancestor-first via a
// depth-first walk; when a property name appears at multiple levels
// the most-derived definition wins, but its position in AttrOrder is
// fixed by the FIRST ancestor that declared it (BMM-spec linearisation
// rule: redefinition keeps the parent's slot).
func effectiveProperties(plan *Plan, className string) (map[string]rmAttr, []string) {
	out := make(map[string]rmAttr)
	var order []string
	seen := make(map[string]bool)
	visitedClass := make(map[string]bool)

	var visit func(name string)
	visit = func(name string) {
		if visitedClass[name] {
			return
		}
		visitedClass[name] = true
		pc, ok := plan.Classes[name]
		if !ok {
			return
		}
		// Visit ancestors first so their property names land earlier
		// in AttrOrder. Multiple inheritance is rare in the openEHR
		// BMM; when it occurs we follow declaration order of
		// Ancestors().
		for _, anc := range pc.Class.Ancestors() {
			visit(anc)
		}
		props, propOrder := classProperties(pc.Class)
		for _, propName := range propOrder {
			prop := props[propName]
			attr, ok := propToAttr(prop)
			if !ok {
				continue
			}
			out[propName] = attr // most-derived wins on shape/required/container.
			if !seen[propName] {
				seen[propName] = true
				order = append(order, propName)
			}
		}
	}
	visit(className)
	return out, order
}

// classProperties returns the BMM (properties, declarationOrder) of
// a class. SimpleClass and Interface carry properties; Enumeration
// does not (returns nil/nil).
func classProperties(c bmm.Class) (map[string]bmm.Property, []string) {
	switch cls := c.(type) {
	case *bmm.SimpleClass:
		return cls.Properties, cls.PropertyOrder
	case *bmm.Interface:
		return cls.Properties, cls.PropertyOrder
	default:
		return nil, nil
	}
}

// propToAttr unpacks a BMM Property into the rminfo AttrMeta shape.
// Returns ok=false for properties we cannot translate (typeless
// generic-parameter open properties without a concrete bound).
//
// IsMandatory is exposed via Go struct embedding (propertyCommon
// is embedded in each concrete Property variant), so the field
// access on the concrete type compiles even though the Property
// interface does not declare it.
func propToAttr(p bmm.Property) (rmAttr, bool) {
	switch v := p.(type) {
	case *bmm.SingleProperty:
		return rmAttr{
			typeName:  v.TypeName,
			required:  v.IsMandatory,
			container: false,
		}, true
	case *bmm.SinglePropertyOpen:
		return rmAttr{
			typeName:  v.TypeName,
			required:  v.IsMandatory,
			container: false,
		}, true
	case *bmm.ContainerProperty:
		return rmAttr{
			typeName:  containerInnerType(v.TypeDef),
			required:  containerRequired(v.Cardinality, v.IsMandatory),
			container: true,
		}, true
	case *bmm.GenericProperty:
		return rmAttr{
			typeName:  genericRootType(v.TypeDef),
			required:  v.IsMandatory,
			container: false,
		}, true
	default:
		return rmAttr{}, false
	}
}

// containerInnerType extracts the BMM type name of a container
// property's element. Falls back to a sentinel "Any" when the type
// definition is malformed (should not occur on the pinned BMM).
func containerInnerType(td *bmm.ContainerType) string {
	if td == nil || td.TypeDef == nil {
		return "Any"
	}
	switch inner := td.TypeDef.(type) {
	case *bmm.SimpleType:
		return inner.TypeName
	case *bmm.GenericType:
		return inner.RootType
	case *bmm.ContainerType:
		// Nested containers are rare in the openEHR BMM; report the
		// innermost element type so downstream consumers see a
		// concrete RM class name when they descend.
		return containerInnerType(inner)
	default:
		return "Any"
	}
}

// containerRequired reports whether a container property is required.
// True when:
//   - the propertyCommon.is_mandatory flag is set, OR
//   - the cardinality lower bound is >= 1.
func containerRequired(card *bmm.Cardinality, mandatory bool) bool {
	if mandatory {
		return true
	}
	if card != nil && card.Lower >= 1 {
		return true
	}
	return false
}

// genericRootType returns the BMM root type name for a GenericType.
// Used by GenericProperty to expose the outer class name (e.g.
// "INTERVAL" for an INTERVAL[DV_QUANTITY] property).
func genericRootType(td bmm.Type) string {
	if td == nil {
		return "Any"
	}
	switch t := td.(type) {
	case *bmm.GenericType:
		return t.RootType
	case *bmm.SimpleType:
		return t.TypeName
	default:
		return "Any"
	}
}
