// Code generated by termgen; DO NOT EDIT.
// Source: resources/terminology/openehr_terminology.xml — openEHR TERM Release-3.0.0
// (terminology version 3.0.0, sha256 a1a64cc8665afff3992b4c511997e8a8acd1a3706efc32b775894aaf601f0bcf).
// Regenerate: make termgen. Verify: make termgen-verify.

package terminology

// Version is the openEHR Terminology release the tables below are generated from.
const Version = "3.0.0"

// SourceSHA256 is the sha256 of the pinned openehr_terminology.xml the tables were generated from.
const SourceSHA256 = "a1a64cc8665afff3992b4c511997e8a8acd1a3706efc32b775894aaf601f0bcf"

// AttestationReason is the openEHR terminology group "attestation reason" (openehr_id attestation_reason), 2 concepts.
var AttestationReason = newGroup("attestation_reason", "attestation reason", []Concept{
	{Code: "240", Rubric: "signed"},
	{Code: "648", Rubric: "witnessed"},
})

// AuditChangeType is the openEHR terminology group "audit change type" (openehr_id audit_change_type), 9 concepts.
var AuditChangeType = newGroup("audit_change_type", "audit change type", []Concept{
	{Code: "249", Rubric: "creation"},
	{Code: "250", Rubric: "amendment"},
	{Code: "251", Rubric: "modification"},
	{Code: "252", Rubric: "synthesis"},
	{Code: "523", Rubric: "deleted"},
	{Code: "666", Rubric: "attestation"},
	{Code: "816", Rubric: "restoration"},
	{Code: "817", Rubric: "format conversion"},
	{Code: "253", Rubric: "unknown"},
})

// CompositionCategory is the openEHR terminology group "composition category" (openehr_id composition_category), 4 concepts.
var CompositionCategory = newGroup("composition_category", "composition category", []Concept{
	{Code: "431", Rubric: "persistent"},
	{Code: "451", Rubric: "episodic"},
	{Code: "433", Rubric: "event"},
	{Code: "815", Rubric: "report"},
})

// Property is the openEHR terminology group "property" (openehr_id property), 86 concepts.
var Property = newGroup("property", "property", []Concept{
	{Code: "339", Rubric: "Acceleration"},
	{Code: "342", Rubric: "Acceleration, angular"},
	{Code: "381", Rubric: "Amount (Eq)"},
	{Code: "384", Rubric: "Amount (mole)"},
	{Code: "497", Rubric: "Angle, plane"},
	{Code: "500", Rubric: "Angle, solid"},
	{Code: "335", Rubric: "Area"},
	{Code: "119", Rubric: "Concentration"},
	{Code: "350", Rubric: "Density"},
	{Code: "362", Rubric: "Diffusion coefficient"},
	{Code: "501", Rubric: "Electric capacitance"},
	{Code: "498", Rubric: "Electric charge"},
	{Code: "502", Rubric: "Electric conductance"},
	{Code: "334", Rubric: "Electric current"},
	{Code: "377", Rubric: "Electric field strength"},
	{Code: "655", Rubric: "Electric potential time"},
	{Code: "121", Rubric: "Energy"},
	{Code: "366", Rubric: "Energy density"},
	{Code: "508", Rubric: "Energy dose"},
	{Code: "365", Rubric: "Energy per area"},
	{Code: "364", Rubric: "Energy, linear"},
	{Code: "347", Rubric: "Flow rate, mass"},
	{Code: "352", Rubric: "Flow rate, mass/force"},
	{Code: "351", Rubric: "Flow rate, mass/volume"},
	{Code: "126", Rubric: "Flow rate, volume"},
	{Code: "348", Rubric: "Flux, mass"},
	{Code: "355", Rubric: "Force"},
	{Code: "358", Rubric: "Force per mass"},
	{Code: "357", Rubric: "Force, body"},
	{Code: "382", Rubric: "Frequency"},
	{Code: "586", Rubric: "Glomerular filtration rate"},
	{Code: "373", Rubric: "Heat transfer coefficient"},
	{Code: "505", Rubric: "Illuminance"},
	{Code: "379", Rubric: "Inductance"},
	{Code: "122", Rubric: "Length"},
	{Code: "499", Rubric: "Light intensity"},
	{Code: "123", Rubric: "Loudness"},
	{Code: "504", Rubric: "Luminous flux"},
	{Code: "378", Rubric: "Magnetic flux"},
	{Code: "503", Rubric: "Magnetic flux density"},
	{Code: "124", Rubric: "Mass"},
	{Code: "385", Rubric: "Mass (IU)"},
	{Code: "445", Rubric: "Mass (Units)"},
	{Code: "349", Rubric: "Mass per area"},
	{Code: "344", Rubric: "Moment inertia, area"},
	{Code: "345", Rubric: "Moment inertia, mass"},
	{Code: "340", Rubric: "Momentum"},
	{Code: "346", Rubric: "Momentum flow rate"},
	{Code: "343", Rubric: "Momentum, angular"},
	{Code: "363", Rubric: "Power"},
	{Code: "369", Rubric: "Power density"},
	{Code: "368", Rubric: "Power flux"},
	{Code: "367", Rubric: "Power, linear"},
	{Code: "125", Rubric: "Pressure"},
	{Code: "507", Rubric: "Proportion"},
	{Code: "380", Rubric: "Qualified real"},
	{Code: "506", Rubric: "Radioactivity"},
	{Code: "375", Rubric: "Resistance"},
	{Code: "370", Rubric: "Specific energy"},
	{Code: "371", Rubric: "Specific heat, gas constant"},
	{Code: "337", Rubric: "Specific surface"},
	{Code: "336", Rubric: "Specific volume"},
	{Code: "354", Rubric: "Specific weight"},
	{Code: "356", Rubric: "Surface tension"},
	{Code: "127", Rubric: "Temperature"},
	{Code: "372", Rubric: "Thermal conductivity"},
	{Code: "128", Rubric: "Time"},
	{Code: "359", Rubric: "Torque"},
	{Code: "338", Rubric: "Velocity"},
	{Code: "341", Rubric: "Velocity, angular"},
	{Code: "360", Rubric: "Viscosity, dynamic"},
	{Code: "361", Rubric: "Viscosity, kinematic"},
	{Code: "374", Rubric: "Electric potential"},
	{Code: "129", Rubric: "Volume"},
	{Code: "130", Rubric: "Work"},
	{Code: "685", Rubric: "Refractive power"},
	{Code: "118", Rubric: "<not set>"},
	{Code: "709", Rubric: "Time fraction"},
	{Code: "708", Rubric: "Rate of change, pressure"},
	{Code: "754", Rubric: "Rate of change, frequency"},
	{Code: "755", Rubric: "Arbitrary"},
	{Code: "756", Rubric: "Medication dose rate"},
	{Code: "757", Rubric: "Spectral power"},
	{Code: "758", Rubric: "Spectral power density"},
	{Code: "759", Rubric: "Pace"},
	{Code: "760", Rubric: "Enzyme activity"},
})

// VersionLifecycleState is the openEHR terminology group "version lifecycle state" (openehr_id version_lifecycle_state), 5 concepts.
var VersionLifecycleState = newGroup("version_lifecycle_state", "version lifecycle state", []Concept{
	{Code: "532", Rubric: "complete"},
	{Code: "553", Rubric: "incomplete"},
	{Code: "523", Rubric: "deleted"},
	{Code: "800", Rubric: "inactive"},
	{Code: "801", Rubric: "abandoned"},
})

// ParticipationFunction is the openEHR terminology group "participation function" (openehr_id participation_function), 1 concept.
var ParticipationFunction = newGroup("participation_function", "participation function", []Concept{
	{Code: "253", Rubric: "unknown"},
})

// NullFlavours is the openEHR terminology group "null flavours" (openehr_id null_flavours), 4 concepts.
var NullFlavours = newGroup("null_flavours", "null flavours", []Concept{
	{Code: "271", Rubric: "no information"},
	{Code: "253", Rubric: "unknown"},
	{Code: "272", Rubric: "masked"},
	{Code: "273", Rubric: "not applicable"},
})

// ParticipationMode is the openEHR terminology group "participation mode" (openehr_id participation_mode), 32 concepts.
var ParticipationMode = newGroup("participation_mode", "participation mode", []Concept{
	{Code: "193", Rubric: "not specified"},
	{Code: "216", Rubric: "face-to-face communication"},
	{Code: "223", Rubric: "interpreted face-to-face communication"},
	{Code: "217", Rubric: "signing (face-to-face)"},
	{Code: "195", Rubric: "live audiovisual; videoconference; videophone"},
	{Code: "198", Rubric: "videoconferencing"},
	{Code: "197", Rubric: "videophone"},
	{Code: "218", Rubric: "signing over video"},
	{Code: "224", Rubric: "interpreted video communication"},
	{Code: "194", Rubric: "asynchronous audiovisual; recorded video"},
	{Code: "196", Rubric: "recorded video"},
	{Code: "202", Rubric: "live audio-only; telephone; internet phone; teleconference"},
	{Code: "204", Rubric: "telephone"},
	{Code: "203", Rubric: "teleconference"},
	{Code: "205", Rubric: "internet telephone"},
	{Code: "222", Rubric: "interpreted audio-only"},
	{Code: "199", Rubric: "asynchronous audio-only; dictated; voice mail"},
	{Code: "200", Rubric: "dictated"},
	{Code: "201", Rubric: "voice-mail"},
	{Code: "212", Rubric: "live text-only; internet chat; SMS chat; interactive written note"},
	{Code: "213", Rubric: "internet chat"},
	{Code: "214", Rubric: "SMS chat"},
	{Code: "215", Rubric: "interactive written note"},
	{Code: "206", Rubric: "asynchronous text; email; fax; letter; handwritten note; SMS message"},
	{Code: "211", Rubric: "handwritten note"},
	{Code: "210", Rubric: "printed/typed letter"},
	{Code: "207", Rubric: "email"},
	{Code: "208", Rubric: "facsimile/telefax"},
	{Code: "221", Rubric: "translated text"},
	{Code: "209", Rubric: "SMS message"},
	{Code: "219", Rubric: "physically present"},
	{Code: "220", Rubric: "physically remote"},
})

// InstructionStates is the openEHR terminology group "instruction states" (openehr_id instruction_states), 10 concepts.
var InstructionStates = newGroup("instruction_states", "instruction states", []Concept{
	{Code: "524", Rubric: "initial"},
	{Code: "526", Rubric: "planned"},
	{Code: "527", Rubric: "postponed"},
	{Code: "528", Rubric: "cancelled"},
	{Code: "529", Rubric: "scheduled"},
	{Code: "245", Rubric: "active"},
	{Code: "530", Rubric: "suspended"},
	{Code: "531", Rubric: "aborted"},
	{Code: "532", Rubric: "completed"},
	{Code: "533", Rubric: "expired"},
})

// InstructionTransitions is the openEHR terminology group "instruction transitions" (openehr_id instruction_transitions), 20 concepts.
var InstructionTransitions = newGroup("instruction_transitions", "instruction transitions", []Concept{
	{Code: "535", Rubric: "initiate"},
	{Code: "536", Rubric: "plan step"},
	{Code: "537", Rubric: "postpone"},
	{Code: "538", Rubric: "restore"},
	{Code: "166", Rubric: "cancel"},
	{Code: "542", Rubric: "postponed step"},
	{Code: "539", Rubric: "schedule"},
	{Code: "534", Rubric: "scheduled step"},
	{Code: "540", Rubric: "start"},
	{Code: "541", Rubric: "do"},
	{Code: "543", Rubric: "active step"},
	{Code: "544", Rubric: "suspend"},
	{Code: "545", Rubric: "suspended step"},
	{Code: "546", Rubric: "resume"},
	{Code: "547", Rubric: "abort"},
	{Code: "548", Rubric: "finish"},
	{Code: "549", Rubric: "time out"},
	{Code: "550", Rubric: "notify aborted"},
	{Code: "551", Rubric: "notify completed"},
	{Code: "552", Rubric: "notify cancelled"},
})

// SubjectRelationship is the openEHR terminology group "subject relationship" (openehr_id subject_relationship), 36 concepts.
var SubjectRelationship = newGroup("subject_relationship", "subject relationship", []Concept{
	{Code: "0", Rubric: "self"},
	{Code: "3", Rubric: "foetus"},
	{Code: "10", Rubric: "mother"},
	{Code: "9", Rubric: "father"},
	{Code: "6", Rubric: "donor"},
	{Code: "253", Rubric: "unknown"},
	{Code: "261", Rubric: "adopted daughter"},
	{Code: "260", Rubric: "adopted son"},
	{Code: "259", Rubric: "adoptive father"},
	{Code: "258", Rubric: "adoptive mother"},
	{Code: "256", Rubric: "biological father"},
	{Code: "255", Rubric: "biological mother"},
	{Code: "23", Rubric: "brother"},
	{Code: "28", Rubric: "child"},
	{Code: "265", Rubric: "cohabitee"},
	{Code: "257", Rubric: "cousin"},
	{Code: "29", Rubric: "daughter"},
	{Code: "264", Rubric: "guardian"},
	{Code: "39", Rubric: "maternal aunt"},
	{Code: "8", Rubric: "maternal grandfather"},
	{Code: "7", Rubric: "maternal grandmother"},
	{Code: "38", Rubric: "maternal uncle"},
	{Code: "189", Rubric: "neonate"},
	{Code: "254", Rubric: "parent"},
	{Code: "22", Rubric: "partner/spouse"},
	{Code: "41", Rubric: "paternal aunt"},
	{Code: "36", Rubric: "paternal grandfather"},
	{Code: "37", Rubric: "paternal grandmother"},
	{Code: "40", Rubric: "paternal uncle"},
	{Code: "27", Rubric: "sibling"},
	{Code: "24", Rubric: "sister"},
	{Code: "31", Rubric: "son"},
	{Code: "263", Rubric: "step father"},
	{Code: "262", Rubric: "step mother"},
	{Code: "25", Rubric: "step or half brother"},
	{Code: "26", Rubric: "step or half sister"},
})

// TermMappingPurpose is the openEHR terminology group "term mapping purpose" (openehr_id term_mapping_purpose), 3 concepts.
var TermMappingPurpose = newGroup("term_mapping_purpose", "term mapping purpose", []Concept{
	{Code: "669", Rubric: "public health"},
	{Code: "670", Rubric: "reimbursement"},
	{Code: "671", Rubric: "research study"},
})

// EventMathFunction is the openEHR terminology group "event math function" (openehr_id event_math_function), 11 concepts.
var EventMathFunction = newGroup("event_math_function", "event math function", []Concept{
	{Code: "145", Rubric: "minimum"},
	{Code: "144", Rubric: "maximum"},
	{Code: "267", Rubric: "mode"},
	{Code: "268", Rubric: "median"},
	{Code: "146", Rubric: "mean"},
	{Code: "147", Rubric: "change"},
	{Code: "148", Rubric: "total"},
	{Code: "149", Rubric: "variation"},
	{Code: "521", Rubric: "decrease"},
	{Code: "522", Rubric: "increase"},
	{Code: "640", Rubric: "actual"},
})

// Setting is the openEHR terminology group "setting" (openehr_id setting), 14 concepts.
var Setting = newGroup("setting", "setting", []Concept{
	{Code: "225", Rubric: "home"},
	{Code: "227", Rubric: "emergency care"},
	{Code: "228", Rubric: "primary medical care"},
	{Code: "229", Rubric: "primary nursing care"},
	{Code: "230", Rubric: "primary allied health care"},
	{Code: "231", Rubric: "midwifery care"},
	{Code: "232", Rubric: "secondary medical care"},
	{Code: "233", Rubric: "secondary nursing care"},
	{Code: "234", Rubric: "secondary allied health care"},
	{Code: "235", Rubric: "complementary health care"},
	{Code: "236", Rubric: "dental care"},
	{Code: "237", Rubric: "nursing home care"},
	{Code: "802", Rubric: "mental healthcare"},
	{Code: "238", Rubric: "other care"},
})

// ExtractContentType is the openEHR terminology group "extract content type" (openehr_id extract_content_type), 6 concepts.
var ExtractContentType = newGroup("extract_content_type", "extract content type", []Concept{
	{Code: "803", Rubric: "openEHR EHR"},
	{Code: "804", Rubric: "openEHR Demographic"},
	{Code: "805", Rubric: "openEHR synchronisation"},
	{Code: "806", Rubric: "openEHR generic"},
	{Code: "807", Rubric: "generic EMR"},
	{Code: "808", Rubric: "other"},
})

// ExtractActionType is the openEHR terminology group "extract action type" (openehr_id extract_action_type), 3 concepts.
var ExtractActionType = newGroup("extract_action_type", "extract action type", []Concept{
	{Code: "809", Rubric: "cancel"},
	{Code: "810", Rubric: "resend"},
	{Code: "811", Rubric: "send new"},
})

// ExtractUpdateTriggerEventType is the openEHR terminology group "extract update trigger event type" (openehr_id extract_update_trigger_event_type), 3 concepts.
var ExtractUpdateTriggerEventType = newGroup("extract_update_trigger_event_type", "extract update trigger event type", []Concept{
	{Code: "812", Rubric: "any change"},
	{Code: "813", Rubric: "correction"},
	{Code: "814", Rubric: "update"},
})

// CompressionAlgorithms is the openEHR terminology code set "compression algorithms" (openehr_id compression_algorithms), 5 codes.
var CompressionAlgorithms = newCodeSet("compression_algorithms", "compression algorithms", []string{"compress", "deflate", "gzip", "zlib", "other"})

// IntegrityCheckAlgorithms is the openEHR terminology code set "integrity check algorithms" (openehr_id integrity_check_algorithms), 7 codes.
var IntegrityCheckAlgorithms = newCodeSet("integrity_check_algorithms", "integrity check algorithms", []string{"SHA-1", "SHA-224", "SHA-256", "SHA-384", "SHA-512", "SHA-512/224", "SHA-512/256"})

// NormalStatuses is the openEHR terminology code set "normal statuses" (openehr_id normal_statuses), 7 codes.
var NormalStatuses = newCodeSet("normal_statuses", "normal statuses", []string{"HHH", "HH", "H", "N", "L", "LL", "LLL"})

// groups is the pin's 17 groups in document order — what Groups and GroupByID range over.
var groups = []*Group{AttestationReason, AuditChangeType, CompositionCategory, Property, VersionLifecycleState, ParticipationFunction, NullFlavours, ParticipationMode, InstructionStates, InstructionTransitions, SubjectRelationship, TermMappingPurpose, EventMathFunction, Setting, ExtractContentType, ExtractActionType, ExtractUpdateTriggerEventType}

// codeSets is the pin's 3 code sets in document order — what CodeSets and CodeSetByID range over.
var codeSets = []*CodeSet{CompressionAlgorithms, IntegrityCheckAlgorithms, NormalStatuses}
