#!/usr/bin/env bash
# spec-context.sh — assemble the full SDD context for one REQ into a single
# markdown bundle: registry row, traceability block, canonical spec excerpt,
# the plans and ADRs that name it, and any research strands that touch it.
#
# Agents (and humans) run this instead of hunting across files — it routes to
# canonical sources in one shot and states the PROBE-driven definition of done.
#
# Usage: scripts/spec-context.sh REQ-094     (also accepts: 094, req-094)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SPECS="${ROOT}/docs/specifications"
REQ_REG="${SPECS}/REQ.md"
YAML="${SPECS}/traceability.yaml"
STRANDS="${SPECS}/research-strands.md"

raw="${1:-}"
[[ -n "$raw" ]] || { echo "usage: $(basename "$0") REQ-NNN (e.g. 094)" >&2; exit 2; }
num="$(printf '%s' "$raw" | tr -cd '0-9')"
[[ -n "$num" ]] || { echo "error: no REQ number in '$raw'" >&2; exit 2; }
REQ="REQ-$(printf '%03d' "$((10#$num))")"
N="$((10#$num))"

echo "# Context bundle — ${REQ}"
echo
echo "_Routing aid generated by \`scripts/spec-context.sh\`. Canonical prose lives in the linked spec — read it, don't reimplement from this summary._"
echo

# --- 1) Registry row -------------------------------------------------------
echo "## Registry (REQ.md)"
echo
row="$(awk -v id="$REQ" '
  index($0, "<!-- BEGIN GENERATED: registry ") == 1 { inside = 1; next }
  index($0, "<!-- END GENERATED: registry ") == 1 { inside = 0 }
  inside && index($0, "| " id " |") == 1
' "$REQ_REG" 2>/dev/null || true)"
if [[ -n "$row" ]]; then
  printf '| ID | Title | Canonical | Stability | Impl. |\n|---|---|---|---|---|\n%s\n' "$row"
else
  echo "_not found in REQ.md registry_"
fi
echo

# --- 2) Traceability block -------------------------------------------------
echo "## Traceability (traceability.yaml)"
echo
block="$(awk -v id="$REQ" '
  $0 ~ "^[[:space:]]*-[[:space:]]*id:[[:space:]]*" id "([[:space:]]|$)" { g=1 }
  g && /^[[:space:]]*-[[:space:]]*id:/ && $0 !~ ("id:[[:space:]]*" id "([[:space:]]|$)") { exit }
  g { print }
' "$YAML")"
if [[ -n "$block" ]]; then printf '```yaml\n%s\n```\n' "$block"; else echo "_no traceability entry — add one (spec-check enforces coverage)_"; fi
echo

# --- 3) Canonical spec excerpt ---------------------------------------------
canon="$(printf '%s' "$row" | grep -oE '\]\([^)]+\)' | tail -1 | sed -E 's/^\]\(//; s/\)$//' || true)"
echo "## Canonical spec"
echo
if [[ -n "$canon" ]]; then
  file="${canon%%#*}"; anchor="${canon#*#}"
  echo "Source: [\`docs/specifications/${file}\`](${file}#${anchor})"
  echo
  specfile="${SPECS}/${file}"
  if [[ -f "$specfile" ]]; then
    start="$(grep -nE "^#+ .*${REQ}([^0-9]|$)" "$specfile" | head -1 | cut -d: -f1 || true)"
    if [[ -n "$start" ]]; then
      printf '```markdown\n'
      awk -v s="$start" 'NR>=s { if (NR>s && /^#+ /) exit; print; if (NR-s>=44) { print "… (truncated — open the spec for the rest)"; exit } }' "$specfile"
      printf '```\n'
    else
      echo "_(heading for ${REQ} not auto-located — open the link above)_"
    fi
  else
    echo "_canonical file ${file} not found_"
  fi
else
  echo "_no canonical link in the registry row_"
fi
echo

# --- 4) Plans and ADRs that name this REQ ---------------------------------
# The map carries no plans or ADRs. An ADR names its REQs in the bullet list
# above its first `##` heading. Plans are working notes outside the
# traceability chain, with no required header: a plan is listed when its
# text names the REQ anywhere. Only the whole identifier counts (REQ-06 never
# matches REQ-060). A plan may also name a range, REQ-060..068, which covers
# every number from the first to the last, as in the strands section below.
names_req() { grep -qwF -- "$REQ" <<< "$1"; }
covers_req() {
  names_req "$1" && return 0
  local tok lo hi
  while read -r tok; do
    [[ -n "$tok" ]] || continue
    lo="${tok#REQ-}"; lo="${lo%%..*}"; hi="${tok##*..}"
    (( N >= 10#$lo && N <= 10#$hi )) && return 0
  done < <(grep -oE 'REQ-[0-9]+\.\.[0-9]+' <<< "$1" || true)
  return 1
}
doc_title() { grep -m1 -E '^# ' "$1" | sed -E 's/^# (Plan[^A-Za-z]+)?//' || true; }

echo "## Plans"
echo
plan_hits=""
for f in "${ROOT}"/docs/plans/*.md; do
  [[ -f "$f" ]] || continue
  case "$(basename "$f")" in README.md|_template.md) continue ;; esac
  covers_req "$(cat "$f")" || continue
  plan_hits+="- \`${f#"${ROOT}/"}\`: $(doc_title "$f")"$'\n'
done
if [[ -n "$plan_hits" ]]; then printf '%s' "$plan_hits"; else echo "_no plan names ${REQ}_"; fi
echo

echo "## ADRs"
echo
adr_hits=""
for f in "${ROOT}"/docs/adr/[0-9]*.md; do
  [[ -f "$f" ]] || continue
  header="$(awk '/^## /{exit} /^- /' "$f")"
  [[ -n "$header" ]] && names_req "$header" || continue
  adr_hits+="- \`${f#"${ROOT}/"}\`: $(doc_title "$f")"$'\n'
done
if [[ -n "$adr_hits" ]]; then printf '%s' "$adr_hits"; else echo "_none names ${REQ} in its header_"; fi
echo

# --- 5) Research strands touching this REQ (from the Index table) ----------
echo "## Research strands touching ${REQ}"
echo
hits="$(awk -F'|' -v n="$N" '
  function touches(cell,   tok,arr,lo,hi) {
    while (match(cell, /REQ-[0-9]+(\.\.[0-9]+)?/)) {
      tok=substr(cell, RSTART, RLENGTH); cell=substr(cell, RSTART+RLENGTH)
      if (tok ~ /\.\./) { split(tok, arr, /REQ-|\.\./); lo=arr[2]+0; hi=arr[3]+0; if (n>=lo && n<=hi) return 1 }
      else { split(tok, arr, /REQ-/); if (arr[2]+0==n) return 1 }
    }
    return 0
  }
  /^\|[[:space:]]*\[STRAND-/ { if (touches($(NF-1))) print "- " $2 " — status: " $4 }
' "$STRANDS")"
if [[ -n "$hits" ]]; then
  printf '%s\n' "$hits" | sed -E 's/\[([^]]*)\]\([^)]*\)/\1/g; s/[[:space:]]+/ /g; s/ - /- /'
else
  echo "_none_"
fi
echo

# --- definition of done ----------------------------------------------------
echo "---"
echo "**Definition of done:** code + tests green **and** \`traceability.yaml\` updated and the canonical spec current. For wire/client work the \`probes:\` listed above are part of done — each must be Implemented (Sandbox) in [conformance.md](docs/specifications/conformance.md) or explicitly deferred in the plan."
