// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

// BMM package: org.openehr.base.base_types.definitions

// BasicDefinitions Defines globally used constant values.
type BasicDefinitions struct {
}

// OpenehrDefinitions Inheritance class to provide access to constants defined in other packages.
type OpenehrDefinitions struct {
	BasicDefinitions
}

// ValidityKind An enumeration of three values that may commonly occur in constraint models.
//
// Use as the type of any attribute within this model, which expresses constraint on some attribute in a class in a reference model. For example to indicate validity
// of Date/Time fields.
type ValidityKind string

const (
	// ValidityKindMandatory Constant to indicate mandatory presence of something.
	ValidityKindMandatory ValidityKind = "mandatory"
	// ValidityKindOptional Constant to indicate optional presence of something.
	ValidityKindOptional ValidityKind = "optional"
	// ValidityKindProhibited Constant to indicate disallowed presence of something.
	ValidityKindProhibited ValidityKind = "prohibited"
	// ValidityKindDisallowed (DEPRECATED) Constant to indicate disallowed presence of something.
	//
	// NOTE: This is only used by AOM 1.4, while AOM 2 is using the `prohibited` alternative value.
	ValidityKindDisallowed ValidityKind = "disallowed"
)

// VersionStatus Status of a versioned artefact, as one of a number of possible values: uncontrolled, prerelease, release, build.
type VersionStatus string

const (
	// VersionStatusAlpha Value representing a version which is 'unstable', i.e. contains an unknown size of change with respect to its base version. Rendered with the build number as a string in the form `N.M.P-alpha.B` e.g. `2.0.1-alpha.154`.
	VersionStatusAlpha VersionStatus = "alpha"
	// VersionStatusBeta Value representing a version which is 'beta', i.e. contains an unknown but reducing size of change with respect to its base version. Rendered with the build number as a string in the form `N.M.P-beta.B` e.g. `2.0.1-beta.154`.
	VersionStatusBeta VersionStatus = "beta"
	// VersionStatusReleaseCandidate Value representing a version which is 'release candidate', i.e. contains only patch-level changes on the base version. Rendered as a string as `N.M.P-rc.B` e.g. `2.0.1-rc.27`.
	VersionStatusReleaseCandidate VersionStatus = "release_candidate"
	// VersionStatusReleased Value representing a version which is 'released', i.e. is the definitive base version. `N.M.P` e.g. `2.0.1`.
	VersionStatusReleased VersionStatus = "released"
	// VersionStatusBuild Value representing a version which is a build of the current base release. Rendered with the build number as a string in the form `N.M.P+B` e.g. `2.0.1+33`.
	VersionStatusBuild VersionStatus = "build"
)
