// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import "encoding/json"

// BMM package: org.openehr.base.base_types.identification — canonical-JSON MarshalJSON companions

type AccessGroupRefJSONMarshaller struct {
	Class string `json:"_type"`
	// Namespace Namespace to which this identifier belongs in the local system context (and possibly in any other openEHR compliant environment) e.g.  terminology ,  demographic . These names are not yet standardised. Legal values for `_namespace_` are:
	//
	// * `"local"`
	// * `"unknown"`
	// * a string matching the standard regex `[a-zA-Z][a-zA-Z0-9_.:\/&?=+-]*`.
	//
	// Note that the first two are just special values of the regex, and will be matched by it.
	Namespace string `json:"namespace"`
	// Type Name of the  class (concrete or abstract) of object to which this identifier type refers, e.g. `PARTY`, `PERSON`,  `GUIDELINE`  etc. These class names are from the relevant reference model. The type name `ANY` can be used to indicate that any type is accepted (e.g. if the type is unknown).
	Type string `json:"type"`
	// ID Globally unique id of an object, regardless of where it is stored.
	ID ObjectID `json:"id"`
}

// MarshalJSON emits canonical openEHR JSON for AccessGroupRef with `_type`
// (value "ACCESS_GROUP_REF") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (a *AccessGroupRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(&AccessGroupRefJSONMarshaller{
		Class:     "ACCESS_GROUP_REF",
		Namespace: a.Namespace,
		Type:      a.Type,
		ID:        a.ID,
	})
}

type ArchetypeIDJSONMarshaller struct {
	Class string `json:"_type"`
	// Value The value of the id in the form defined below.
	Value string `json:"value"`
}

// MarshalJSON emits canonical openEHR JSON for ArchetypeID with `_type`
// (value "ARCHETYPE_ID") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (a *ArchetypeID) MarshalJSON() ([]byte, error) {
	return json.Marshal(&ArchetypeIDJSONMarshaller{
		Class: "ARCHETYPE_ID",
		Value: a.Value,
	})
}

type GenericIDJSONMarshaller struct {
	Class string `json:"_type"`
	// Value The value of the id in the form defined below.
	Value string `json:"value"`
	// Scheme Name of the scheme to which this identifier conforms. Ideally this name will be recognisable globally but realistically it may be a local ad hoc scheme whose name is not controlled or standardised in any way.
	Scheme string `json:"scheme"`
}

// MarshalJSON emits canonical openEHR JSON for GenericID with `_type`
// (value "GENERIC_ID") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (g *GenericID) MarshalJSON() ([]byte, error) {
	return json.Marshal(&GenericIDJSONMarshaller{
		Class:  "GENERIC_ID",
		Value:  g.Value,
		Scheme: g.Scheme,
	})
}

type HierObjectIDJSONMarshaller struct {
	Class string `json:"_type"`
	// Value The value of the id in the form defined below.
	Value string `json:"value"`
}

// MarshalJSON emits canonical openEHR JSON for HierObjectID with `_type`
// (value "HIER_OBJECT_ID") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (h *HierObjectID) MarshalJSON() ([]byte, error) {
	return json.Marshal(&HierObjectIDJSONMarshaller{
		Class: "HIER_OBJECT_ID",
		Value: h.Value,
	})
}

type ISOOIDJSONMarshaller struct {
	Class string `json:"_type"`
	// Value The value of the id.
	Value string `json:"value"`
}

// MarshalJSON emits canonical openEHR JSON for ISOOID with `_type`
// (value "ISO_OID") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (i *ISOOID) MarshalJSON() ([]byte, error) {
	return json.Marshal(&ISOOIDJSONMarshaller{
		Class: "ISO_OID",
		Value: i.Value,
	})
}

type InternetIDJSONMarshaller struct {
	Class string `json:"_type"`
	// Value The value of the id.
	Value string `json:"value"`
}

// MarshalJSON emits canonical openEHR JSON for InternetID with `_type`
// (value "INTERNET_ID") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (i *InternetID) MarshalJSON() ([]byte, error) {
	return json.Marshal(&InternetIDJSONMarshaller{
		Class: "INTERNET_ID",
		Value: i.Value,
	})
}

type LocatableRefJSONMarshaller struct {
	Class string `json:"_type"`
	// Namespace Namespace to which this identifier belongs in the local system context (and possibly in any other openEHR compliant environment) e.g.  terminology ,  demographic . These names are not yet standardised. Legal values for `_namespace_` are:
	//
	// * `"local"`
	// * `"unknown"`
	// * a string matching the standard regex `[a-zA-Z][a-zA-Z0-9_.:\/&?=+-]*`.
	//
	// Note that the first two are just special values of the regex, and will be matched by it.
	Namespace string `json:"namespace"`
	// Type Name of the  class (concrete or abstract) of object to which this identifier type refers, e.g. `PARTY`, `PERSON`,  `GUIDELINE`  etc. These class names are from the relevant reference model. The type name `ANY` can be used to indicate that any type is accepted (e.g. if the type is unknown).
	Type string `json:"type"`
	// Path The path to an instance, as an absolute path with respect to the object found at `VERSION._data_`. An empty path means that the object referred to by `_id_` is being specified.
	Path *string `json:"path,omitempty"`
	// ID Globally unique id of an object, regardless of where it is stored.
	ID UIDBasedID `json:"id"`
}

// MarshalJSON emits canonical openEHR JSON for LocatableRef with `_type`
// (value "LOCATABLE_REF") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (l *LocatableRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(&LocatableRefJSONMarshaller{
		Class:     "LOCATABLE_REF",
		Namespace: l.Namespace,
		Type:      l.Type,
		Path:      l.Path,
		ID:        l.ID,
	})
}

type ObjectRefJSONMarshaller struct {
	Class string `json:"_type"`
	// Namespace Namespace to which this identifier belongs in the local system context (and possibly in any other openEHR compliant environment) e.g.  terminology ,  demographic . These names are not yet standardised. Legal values for `_namespace_` are:
	//
	// * `"local"`
	// * `"unknown"`
	// * a string matching the standard regex `[a-zA-Z][a-zA-Z0-9_.:\/&?=+-]*`.
	//
	// Note that the first two are just special values of the regex, and will be matched by it.
	Namespace string `json:"namespace"`
	// Type Name of the  class (concrete or abstract) of object to which this identifier type refers, e.g. `PARTY`, `PERSON`,  `GUIDELINE`  etc. These class names are from the relevant reference model. The type name `ANY` can be used to indicate that any type is accepted (e.g. if the type is unknown).
	Type string `json:"type"`
	// ID Globally unique id of an object, regardless of where it is stored.
	ID ObjectID `json:"id"`
}

// MarshalJSON emits canonical openEHR JSON for ObjectRef with `_type`
// (value "OBJECT_REF") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (o *ObjectRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(&ObjectRefJSONMarshaller{
		Class:     "OBJECT_REF",
		Namespace: o.Namespace,
		Type:      o.Type,
		ID:        o.ID,
	})
}

type ObjectVersionIDJSONMarshaller struct {
	Class string `json:"_type"`
	// Value The value of the id in the form defined below.
	Value string `json:"value"`
}

// MarshalJSON emits canonical openEHR JSON for ObjectVersionID with `_type`
// (value "OBJECT_VERSION_ID") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (o *ObjectVersionID) MarshalJSON() ([]byte, error) {
	return json.Marshal(&ObjectVersionIDJSONMarshaller{
		Class: "OBJECT_VERSION_ID",
		Value: o.Value,
	})
}

type PartyRefJSONMarshaller struct {
	Class string `json:"_type"`
	// Namespace Namespace to which this identifier belongs in the local system context (and possibly in any other openEHR compliant environment) e.g.  terminology ,  demographic . These names are not yet standardised. Legal values for `_namespace_` are:
	//
	// * `"local"`
	// * `"unknown"`
	// * a string matching the standard regex `[a-zA-Z][a-zA-Z0-9_.:\/&?=+-]*`.
	//
	// Note that the first two are just special values of the regex, and will be matched by it.
	Namespace string `json:"namespace"`
	// Type Name of the  class (concrete or abstract) of object to which this identifier type refers, e.g. `PARTY`, `PERSON`,  `GUIDELINE`  etc. These class names are from the relevant reference model. The type name `ANY` can be used to indicate that any type is accepted (e.g. if the type is unknown).
	Type string `json:"type"`
	// ID Globally unique id of an object, regardless of where it is stored.
	ID ObjectID `json:"id"`
}

// MarshalJSON emits canonical openEHR JSON for PartyRef with `_type`
// (value "PARTY_REF") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (p *PartyRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(&PartyRefJSONMarshaller{
		Class:     "PARTY_REF",
		Namespace: p.Namespace,
		Type:      p.Type,
		ID:        p.ID,
	})
}

type TemplateIDJSONMarshaller struct {
	Class string `json:"_type"`
	// Value The value of the id in the form defined below.
	Value string `json:"value"`
}

// MarshalJSON emits canonical openEHR JSON for TemplateID with `_type`
// (value "TEMPLATE_ID") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (t *TemplateID) MarshalJSON() ([]byte, error) {
	return json.Marshal(&TemplateIDJSONMarshaller{
		Class: "TEMPLATE_ID",
		Value: t.Value,
	})
}

type TerminologyIDJSONMarshaller struct {
	Class string `json:"_type"`
	// Value The value of the id in the form defined below.
	Value string `json:"value"`
}

// MarshalJSON emits canonical openEHR JSON for TerminologyID with `_type`
// (value "TERMINOLOGY_ID") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (t *TerminologyID) MarshalJSON() ([]byte, error) {
	return json.Marshal(&TerminologyIDJSONMarshaller{
		Class: "TERMINOLOGY_ID",
		Value: t.Value,
	})
}

type UuidJSONMarshaller struct {
	Class string `json:"_type"`
	// Value The value of the id.
	Value string `json:"value"`
}

// MarshalJSON emits canonical openEHR JSON for Uuid with `_type`
// (value "UUID") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (u *Uuid) MarshalJSON() ([]byte, error) {
	return json.Marshal(&UuidJSONMarshaller{
		Class: "UUID",
		Value: u.Value,
	})
}

type VersionTreeIDJSONMarshaller struct {
	Class string `json:"_type"`
	// Value String form of this identifier.
	Value string `json:"value"`
}

// MarshalJSON emits canonical openEHR JSON for VersionTreeID with `_type`
// (value "VERSION_TREE_ID") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (v *VersionTreeID) MarshalJSON() ([]byte, error) {
	return json.Marshal(&VersionTreeIDJSONMarshaller{
		Class: "VERSION_TREE_ID",
		Value: v.Value,
	})
}
