// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/xml"

	"github.com/cadasto/openehr-sdk-go/openehr/serialize/canxml"
)

// BMM package: org.openehr.base.base_types.identification — canonical-XML MarshalXML companions

// BMMName returns "ACCESS_GROUP_REF" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (a *AccessGroupRef) BMMName() string { return "ACCESS_GROUP_REF" }

// MarshalXML emits canonical openEHR XML for AccessGroupRef. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
func (a *AccessGroupRef) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("ACCESS_GROUP_REF")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeElement(a.Namespace, xml.StartElement{Name: xml.Name{Local: "namespace"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(a.Type, xml.StartElement{Name: xml.Name{Local: "type"}}); err != nil {
		return err
	}
	if a.ID != nil {
		if err := canxml.EncodePoly(_e, "id", a.ID); err != nil {
			return err
		}
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "ARCHETYPE_ID" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (a *ArchetypeID) BMMName() string { return "ARCHETYPE_ID" }

// MarshalXML emits canonical openEHR XML for ArchetypeID. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
func (a *ArchetypeID) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("ARCHETYPE_ID")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeElement(a.Value, xml.StartElement{Name: xml.Name{Local: "value"}}); err != nil {
		return err
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "GENERIC_ID" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (g *GenericID) BMMName() string { return "GENERIC_ID" }

// MarshalXML emits canonical openEHR XML for GenericID. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
func (g *GenericID) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("GENERIC_ID")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeElement(g.Value, xml.StartElement{Name: xml.Name{Local: "value"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(g.Scheme, xml.StartElement{Name: xml.Name{Local: "scheme"}}); err != nil {
		return err
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "HIER_OBJECT_ID" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (h *HierObjectID) BMMName() string { return "HIER_OBJECT_ID" }

// MarshalXML emits canonical openEHR XML for HierObjectID. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
func (h *HierObjectID) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("HIER_OBJECT_ID")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeElement(h.Value, xml.StartElement{Name: xml.Name{Local: "value"}}); err != nil {
		return err
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "ISO_OID" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (i *ISOOID) BMMName() string { return "ISO_OID" }

// MarshalXML emits canonical openEHR XML for ISOOID. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
func (i *ISOOID) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("ISO_OID")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeElement(i.Value, xml.StartElement{Name: xml.Name{Local: "value"}}); err != nil {
		return err
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "INTERNET_ID" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (i *InternetID) BMMName() string { return "INTERNET_ID" }

// MarshalXML emits canonical openEHR XML for InternetID. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
func (i *InternetID) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("INTERNET_ID")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeElement(i.Value, xml.StartElement{Name: xml.Name{Local: "value"}}); err != nil {
		return err
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "LOCATABLE_REF" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (l *LocatableRef) BMMName() string { return "LOCATABLE_REF" }

// MarshalXML emits canonical openEHR XML for LocatableRef. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
func (l *LocatableRef) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("LOCATABLE_REF")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeElement(l.Namespace, xml.StartElement{Name: xml.Name{Local: "namespace"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(l.Type, xml.StartElement{Name: xml.Name{Local: "type"}}); err != nil {
		return err
	}
	if l.Path != nil {
		if err := _e.EncodeElement(*l.Path, xml.StartElement{Name: xml.Name{Local: "path"}}); err != nil {
			return err
		}
	}
	if l.ID != nil {
		if err := canxml.EncodePoly(_e, "id", l.ID); err != nil {
			return err
		}
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "OBJECT_REF" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (o *ObjectRef) BMMName() string { return "OBJECT_REF" }

// MarshalXML emits canonical openEHR XML for ObjectRef. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
func (o *ObjectRef) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("OBJECT_REF")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeElement(o.Namespace, xml.StartElement{Name: xml.Name{Local: "namespace"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(o.Type, xml.StartElement{Name: xml.Name{Local: "type"}}); err != nil {
		return err
	}
	if o.ID != nil {
		if err := canxml.EncodePoly(_e, "id", o.ID); err != nil {
			return err
		}
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "OBJECT_VERSION_ID" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (o *ObjectVersionID) BMMName() string { return "OBJECT_VERSION_ID" }

// MarshalXML emits canonical openEHR XML for ObjectVersionID. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
func (o *ObjectVersionID) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("OBJECT_VERSION_ID")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeElement(o.Value, xml.StartElement{Name: xml.Name{Local: "value"}}); err != nil {
		return err
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "PARTY_REF" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (p *PartyRef) BMMName() string { return "PARTY_REF" }

// MarshalXML emits canonical openEHR XML for PartyRef. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
func (p *PartyRef) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("PARTY_REF")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeElement(p.Namespace, xml.StartElement{Name: xml.Name{Local: "namespace"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(p.Type, xml.StartElement{Name: xml.Name{Local: "type"}}); err != nil {
		return err
	}
	if p.ID != nil {
		if err := canxml.EncodePoly(_e, "id", p.ID); err != nil {
			return err
		}
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "TEMPLATE_ID" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (t *TemplateID) BMMName() string { return "TEMPLATE_ID" }

// MarshalXML emits canonical openEHR XML for TemplateID. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
func (t *TemplateID) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("TEMPLATE_ID")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeElement(t.Value, xml.StartElement{Name: xml.Name{Local: "value"}}); err != nil {
		return err
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "TERMINOLOGY_ID" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (t *TerminologyID) BMMName() string { return "TERMINOLOGY_ID" }

// MarshalXML emits canonical openEHR XML for TerminologyID. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
func (t *TerminologyID) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("TERMINOLOGY_ID")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeElement(t.Value, xml.StartElement{Name: xml.Name{Local: "value"}}); err != nil {
		return err
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "UUID" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (u *Uuid) BMMName() string { return "UUID" }

// MarshalXML emits canonical openEHR XML for Uuid. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
func (u *Uuid) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("UUID")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeElement(u.Value, xml.StartElement{Name: xml.Name{Local: "value"}}); err != nil {
		return err
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "VERSION_TREE_ID" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (v *VersionTreeID) BMMName() string { return "VERSION_TREE_ID" }

// MarshalXML emits canonical openEHR XML for VersionTreeID. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
func (v *VersionTreeID) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("VERSION_TREE_ID")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeElement(v.Value, xml.StartElement{Name: xml.Name{Local: "value"}}); err != nil {
		return err
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}
