// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/json"
	"fmt"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
)

// BMM package: org.openehr.base.base_types.definitions — canonical-JSON UnmarshalJSON companions

type BasicDefinitionsJSONUnmarshaller struct {
	Class string `json:"_type"`
}

// UnmarshalJSON decodes canonical openEHR JSON into BasicDefinitions.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
// A whole-value shape failure goes through typereg.WrapShapeError,
// which keeps the `canjson: <RM_TYPE>:` text and adds
// typereg.ErrInvalidShape (REQ-052). A nil receiver is refused with
// typereg.ErrNilReceiver rather than dereferenced (REQ-025).
func (b *BasicDefinitions) UnmarshalJSON(data []byte) error {
	if b == nil {
		return fmt.Errorf("canjson: BASIC_DEFINITIONS: %w", typereg.ErrNilReceiver)
	}
	var aux BasicDefinitionsJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return typereg.WrapShapeError("BASIC_DEFINITIONS", err)
	}
	if aux.Class != "" && aux.Class != "BASIC_DEFINITIONS" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q, got %q: %w", "BASIC_DEFINITIONS", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	return nil
}

type OpenehrDefinitionsJSONUnmarshaller struct {
	Class string `json:"_type"`
}

// UnmarshalJSON decodes canonical openEHR JSON into OpenehrDefinitions.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
// A whole-value shape failure goes through typereg.WrapShapeError,
// which keeps the `canjson: <RM_TYPE>:` text and adds
// typereg.ErrInvalidShape (REQ-052). A nil receiver is refused with
// typereg.ErrNilReceiver rather than dereferenced (REQ-025).
func (o *OpenehrDefinitions) UnmarshalJSON(data []byte) error {
	if o == nil {
		return fmt.Errorf("canjson: OPENEHR_DEFINITIONS: %w", typereg.ErrNilReceiver)
	}
	var aux OpenehrDefinitionsJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return typereg.WrapShapeError("OPENEHR_DEFINITIONS", err)
	}
	if aux.Class != "" && aux.Class != "OPENEHR_DEFINITIONS" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q, got %q: %w", "OPENEHR_DEFINITIONS", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	return nil
}
