// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/json/jsontext"
	"fmt"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
)

// BMM package: org.openehr.rm.common.archetyped — canonical-JSON UnmarshalJSONFrom companions

// UnmarshalJSONFrom decodes canonical openEHR JSON into Archetyped.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError — keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (a *Archetyped) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if a == nil {
		return fmt.Errorf("canjson: ARCHETYPED: %w", typereg.ErrNilReceiver)
	}
	return typereg.DecodeInto(dec, "ARCHETYPED", &struct {
		Type string `json:"_type"`
		*rawArchetyped
	}{rawArchetyped: (*rawArchetyped)(a)})
}

// UnmarshalJSONFrom decodes canonical openEHR JSON into FeederAudit.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError — keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (f *FeederAudit) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if f == nil {
		return fmt.Errorf("canjson: FEEDER_AUDIT: %w", typereg.ErrNilReceiver)
	}
	return typereg.DecodeInto(dec, "FEEDER_AUDIT", &struct {
		Type string `json:"_type"`
		*rawFeederAudit
	}{rawFeederAudit: (*rawFeederAudit)(f)})
}

// UnmarshalJSONFrom decodes canonical openEHR JSON into FeederAuditDetails.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError — keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (f *FeederAuditDetails) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if f == nil {
		return fmt.Errorf("canjson: FEEDER_AUDIT_DETAILS: %w", typereg.ErrNilReceiver)
	}
	return typereg.DecodeInto(dec, "FEEDER_AUDIT_DETAILS", &struct {
		Type string `json:"_type"`
		*rawFeederAuditDetails
	}{rawFeederAuditDetails: (*rawFeederAuditDetails)(f)})
}

// UnmarshalJSONFrom decodes canonical openEHR JSON into Link.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError — keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (l *Link) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if l == nil {
		return fmt.Errorf("canjson: LINK: %w", typereg.ErrNilReceiver)
	}
	return typereg.DecodeInto(dec, "LINK", &struct {
		Type string `json:"_type"`
		*rawLink
	}{rawLink: (*rawLink)(l)})
}
