// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import "encoding/json"

// BMM package: org.openehr.rm.common.change_control — canonical-JSON MarshalJSON companions

type ContributionJSONMarshaller struct {
	Class string `json:"_type"`
	// UID Unique identifier for this Contribution.
	UID HierObjectID `json:"uid"`
	// Versions Set of references to Versions causing changes to this EHR. Each contribution contains a list of versions, which may include paths pointing to any number of versionable items, i.e. items of types such as `COMPOSITION` and `FOLDER`.
	Versions []ObjectRef `json:"versions"`
	// Audit Audit trail corresponding to the committal of this Contribution.
	Audit AuditDetails `json:"audit"`
}

// MarshalJSON emits canonical openEHR JSON for Contribution with `_type`
// (value "CONTRIBUTION") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (c *Contribution) MarshalJSON() ([]byte, error) {
	return json.Marshal(&ContributionJSONMarshaller{
		Class:    "CONTRIBUTION",
		UID:      c.UID,
		Versions: c.Versions,
		Audit:    c.Audit,
	})
}

type ImportedVersionJSONMarshaller[T any] struct {
	Class string `json:"_type"`
	// Contribution Contribution in which this version was added.
	Contribution ObjectRef `json:"contribution"`
	// Signature OpenPGP digital signature or digest of content committed in this Version.
	Signature *string `json:"signature,omitempty"`
	// CommitAudit Audit trail corresponding to the committal of this version to the `VERSIONED_OBJECT`.
	CommitAudit AuditDetails `json:"commit_audit"`
	// Item The `ORIGINAL_VERSION` object that was imported.
	Item OriginalVersion[any] `json:"item"`
}

// MarshalJSON emits canonical openEHR JSON for ImportedVersion with `_type`
// (value "IMPORTED_VERSION") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (i *ImportedVersion[T]) MarshalJSON() ([]byte, error) {
	return json.Marshal(&ImportedVersionJSONMarshaller[T]{
		Class:        "IMPORTED_VERSION",
		Contribution: i.Contribution,
		Signature:    i.Signature,
		CommitAudit:  i.CommitAudit,
		Item:         i.Item,
	})
}

type OriginalVersionJSONMarshaller[T any] struct {
	Class string `json:"_type"`
	// Contribution Contribution in which this version was added.
	Contribution ObjectRef `json:"contribution"`
	// Signature OpenPGP digital signature or digest of content committed in this Version.
	Signature *string `json:"signature,omitempty"`
	// CommitAudit Audit trail corresponding to the committal of this version to the `VERSIONED_OBJECT`.
	CommitAudit AuditDetails `json:"commit_audit"`
	// UID Stored version of inheritance precursor.
	UID ObjectVersionID `json:"uid"`
	// PrecedingVersionUID Stored version of inheritance precursor.
	PrecedingVersionUID *ObjectVersionID `json:"preceding_version_uid,omitempty"`
	// OtherInputVersionUids Identifiers of other versions whose content was merged into this version, if any.
	OtherInputVersionUids []ObjectVersionID `json:"other_input_version_uids,omitempty"`
	// LifecycleState Lifecycle state of the content item in this version; coded by openEHR vocabulary `version lifecycle state`.
	LifecycleState DVCodedText `json:"lifecycle_state"`
	// Attestations Set of attestations relating to this version.
	Attestations []Attestation `json:"attestations,omitempty"`
	// Data Data content of this Version.
	Data *T `json:"data,omitempty"`
}

// MarshalJSON emits canonical openEHR JSON for OriginalVersion with `_type`
// (value "ORIGINAL_VERSION") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (o *OriginalVersion[T]) MarshalJSON() ([]byte, error) {
	return json.Marshal(&OriginalVersionJSONMarshaller[T]{
		Class:                 "ORIGINAL_VERSION",
		Contribution:          o.Contribution,
		Signature:             o.Signature,
		CommitAudit:           o.CommitAudit,
		UID:                   o.UID,
		PrecedingVersionUID:   o.PrecedingVersionUID,
		OtherInputVersionUids: o.OtherInputVersionUids,
		LifecycleState:        o.LifecycleState,
		Attestations:          o.Attestations,
		Data:                  o.Data,
	})
}

type VersionedObjectJSONMarshaller[T any] struct {
	Class string `json:"_type"`
	// UID Unique identifier of this version container in the form of a UID with no extension. This id will be the same in all instances of the same container in a distributed environment, meaning that it can be understood as the uid of the  virtual version tree.
	UID HierObjectID `json:"uid"`
	// OwnerID Reference to object to which this version container belongs, e.g. the id of the containing EHR or other relevant owning entity.
	OwnerID ObjectRef `json:"owner_id"`
	// TimeCreated Time of initial creation of this versioned object.
	TimeCreated DVDateTime `json:"time_created"`
}

// MarshalJSON emits canonical openEHR JSON for VersionedObject with `_type`
// (value "VERSIONED_OBJECT") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (v *VersionedObject[T]) MarshalJSON() ([]byte, error) {
	return json.Marshal(&VersionedObjectJSONMarshaller[T]{
		Class:       "VERSIONED_OBJECT",
		UID:         v.UID,
		OwnerID:     v.OwnerID,
		TimeCreated: v.TimeCreated,
	})
}
