// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/json"

	"github.com/cadasto/openehr-sdk-go/openehr/internal/jsonpoly"
)

// BMM package: org.openehr.rm.common.directory — canonical-JSON MarshalJSON companions

type FolderJSONMarshaller struct {
	Class string `json:"_type"`
	// Name Runtime name of this fragment, used to build runtime paths. This is the term provided via a clinical application or batch process to name this EHR construct: its retention in the EHR faithfully preserves the original label by which this entry was known to end users.
	Name json.RawMessage `json:"name"`
	// ArchetypeNodeID Design-time archetype identifier of this node taken from its generating archetype; used to build archetype paths. Always in the form of an at-code, e.g.  `at0005`. This value enables a 'standardised' name for this node to be generated, by referring to the generating archetype local terminology.
	//
	// At an archetype root point, the value of this attribute is always the stringified form of the `_archetype_id_` found in the `_archetype_details_` object.
	ArchetypeNodeID string `json:"archetype_node_id"`
	// UID Optional globally unique object identifier for root points of archetyped structures.
	UID json.RawMessage `json:"uid,omitempty"`
	// Links Links to other archetyped structures (data whose root object inherits from `ARCHETYPED`, such as `ENTRY`, `SECTION` and so on). Links may be to structures in other compositions.
	Links []Link `json:"links,omitempty"`
	// ArchetypeDetails Details of archetyping used on this node.
	ArchetypeDetails *Archetyped `json:"archetype_details,omitempty"`
	// FeederAudit Audit trail from non-openEHR system of original commit of information forming the content of this node, or from a conversion gateway which has synthesised this node.
	FeederAudit *FeederAudit `json:"feeder_audit,omitempty"`
	// Items The list of references to other (usually) versioned objects logically in this folder.
	Items json.RawMessage `json:"items,omitempty"`
	// Folders Sub-folders of this `FOLDER`.
	Folders []Folder `json:"folders,omitempty"`
	// Details Archetypable meta-data for `FOLDER`.
	Details json.RawMessage `json:"details,omitempty"`
}

// MarshalJSON emits canonical openEHR JSON for Folder with `_type`
// (value "FOLDER") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (f *Folder) MarshalJSON() ([]byte, error) {
	rawName, err := jsonpoly.Marshal(f.Name)
	if err != nil {
		return nil, err
	}
	rawUID, err := jsonpoly.Marshal(f.UID)
	if err != nil {
		return nil, err
	}
	rawItems, err := jsonpoly.MarshalSlice(f.Items)
	if err != nil {
		return nil, err
	}
	rawDetails, err := jsonpoly.Marshal(f.Details)
	if err != nil {
		return nil, err
	}
	return json.Marshal(&FolderJSONMarshaller{
		Class:            "FOLDER",
		Name:             rawName,
		ArchetypeNodeID:  f.ArchetypeNodeID,
		UID:              rawUID,
		Links:            f.Links,
		ArchetypeDetails: f.ArchetypeDetails,
		FeederAudit:      f.FeederAudit,
		Items:            rawItems,
		Folders:          f.Folders,
		Details:          rawDetails,
	})
}

type VersionedFolderJSONMarshaller struct {
	Class string `json:"_type"`
	// UID Unique identifier of this version container in the form of a UID with no extension. This id will be the same in all instances of the same container in a distributed environment, meaning that it can be understood as the uid of the  virtual version tree.
	UID HierObjectID `json:"uid"`
	// OwnerID Reference to object to which this version container belongs, e.g. the id of the containing EHR or other relevant owning entity.
	OwnerID json.RawMessage `json:"owner_id"`
	// TimeCreated Time of initial creation of this versioned object.
	TimeCreated DVDateTime `json:"time_created"`
}

// MarshalJSON emits canonical openEHR JSON for VersionedFolder with `_type`
// (value "VERSIONED_FOLDER") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (v *VersionedFolder) MarshalJSON() ([]byte, error) {
	rawOwnerID, err := jsonpoly.Marshal(v.OwnerID)
	if err != nil {
		return nil, err
	}
	return json.Marshal(&VersionedFolderJSONMarshaller{
		Class:       "VERSIONED_FOLDER",
		UID:         v.UID,
		OwnerID:     rawOwnerID,
		TimeCreated: v.TimeCreated,
	})
}
