// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/xml"
	"fmt"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
	"github.com/cadasto/openehr-sdk-go/openehr/serialize/canxml"
)

// BMM package: org.openehr.rm.common.change_control — canonical-XML UnmarshalXML companions

// UnmarshalXML decodes canonical openEHR XML into Contribution.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are read from _start.Attr.
func (c *Contribution) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "uid":
				if _err := _dec.DecodeElement(&c.UID, &_t); _err != nil {
					return _err
				}
			case "versions":
				_v, _err := canxml.DecodeAs[ObjectRefLike](_dec, _t)
				if _err != nil {
					return _err
				}
				c.Versions = append(c.Versions, _v)
			case "audit":
				_v, _err := canxml.DecodeAsOrDefault[AuditDetailsLike](_dec, _t, func() any { return new(AuditDetails) })
				if _err != nil {
					return _err
				}
				c.Audit = _v
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// UnmarshalXML decodes canonical openEHR XML into ImportedVersion.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are read from _start.Attr.
func (i *ImportedVersion[T]) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "contribution":
				_v, _err := canxml.DecodeAsOrDefault[ObjectRefLike](_dec, _t, func() any { return new(ObjectRef) })
				if _err != nil {
					return _err
				}
				i.Contribution = _v
			case "signature":
				var _v string
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				i.Signature = &_v
			case "commit_audit":
				_v, _err := canxml.DecodeAsOrDefault[AuditDetailsLike](_dec, _t, func() any { return new(AuditDetails) })
				if _err != nil {
					return _err
				}
				i.CommitAudit = _v
			case "item":
				if _err := _dec.DecodeElement(&i.Item, &_t); _err != nil {
					return _err
				}
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// UnmarshalXML decodes canonical openEHR XML into OriginalVersion.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are read from _start.Attr.
func (o *OriginalVersion[T]) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "contribution":
				_v, _err := canxml.DecodeAsOrDefault[ObjectRefLike](_dec, _t, func() any { return new(ObjectRef) })
				if _err != nil {
					return _err
				}
				o.Contribution = _v
			case "signature":
				var _v string
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				o.Signature = &_v
			case "commit_audit":
				_v, _err := canxml.DecodeAsOrDefault[AuditDetailsLike](_dec, _t, func() any { return new(AuditDetails) })
				if _err != nil {
					return _err
				}
				o.CommitAudit = _v
			case "uid":
				if _err := _dec.DecodeElement(&o.UID, &_t); _err != nil {
					return _err
				}
			case "preceding_version_uid":
				_v := new(ObjectVersionID)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				o.PrecedingVersionUID = _v
			case "other_input_version_uids":
				var _v ObjectVersionID
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				o.OtherInputVersionUids = append(o.OtherInputVersionUids, _v)
			case "lifecycle_state":
				if _err := _dec.DecodeElement(&o.LifecycleState, &_t); _err != nil {
					return _err
				}
			case "attestations":
				var _v Attestation
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				o.Attestations = append(o.Attestations, _v)
			case "data":
				_v := new(T)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				o.Data = _v
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// UnmarshalXML decodes canonical openEHR XML into VersionedObject.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are read from _start.Attr.
func (v *VersionedObject[T]) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "uid":
				if _err := _dec.DecodeElement(&v.UID, &_t); _err != nil {
					return _err
				}
			case "owner_id":
				_v, _err := canxml.DecodeAsOrDefault[ObjectRefLike](_dec, _t, func() any { return new(ObjectRef) })
				if _err != nil {
					return _err
				}
				v.OwnerID = _v
			case "time_created":
				if _err := _dec.DecodeElement(&v.TimeCreated, &_t); _err != nil {
					return _err
				}
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

var (
	_ = typereg.ErrMissingType
	_ = fmt.Sprintf
	_ = canxml.NSDefault
)
