// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/json/jsontext"
	"fmt"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
)

// BMM package org.openehr.rm.common.directory: canonical-JSON UnmarshalJSONFrom companions

// UnmarshalJSONFrom decodes canonical openEHR JSON into Folder.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced. The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError, keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape.
func (f *Folder) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if f == nil {
		return fmt.Errorf("canjson: FOLDER: %w", typereg.ErrNilReceiver)
	}
	w := struct {
		Type string `json:"_type"`
		*rawFolder
	}{rawFolder: (*rawFolder)(f)}
	return typereg.DecodeInto(dec, "FOLDER", &w, &w.Type)
}

// UnmarshalJSONFrom decodes canonical openEHR JSON into VersionedFolder.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced. The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError, keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape.
func (v *VersionedFolder) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if v == nil {
		return fmt.Errorf("canjson: VERSIONED_FOLDER: %w", typereg.ErrNilReceiver)
	}
	var wire jsonWireVersionedFolder
	if err := typereg.DecodeInto(dec, "VERSIONED_FOLDER", &wire, &wire.Class); err != nil {
		return err
	}
	v.UID = wire.UID
	v.OwnerID = wire.OwnerID
	v.TimeCreated = wire.TimeCreated
	return nil
}
