// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/json/jsontext"
	"fmt"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
)

// BMM package org.openehr.rm.common.resource: canonical-JSON UnmarshalJSONFrom companions

// UnmarshalJSONFrom decodes canonical openEHR JSON into ResourceDescription.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced. The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError, keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape.
func (r *ResourceDescription) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if r == nil {
		return fmt.Errorf("canjson: RESOURCE_DESCRIPTION: %w", typereg.ErrNilReceiver)
	}
	w := struct {
		Type string `json:"_type"`
		*rawResourceDescription
	}{rawResourceDescription: (*rawResourceDescription)(r)}
	return typereg.DecodeInto(dec, "RESOURCE_DESCRIPTION", &w, &w.Type)
}

// UnmarshalJSONFrom decodes canonical openEHR JSON into ResourceDescriptionItem.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced. The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError, keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape.
func (r *ResourceDescriptionItem) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if r == nil {
		return fmt.Errorf("canjson: RESOURCE_DESCRIPTION_ITEM: %w", typereg.ErrNilReceiver)
	}
	w := struct {
		Type string `json:"_type"`
		*rawResourceDescriptionItem
	}{rawResourceDescriptionItem: (*rawResourceDescriptionItem)(r)}
	return typereg.DecodeInto(dec, "RESOURCE_DESCRIPTION_ITEM", &w, &w.Type)
}

// UnmarshalJSONFrom decodes canonical openEHR JSON into TranslationDetails.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced. The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError, keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape.
func (t *TranslationDetails) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if t == nil {
		return fmt.Errorf("canjson: TRANSLATION_DETAILS: %w", typereg.ErrNilReceiver)
	}
	w := struct {
		Type string `json:"_type"`
		*rawTranslationDetails
	}{rawTranslationDetails: (*rawTranslationDetails)(t)}
	return typereg.DecodeInto(dec, "TRANSLATION_DETAILS", &w, &w.Type)
}
