// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import "encoding/json"

// BMM package: org.openehr.rm.common.tags — canonical-JSON MarshalJSON companions

type ItemTagJSONMarshaller struct {
	Class string `json:"_type"`
	// Key The tag key. May not be empty or contain leading or trailing whitespace.
	Key string `json:"key"`
	// Value The value. If set, may not be empty.
	Value *string `json:"value,omitempty"`
	// Target Identifier of target, which may be a `VERSIONED_OBJECT<T>` or a `VERSION<T>`.
	Target UIDBasedID `json:"target"`
	// TargetPath Optional archetype (i.e. AQL) or RM path within `_target_`, used to tag a fine-grained element.
	TargetPath *string `json:"target_path,omitempty"`
	// OwnerID Identifier of owner object, such as EHR.
	OwnerID ObjectRef `json:"owner_id"`
}

// MarshalJSON emits canonical openEHR JSON for ItemTag with `_type`
// (value "ITEM_TAG") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (i *ItemTag) MarshalJSON() ([]byte, error) {
	return json.Marshal(&ItemTagJSONMarshaller{
		Class:      "ITEM_TAG",
		Key:        i.Key,
		Value:      i.Value,
		Target:     i.Target,
		TargetPath: i.TargetPath,
		OwnerID:    i.OwnerID,
	})
}
