// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/json"
	"fmt"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
)

// BMM package: org.openehr.rm.common.tags — canonical-JSON UnmarshalJSON companions

type ItemTagJSONUnmarshaller struct {
	Class string `json:"_type"`
	// Key The tag key. May not be empty or contain leading or trailing whitespace.
	Key string `json:"key"`
	// Value The value. If set, may not be empty.
	Value  *string         `json:"value,omitempty"`
	Target json.RawMessage `json:"target"` // polymorphic UIDBasedID
	// TargetPath Optional archetype (i.e. AQL) or RM path within `_target_`, used to tag a fine-grained element.
	TargetPath *string `json:"target_path,omitempty"`
	// OwnerID Identifier of owner object, such as EHR.
	OwnerID ObjectRef `json:"owner_id"`
}

// UnmarshalJSON decodes canonical openEHR JSON into ItemTag.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (i *ItemTag) UnmarshalJSON(data []byte) error {
	var aux ItemTagJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: ITEM_TAG: %w", err)
	}
	if aux.Class != "" && aux.Class != "ITEM_TAG" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q, got %q: %w", "ITEM_TAG", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	i.Key = aux.Key
	i.Value = aux.Value
	if len(aux.Target) > 0 && string(aux.Target) != "null" {
		dv, err := typereg.DecodeAs[UIDBasedID](aux.Target)
		if err != nil {
			return &typereg.DecodeError{Path: "/target", Inner: err}
		}
		i.Target = dv
	}
	i.TargetPath = aux.TargetPath
	i.OwnerID = aux.OwnerID
	return nil
}
