// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import "encoding/json"

// BMM package: org.openehr.rm.composition — canonical-JSON MarshalJSON companions

type CompositionJSONMarshaller struct {
	Class string `json:"_type"`
	// Name Runtime name of this fragment, used to build runtime paths. This is the term provided via a clinical application or batch process to name this EHR construct: its retention in the EHR faithfully preserves the original label by which this entry was known to end users.
	Name DataValueText `json:"name"`
	// ArchetypeNodeID Design-time archetype identifier of this node taken from its generating archetype; used to build archetype paths. Always in the form of an at-code, e.g.  `at0005`. This value enables a 'standardised' name for this node to be generated, by referring to the generating archetype local terminology.
	//
	// At an archetype root point, the value of this attribute is always the stringified form of the `_archetype_id_` found in the `_archetype_details_` object.
	ArchetypeNodeID string `json:"archetype_node_id"`
	// UID Optional globally unique object identifier for root points of archetyped structures.
	UID UIDBasedID `json:"uid,omitempty"`
	// Links Links to other archetyped structures (data whose root object inherits from `ARCHETYPED`, such as `ENTRY`, `SECTION` and so on). Links may be to structures in other compositions.
	Links []Link `json:"links,omitempty"`
	// ArchetypeDetails Details of archetyping used on this node.
	ArchetypeDetails *Archetyped `json:"archetype_details,omitempty"`
	// FeederAudit Audit trail from non-openEHR system of original commit of information forming the content of this node, or from a conversion gateway which has synthesised this node.
	FeederAudit *FeederAudit `json:"feeder_audit,omitempty"`
	// Language Mandatory indicator of the localised language in which this Composition is written. Coded from openEHR Code Set  `languages`. The language of an Entry if different from the Composition is indicated in `ENTRY._language_`.
	Language CodePhrase `json:"language"`
	// Territory Name of territory in which this Composition was written. Coded from openEHR  countries  code set, which is an expression of the ISO 3166 standard.
	Territory CodePhrase `json:"territory"`
	// Category Temporal category of this Composition, i.e.
	//
	// * `431|persistent|` - of potential life-time validity;
	// * `451|episodic|` - valid over the life of a care episode;
	// * `433|event|` - valid at the time of recording (long-term validity requires subsequent clinical assessment).
	//
	// or any other code defined in the openEHR terminology group 'category'.
	Category DVCodedText `json:"category"`
	// Context The clinical session context of this Composition, i.e. the contextual attributes of the clinical session.
	Context *EventContext `json:"context,omitempty"`
	// Composer The person primarily responsible for the content of the Composition (but not necessarily its committal into the EHR system). This is the identifier which should appear on the screen. It may or may not be the person who entered the data. When it is the patient, the special self  instance of `PARTY_PROXY` will be used.
	Composer PartyProxy `json:"composer"`
	// Content The content of this Composition.
	Content []ContentItem `json:"content,omitempty"`
}

// MarshalJSON emits canonical openEHR JSON for Composition with `_type`
// (value "COMPOSITION") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (c *Composition) MarshalJSON() ([]byte, error) {
	return json.Marshal(&CompositionJSONMarshaller{
		Class:            "COMPOSITION",
		Name:             c.Name,
		ArchetypeNodeID:  c.ArchetypeNodeID,
		UID:              c.UID,
		Links:            c.Links,
		ArchetypeDetails: c.ArchetypeDetails,
		FeederAudit:      c.FeederAudit,
		Language:         c.Language,
		Territory:        c.Territory,
		Category:         c.Category,
		Context:          c.Context,
		Composer:         c.Composer,
		Content:          c.Content,
	})
}

type EventContextJSONMarshaller struct {
	Class string `json:"_type"`
	// StartTime Start time of the clinical session or other kind of event during which a provider performs a service of any kind for the patient.
	StartTime DVDateTime `json:"start_time"`
	// EndTime Optional end time of the clinical session.
	EndTime *DVDateTime `json:"end_time,omitempty"`
	// Location The actual location where the session occurred, e.g. 'microbiology lab 2', 'home', 'ward A3'  and so on.
	Location *string `json:"location,omitempty"`
	// Setting The setting in which the clinical session took place. Coded using the openEHR Terminology,  setting  group.
	Setting DVCodedText `json:"setting"`
	// OtherContext Other optional context which will be archetyped.
	OtherContext ItemStructure `json:"other_context,omitempty"`
	// HealthCareFacility The health care facility under whose care the event took place. This is the most specific workgroup or delivery unit within a care delivery enterprise that has an official identifier in the health system, and can be used to ensure medico-legal accountability.
	HealthCareFacility *PartyIdentified `json:"health_care_facility,omitempty"`
	// Participations Parties involved in the healthcare event. These would normally include the physician(s) and often the patient (but not the latter if the clinical session is a pathology test for example).
	Participations []Participation `json:"participations,omitempty"`
}

// MarshalJSON emits canonical openEHR JSON for EventContext with `_type`
// (value "EVENT_CONTEXT") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (e *EventContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(&EventContextJSONMarshaller{
		Class:              "EVENT_CONTEXT",
		StartTime:          e.StartTime,
		EndTime:            e.EndTime,
		Location:           e.Location,
		Setting:            e.Setting,
		OtherContext:       e.OtherContext,
		HealthCareFacility: e.HealthCareFacility,
		Participations:     e.Participations,
	})
}
