// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/json/jsontext"
	json "encoding/json/v2"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
)

// BMM package org.openehr.rm.composition: canonical-JSON MarshalJSONTo companions

// rawComposition is the method-free canonical-JSON alias for Composition. The alias
// drops the codec methods so marshalling the anonymous wrapper below
// does not recurse; the class embeds no marshaler-bearing concrete
// ancestor, so nothing is promoted (ADR 0022).
type rawComposition Composition

// MarshalJSONTo emits canonical openEHR JSON for Composition with `_type`
// (value "COMPOSITION") as the leading member. Field order otherwise follows the
// struct declaration; json.Deterministic sorts any Hash keys and the
// FormatNil* options keep a mandatory nil container's `null` spelling
// (REQ-052, Q6). The receiver is a value so a concrete instance sitting
// in a polymorphic interface slot by value, the shape the like-interface
// accessors admit, still carries its `_type` (REQ-052 substitution).
func (c Composition) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, &struct {
		Type string `json:"_type"`
		*rawComposition
	}{"COMPOSITION", (*rawComposition)(&c)}, typereg.MarshalOptions(enc))
}

// rawEventContext is the method-free canonical-JSON alias for EventContext. The alias
// drops the codec methods so marshalling the anonymous wrapper below
// does not recurse; the class embeds no marshaler-bearing concrete
// ancestor, so nothing is promoted (ADR 0022).
type rawEventContext EventContext

// MarshalJSONTo emits canonical openEHR JSON for EventContext with `_type`
// (value "EVENT_CONTEXT") as the leading member. Field order otherwise follows the
// struct declaration; json.Deterministic sorts any Hash keys and the
// FormatNil* options keep a mandatory nil container's `null` spelling
// (REQ-052, Q6). The receiver is a value so a concrete instance sitting
// in a polymorphic interface slot by value, the shape the like-interface
// accessors admit, still carries its `_type` (REQ-052 substitution).
func (e EventContext) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, &struct {
		Type string `json:"_type"`
		*rawEventContext
	}{"EVENT_CONTEXT", (*rawEventContext)(&e)}, typereg.MarshalOptions(enc))
}
