// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/xml"

	"github.com/cadasto/openehr-sdk-go/openehr/serialize/canxml"
)

// BMM package: org.openehr.rm.composition — canonical-XML MarshalXML companions

// BMMName returns "COMPOSITION" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (c *Composition) BMMName() string { return "COMPOSITION" }

// MarshalXML emits canonical openEHR XML for Composition. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are appended to start.Attr before
// the start token is written.
func (c *Composition) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("COMPOSITION")}
	}
	_start.Attr = append(_start.Attr, xml.Attr{Name: xml.Name{Local: "archetype_node_id"}, Value: c.ArchetypeNodeID})
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeElement(&c.Name, xml.StartElement{Name: xml.Name{Local: "name"}}); err != nil {
		return err
	}
	if c.UID != nil {
		if err := canxml.EncodePoly(_e, "uid", c.UID); err != nil {
			return err
		}
	}
	for _idx := range c.Links {
		if err := _e.EncodeElement(&c.Links[_idx], xml.StartElement{Name: xml.Name{Local: "links"}}); err != nil {
			return err
		}
	}
	if c.ArchetypeDetails != nil {
		if err := _e.EncodeElement(c.ArchetypeDetails, xml.StartElement{Name: xml.Name{Local: "archetype_details"}}); err != nil {
			return err
		}
	}
	if c.FeederAudit != nil {
		if err := _e.EncodeElement(c.FeederAudit, xml.StartElement{Name: xml.Name{Local: "feeder_audit"}}); err != nil {
			return err
		}
	}
	if err := _e.EncodeElement(&c.Language, xml.StartElement{Name: xml.Name{Local: "language"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(&c.Territory, xml.StartElement{Name: xml.Name{Local: "territory"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(&c.Category, xml.StartElement{Name: xml.Name{Local: "category"}}); err != nil {
		return err
	}
	if c.Context != nil {
		if err := _e.EncodeElement(c.Context, xml.StartElement{Name: xml.Name{Local: "context"}}); err != nil {
			return err
		}
	}
	if c.Composer != nil {
		if err := canxml.EncodePoly(_e, "composer", c.Composer); err != nil {
			return err
		}
	}
	for _, _item := range c.Content {
		if _item == nil {
			continue
		}
		if err := canxml.EncodePoly(_e, "content", _item); err != nil {
			return err
		}
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "EVENT_CONTEXT" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (e *EventContext) BMMName() string { return "EVENT_CONTEXT" }

// MarshalXML emits canonical openEHR XML for EventContext. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are appended to start.Attr before
// the start token is written.
func (e *EventContext) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("EVENT_CONTEXT")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeElement(&e.StartTime, xml.StartElement{Name: xml.Name{Local: "start_time"}}); err != nil {
		return err
	}
	if e.EndTime != nil {
		if err := _e.EncodeElement(e.EndTime, xml.StartElement{Name: xml.Name{Local: "end_time"}}); err != nil {
			return err
		}
	}
	if e.Location != nil {
		if err := _e.EncodeElement(*e.Location, xml.StartElement{Name: xml.Name{Local: "location"}}); err != nil {
			return err
		}
	}
	if err := _e.EncodeElement(&e.Setting, xml.StartElement{Name: xml.Name{Local: "setting"}}); err != nil {
		return err
	}
	if e.OtherContext != nil {
		if err := canxml.EncodePoly(_e, "other_context", e.OtherContext); err != nil {
			return err
		}
	}
	if e.HealthCareFacility != nil {
		if err := _e.EncodeElement(e.HealthCareFacility, xml.StartElement{Name: xml.Name{Local: "health_care_facility"}}); err != nil {
			return err
		}
	}
	for _idx := range e.Participations {
		if err := _e.EncodeElement(&e.Participations[_idx], xml.StartElement{Name: xml.Name{Local: "participations"}}); err != nil {
			return err
		}
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}
