// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/json/jsontext"
	"fmt"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
)

// BMM package org.openehr.rm.data_types.quantity.date_time: canonical-JSON UnmarshalJSONFrom companions

// UnmarshalJSONFrom decodes canonical openEHR JSON into DVDate.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError, keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (d *DVDate) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if d == nil {
		return fmt.Errorf("canjson: DV_DATE: %w", typereg.ErrNilReceiver)
	}
	w := struct {
		Type string `json:"_type"`
		*rawDVDate
	}{rawDVDate: (*rawDVDate)(d)}
	return typereg.DecodeInto(dec, "DV_DATE", &w, &w.Type)
}

// UnmarshalJSONFrom decodes canonical openEHR JSON into DVDateTime.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError, keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (d *DVDateTime) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if d == nil {
		return fmt.Errorf("canjson: DV_DATE_TIME: %w", typereg.ErrNilReceiver)
	}
	w := struct {
		Type string `json:"_type"`
		*rawDVDateTime
	}{rawDVDateTime: (*rawDVDateTime)(d)}
	return typereg.DecodeInto(dec, "DV_DATE_TIME", &w, &w.Type)
}

// UnmarshalJSONFrom decodes canonical openEHR JSON into DVDuration.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError, keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (d *DVDuration) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if d == nil {
		return fmt.Errorf("canjson: DV_DURATION: %w", typereg.ErrNilReceiver)
	}
	w := struct {
		Type string `json:"_type"`
		*rawDVDuration
	}{rawDVDuration: (*rawDVDuration)(d)}
	return typereg.DecodeInto(dec, "DV_DURATION", &w, &w.Type)
}

// UnmarshalJSONFrom decodes canonical openEHR JSON into DVTime.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError, keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (d *DVTime) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if d == nil {
		return fmt.Errorf("canjson: DV_TIME: %w", typereg.ErrNilReceiver)
	}
	w := struct {
		Type string `json:"_type"`
		*rawDVTime
	}{rawDVTime: (*rawDVTime)(d)}
	return typereg.DecodeInto(dec, "DV_TIME", &w, &w.Type)
}
