// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/json"
	"fmt"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
)

// BMM package: org.openehr.rm.data_types.time_specification — canonical-JSON UnmarshalJSON companions

type DVGeneralTimeSpecificationJSONUnmarshaller struct {
	Class string `json:"_type"`
	// Value The specification, in the HL7v3 syntax for `PIVL` or `EIVL` types.
	Value DVParsable `json:"value"`
}

// UnmarshalJSON decodes canonical openEHR JSON into DVGeneralTimeSpecification.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (d *DVGeneralTimeSpecification) UnmarshalJSON(data []byte) error {
	var aux DVGeneralTimeSpecificationJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: DV_GENERAL_TIME_SPECIFICATION: %w", err)
	}
	if aux.Class != "" && aux.Class != "DV_GENERAL_TIME_SPECIFICATION" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "DV_GENERAL_TIME_SPECIFICATION", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	d.Value = aux.Value
	return nil
}

type DVPeriodicTimeSpecificationJSONUnmarshaller struct {
	Class string `json:"_type"`
	// Value The specification, in the HL7v3 syntax for `PIVL` or `EIVL` types.
	Value DVParsable `json:"value"`
}

// UnmarshalJSON decodes canonical openEHR JSON into DVPeriodicTimeSpecification.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (d *DVPeriodicTimeSpecification) UnmarshalJSON(data []byte) error {
	var aux DVPeriodicTimeSpecificationJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: DV_PERIODIC_TIME_SPECIFICATION: %w", err)
	}
	if aux.Class != "" && aux.Class != "DV_PERIODIC_TIME_SPECIFICATION" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "DV_PERIODIC_TIME_SPECIFICATION", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	d.Value = aux.Value
	return nil
}
