// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

// BMM package: org.openehr.rm.data_types.quantity.date_time

// DVDate Represents an absolute point in time, as measured on the Gregorian calendar, and specified only to the day. Semantics defined by ISO 8601. Used for recording dates in real world time. The partial form is used for approximate birth dates, dates of death, etc.
type DVDate struct {
	// Accuracy Time accuracy, expressed as a duration.
	Accuracy *DVDuration `json:"accuracy,omitempty"`
	// MagnitudeStatus Optional status of magnitude with values:
	//
	// * `"="`   :   magnitude is a point value
	// * `"<"`   :   value is < magnitude
	// * `">"`   :   value is > magnitude
	// * `"<="` : value is <= magnitude
	// * `">="` : value is >= magnitude
	// * `"~"`   :   value is approximately magnitude
	//
	// If not present, assumed meaning is  `"="` .
	MagnitudeStatus *string `json:"magnitude_status,omitempty"`
	// NormalRange Optional normal range.
	NormalRange *DVInterval[DVOrdered] `json:"normal_range,omitempty"`
	// NormalStatus Optional normal status indicator of value with respect to normal range for this value. Often included by lab, even if the normal range itself is not included. Coded by ordinals in series HHH, HH, H, (nothing), L, LL, LLL; see openEHR terminology group  `normal_status`.
	NormalStatus *CodePhrase `json:"normal_status,omitempty"`
	// OtherReferenceRanges Optional tagged other reference ranges for this value in its particular measurement context.
	OtherReferenceRanges []ReferenceRange[DVOrdered] `json:"other_reference_ranges,omitempty"`
	// Value ISO8601 date string.
	Value string `json:"value"`
}

// Add Addition of a Duration to this Date.
//
// Aliases: + (Go does not support operator overloading)
func (d *DVDate) Add(aDiff DVDuration) DVDate {
	panic("not implemented: DV_DATE.add — implement in a non-generated file")
}

// Diff Difference between this Date and `_other_`.
//
// Aliases: - (Go does not support operator overloading)
func (d *DVDate) Diff(other DVDate) DVDuration {
	panic("not implemented: DV_DATE.diff — implement in a non-generated file")
}

// IsEqual Return True if this `DV_QUANTIFIED` is considered equal to `_other_`.
func (d *DVDate) IsEqual(other DVQuantified) bool {
	panic("not implemented: DV_DATE.is_equal — implement in a non-generated file")
}

// IsStrictlyComparableTo True, for any two Dates.
func (d *DVDate) IsStrictlyComparableTo(other DVDate) bool {
	panic("not implemented: DV_DATE.is_strictly_comparable_to — implement in a non-generated file")
}

// LessThan True if this date object is less than `_other_`, based on comparison of `_magnitude()_`.
//
// Pre: is_strictly_comparable_to (other)
// Post: Result = magnitude < other.magnitude
//
// Aliases: < (Go does not support operator overloading)
func (d *DVDate) LessThan(other DVDate) bool {
	panic("not implemented: DV_DATE.less_than — implement in a non-generated file")
}

// Magnitude Numeric value of the date as days since the calendar origin date `0001-01-01`.
func (d *DVDate) Magnitude() Integer {
	panic("not implemented: DV_DATE.magnitude — implement in a non-generated file")
}

// Subtract Subtract a Duration from this Date.
//
// Aliases: - (Go does not support operator overloading)
func (d *DVDate) Subtract(aDiff DVDuration) DVDate {
	panic("not implemented: DV_DATE.subtract — implement in a non-generated file")
}

// DVDateTime Represents an absolute point in time, specified to the second. Semantics defined by ISO 8601.
//
// Used for recording a precise point in real world time, and for approximate time stamps, e.g. the origin of a `HISTORY` in an `OBSERVATION` which is only partially known.
type DVDateTime struct {
	// Accuracy Time accuracy, expressed as a duration.
	Accuracy *DVDuration `json:"accuracy,omitempty"`
	// MagnitudeStatus Optional status of magnitude with values:
	//
	// * `"="`   :   magnitude is a point value
	// * `"<"`   :   value is < magnitude
	// * `">"`   :   value is > magnitude
	// * `"<="` : value is <= magnitude
	// * `">="` : value is >= magnitude
	// * `"~"`   :   value is approximately magnitude
	//
	// If not present, assumed meaning is  `"="` .
	MagnitudeStatus *string `json:"magnitude_status,omitempty"`
	// NormalRange Optional normal range.
	NormalRange *DVInterval[DVOrdered] `json:"normal_range,omitempty"`
	// NormalStatus Optional normal status indicator of value with respect to normal range for this value. Often included by lab, even if the normal range itself is not included. Coded by ordinals in series HHH, HH, H, (nothing), L, LL, LLL; see openEHR terminology group  `normal_status`.
	NormalStatus *CodePhrase `json:"normal_status,omitempty"`
	// OtherReferenceRanges Optional tagged other reference ranges for this value in its particular measurement context.
	OtherReferenceRanges []ReferenceRange[DVOrdered] `json:"other_reference_ranges,omitempty"`
	// Value ISO8601 date/time string.
	Value string `json:"value"`
}

// Add Addition of a Duration to this Date/time.
//
// Aliases: + (Go does not support operator overloading)
func (d *DVDateTime) Add(aDiff DVDuration) DVDateTime {
	panic("not implemented: DV_DATE_TIME.add — implement in a non-generated file")
}

// Diff Difference between this Date/time and `_other_`.
//
// Aliases: - (Go does not support operator overloading)
func (d *DVDateTime) Diff(other DVDateTime) DVDuration {
	panic("not implemented: DV_DATE_TIME.diff — implement in a non-generated file")
}

// IsStrictlyComparableTo True, for any two Date/times.
func (d *DVDateTime) IsStrictlyComparableTo(other DVDateTime) bool {
	panic("not implemented: DV_DATE_TIME.is_strictly_comparable_to — implement in a non-generated file")
}

// LessThan True if this date-time object is less than `_other_`, based on comparison of `_magnitude()_`.
//
// Pre: is_strictly_comparable_to (other)
// Post: Result = magnitude < other.magnitude
//
// Aliases: < (Go does not support operator overloading)
func (d *DVDateTime) LessThan(other DVDateTime) bool {
	panic("not implemented: DV_DATE_TIME.less_than — implement in a non-generated file")
}

// Magnitude Numeric value of the date/time as seconds since the calendar origin date/time `0001-01-01T00:00:00Z`.
func (d *DVDateTime) Magnitude() float64 {
	panic("not implemented: DV_DATE_TIME.magnitude — implement in a non-generated file")
}

// Subtract Subtract a Duration from this Date/time.
//
// Aliases: - (Go does not support operator overloading)
func (d *DVDateTime) Subtract(aDiff DVDuration) DVDateTime {
	panic("not implemented: DV_DATE_TIME.subtract — implement in a non-generated file")
}

// DVDuration Represents a period of time with respect to a notional point in time, which is not specified. A sign may be used to indicate the duration is  backwards  in time rather than forwards.
//
// NOTE: two deviations from ISO 8601 are supported, the first, to allow a negative sign, and the second allowing the 'W' designator to be mixed with other designators. See time types section in the Foundation Types model.
//
// Used for recording the duration of something in the real world, particularly when there is a need a) to represent the duration in customary format, i.e. days, hours, minutes etc, and b) if it will be used in computational operations with date/time quantities, i.e. additions, subtractions etc.
//
// Misuse: Durations cannot be used to represent points in time, or intervals of time.
type DVDuration struct {
	// Accuracy Accuracy of measurement, expressed either as a half-range percent value (`_accuracy_is_percent_` = `True`) or a half-range quantity. A value of `0` means that accuracy is 100%, i.e. no error.
	//
	// A value of `_unknown_accuracy_value_` means that accuracy was not recorded.
	Accuracy *Real `json:"accuracy,omitempty"`
	// AccuracyIsPercent If `True`, indicates that when this object was created, `_accuracy_` was recorded as a percent value; if `False`, as an absolute quantity value.
	AccuracyIsPercent *bool `json:"accuracy_is_percent,omitempty"`
	// MagnitudeStatus Optional status of magnitude with values:
	//
	// * `"="`   :   magnitude is a point value
	// * `"<"`   :   value is < magnitude
	// * `">"`   :   value is > magnitude
	// * `"<="` : value is <= magnitude
	// * `">="` : value is >= magnitude
	// * `"~"`   :   value is approximately magnitude
	//
	// If not present, assumed meaning is  `"="` .
	MagnitudeStatus *string `json:"magnitude_status,omitempty"`
	// NormalRange Optional normal range.
	NormalRange *DVInterval[DVOrdered] `json:"normal_range,omitempty"`
	// NormalStatus Optional normal status indicator of value with respect to normal range for this value. Often included by lab, even if the normal range itself is not included. Coded by ordinals in series HHH, HH, H, (nothing), L, LL, LLL; see openEHR terminology group  `normal_status`.
	NormalStatus *CodePhrase `json:"normal_status,omitempty"`
	// OtherReferenceRanges Optional tagged other reference ranges for this value in its particular measurement context.
	OtherReferenceRanges []ReferenceRange[DVOrdered] `json:"other_reference_ranges,omitempty"`
	// Value ISO8601 duration string, including described deviations to support negative values and weeks.
	Value string `json:"value"`
}

// Add Sum of this Duration and `_other_`.
//
// Aliases: + (Go does not support operator overloading)
func (d *DVDuration) Add(other DVDuration) DVDuration {
	panic("not implemented: DV_DURATION.add — implement in a non-generated file")
}

// IsStrictlyComparableTo True, for any two Durations.
func (d *DVDuration) IsStrictlyComparableTo(other DVDuration) bool {
	panic("not implemented: DV_DURATION.is_strictly_comparable_to — implement in a non-generated file")
}

// LessThan True if this duration object is less than `_other_`, based on comparison of `_magnitude()_`.
//
// Pre: is_strictly_comparable_to (other)
// Post: Result = magnitude < other.magnitude
//
// Aliases: < (Go does not support operator overloading)
func (d *DVDuration) LessThan(other DVDuration) bool {
	panic("not implemented: DV_DURATION.less_than — implement in a non-generated file")
}

// Magnitude Numeric value of the duration as a number of seconds. Computed using the method `_to_seconds()_` inherited from `Iso8601_duration`.
func (d *DVDuration) Magnitude() float64 {
	panic("not implemented: DV_DURATION.magnitude — implement in a non-generated file")
}

// Multiply Product of this Duration and `_factor_`.
//
// Aliases: &#42; (Go does not support operator overloading)
func (d *DVDuration) Multiply(factor Real) DVDuration {
	panic("not implemented: DV_DURATION.multiply — implement in a non-generated file")
}

// Negative Negated version of current duration.
//
// Assuming the current duration is positive, the negated version represents a time prior to some origin point, or a negative age (e.g. so-called 'adjusted age' of premature infant).
//
// Aliases: - (Go does not support operator overloading)
func (d *DVDuration) Negative() DVDuration {
	panic("not implemented: DV_DURATION.negative — implement in a non-generated file")
}

// Subtract Difference of this Duration and `_other_`.
//
// Aliases: - (Go does not support operator overloading)
func (d *DVDuration) Subtract(other DVDuration) DVDuration {
	panic("not implemented: DV_DURATION.subtract — implement in a non-generated file")
}

// DVTemporal Specialised temporal variant of `DV_ABSOLUTE_QUANTITY` whose diff type is `DV_DURATION`.
type DVTemporal interface {
	isDVTemporal()
}

func (DVDate) isDVTemporal() {}

func (DVDateTime) isDVTemporal() {}

func (DVTime) isDVTemporal() {}

// DVTime Represents an absolute point in time from an origin usually interpreted as meaning the start of the current day, specified to a fraction of a second. Semantics defined by ISO 8601.
//
// Used for recording real world times, rather than scientifically measured fine amounts of time. The partial form is used for approximate times of events and substance administrations.
type DVTime struct {
	// Accuracy Time accuracy, expressed as a duration.
	Accuracy *DVDuration `json:"accuracy,omitempty"`
	// MagnitudeStatus Optional status of magnitude with values:
	//
	// * `"="`   :   magnitude is a point value
	// * `"<"`   :   value is < magnitude
	// * `">"`   :   value is > magnitude
	// * `"<="` : value is <= magnitude
	// * `">="` : value is >= magnitude
	// * `"~"`   :   value is approximately magnitude
	//
	// If not present, assumed meaning is  `"="` .
	MagnitudeStatus *string `json:"magnitude_status,omitempty"`
	// NormalRange Optional normal range.
	NormalRange *DVInterval[DVOrdered] `json:"normal_range,omitempty"`
	// NormalStatus Optional normal status indicator of value with respect to normal range for this value. Often included by lab, even if the normal range itself is not included. Coded by ordinals in series HHH, HH, H, (nothing), L, LL, LLL; see openEHR terminology group  `normal_status`.
	NormalStatus *CodePhrase `json:"normal_status,omitempty"`
	// OtherReferenceRanges Optional tagged other reference ranges for this value in its particular measurement context.
	OtherReferenceRanges []ReferenceRange[DVOrdered] `json:"other_reference_ranges,omitempty"`
	// Value ISO8601 time string
	Value string `json:"value"`
}

// Add Addition of a Duration to this Time.
//
// Aliases: + (Go does not support operator overloading)
func (d *DVTime) Add(aDiff DVDuration) DVTime {
	panic("not implemented: DV_TIME.add — implement in a non-generated file")
}

// Diff Difference between this Time and `_other_`.
//
// Aliases: - (Go does not support operator overloading)
func (d *DVTime) Diff(other DVTime) DVDuration {
	panic("not implemented: DV_TIME.diff — implement in a non-generated file")
}

// IsStrictlyComparableTo True, for any two Times.
func (d *DVTime) IsStrictlyComparableTo(other DVTime) bool {
	panic("not implemented: DV_TIME.is_strictly_comparable_to — implement in a non-generated file")
}

// LessThan True if this time object is less than `_other_`, based on comparison of `_magnitude()_`.
//
// Pre: is_strictly_comparable_to (other)
// Post: Result = magnitude < other.magnitude
//
// Aliases: < (Go does not support operator overloading)
func (d *DVTime) LessThan(other DVTime) bool {
	panic("not implemented: DV_TIME.less_than — implement in a non-generated file")
}

// Magnitude Numeric value of the time as seconds since the start of day, i.e. `00:00:00`.
func (d *DVTime) Magnitude() Real {
	panic("not implemented: DV_TIME.magnitude — implement in a non-generated file")
}

// Subtract Subtract a Duration from this Time.
//
// Aliases: - (Go does not support operator overloading)
func (d *DVTime) Subtract(aDiff DVDuration) DVTime {
	panic("not implemented: DV_TIME.subtract — implement in a non-generated file")
}
