// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/json/jsontext"
	json "encoding/json/v2"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
)

// BMM package: org.openehr.rm.data_types.quantity — canonical-JSON MarshalJSONTo companions

// rawDVCount is the method-free canonical-JSON alias for DVCount. The alias
// drops the codec methods so marshalling the anonymous wrapper below
// does not recurse; the class embeds no marshaler-bearing concrete
// ancestor, so nothing is promoted (ADR 0022).
type rawDVCount DVCount

// MarshalJSONTo emits canonical openEHR JSON for DVCount with `_type`
// (value "DV_COUNT") as the leading member. Field order otherwise follows the
// struct declaration; json.Deterministic sorts any Hash keys and the
// FormatNil* options keep a mandatory nil container's `null` spelling
// (REQ-052, Q6). The receiver is a value so a concrete instance sitting
// in a polymorphic interface slot by value — the shape the like-interface
// accessors admit — still carries its `_type` (REQ-052 substitution).
func (d DVCount) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, &struct {
		Type string `json:"_type"`
		*rawDVCount
	}{"DV_COUNT", (*rawDVCount)(&d)}, typereg.MarshalOptions(enc))
}

// rawDVInterval is the method-free canonical-JSON alias for DVInterval. The alias
// drops the codec methods so marshalling the anonymous wrapper below
// does not recurse; the class embeds no marshaler-bearing concrete
// ancestor, so nothing is promoted (ADR 0022).
type rawDVInterval[T DVOrdered] DVInterval[T]

// MarshalJSONTo emits canonical openEHR JSON for DVInterval with `_type`
// (value "DV_INTERVAL") as the leading member. Field order otherwise follows the
// struct declaration; json.Deterministic sorts any Hash keys and the
// FormatNil* options keep a mandatory nil container's `null` spelling
// (REQ-052, Q6). The receiver is a value so a concrete instance sitting
// in a polymorphic interface slot by value — the shape the like-interface
// accessors admit — still carries its `_type` (REQ-052 substitution).
func (d DVInterval[T]) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, &struct {
		Type string `json:"_type"`
		*rawDVInterval[T]
	}{"DV_INTERVAL", (*rawDVInterval[T])(&d)}, typereg.MarshalOptions(enc))
}

// rawDVOrdinal is the method-free canonical-JSON alias for DVOrdinal. The alias
// drops the codec methods so marshalling the anonymous wrapper below
// does not recurse; the class embeds no marshaler-bearing concrete
// ancestor, so nothing is promoted (ADR 0022).
type rawDVOrdinal DVOrdinal

// MarshalJSONTo emits canonical openEHR JSON for DVOrdinal with `_type`
// (value "DV_ORDINAL") as the leading member. Field order otherwise follows the
// struct declaration; json.Deterministic sorts any Hash keys and the
// FormatNil* options keep a mandatory nil container's `null` spelling
// (REQ-052, Q6). The receiver is a value so a concrete instance sitting
// in a polymorphic interface slot by value — the shape the like-interface
// accessors admit — still carries its `_type` (REQ-052 substitution).
func (d DVOrdinal) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, &struct {
		Type string `json:"_type"`
		*rawDVOrdinal
	}{"DV_ORDINAL", (*rawDVOrdinal)(&d)}, typereg.MarshalOptions(enc))
}

// rawDVProportion is the method-free canonical-JSON alias for DVProportion. The alias
// drops the codec methods so marshalling the anonymous wrapper below
// does not recurse; the class embeds no marshaler-bearing concrete
// ancestor, so nothing is promoted (ADR 0022).
type rawDVProportion DVProportion

// MarshalJSONTo emits canonical openEHR JSON for DVProportion with `_type`
// (value "DV_PROPORTION") as the leading member. Field order otherwise follows the
// struct declaration; json.Deterministic sorts any Hash keys and the
// FormatNil* options keep a mandatory nil container's `null` spelling
// (REQ-052, Q6). The receiver is a value so a concrete instance sitting
// in a polymorphic interface slot by value — the shape the like-interface
// accessors admit — still carries its `_type` (REQ-052 substitution).
func (d DVProportion) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, &struct {
		Type string `json:"_type"`
		*rawDVProportion
	}{"DV_PROPORTION", (*rawDVProportion)(&d)}, typereg.MarshalOptions(enc))
}

// rawDVQuantity is the method-free canonical-JSON alias for DVQuantity. The alias
// drops the codec methods so marshalling the anonymous wrapper below
// does not recurse; the class embeds no marshaler-bearing concrete
// ancestor, so nothing is promoted (ADR 0022).
type rawDVQuantity DVQuantity

// MarshalJSONTo emits canonical openEHR JSON for DVQuantity with `_type`
// (value "DV_QUANTITY") as the leading member. Field order otherwise follows the
// struct declaration; json.Deterministic sorts any Hash keys and the
// FormatNil* options keep a mandatory nil container's `null` spelling
// (REQ-052, Q6). The receiver is a value so a concrete instance sitting
// in a polymorphic interface slot by value — the shape the like-interface
// accessors admit — still carries its `_type` (REQ-052 substitution).
func (d DVQuantity) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, &struct {
		Type string `json:"_type"`
		*rawDVQuantity
	}{"DV_QUANTITY", (*rawDVQuantity)(&d)}, typereg.MarshalOptions(enc))
}

// rawDVScale is the method-free canonical-JSON alias for DVScale. The alias
// drops the codec methods so marshalling the anonymous wrapper below
// does not recurse; the class embeds no marshaler-bearing concrete
// ancestor, so nothing is promoted (ADR 0022).
type rawDVScale DVScale

// MarshalJSONTo emits canonical openEHR JSON for DVScale with `_type`
// (value "DV_SCALE") as the leading member. Field order otherwise follows the
// struct declaration; json.Deterministic sorts any Hash keys and the
// FormatNil* options keep a mandatory nil container's `null` spelling
// (REQ-052, Q6). The receiver is a value so a concrete instance sitting
// in a polymorphic interface slot by value — the shape the like-interface
// accessors admit — still carries its `_type` (REQ-052 substitution).
func (d DVScale) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, &struct {
		Type string `json:"_type"`
		*rawDVScale
	}{"DV_SCALE", (*rawDVScale)(&d)}, typereg.MarshalOptions(enc))
}

// rawReferenceRange is the method-free canonical-JSON alias for ReferenceRange. The alias
// drops the codec methods so marshalling the anonymous wrapper below
// does not recurse; the class embeds no marshaler-bearing concrete
// ancestor, so nothing is promoted (ADR 0022).
type rawReferenceRange[T DVOrdered] ReferenceRange[T]

// MarshalJSONTo emits canonical openEHR JSON for ReferenceRange with `_type`
// (value "REFERENCE_RANGE") as the leading member. Field order otherwise follows the
// struct declaration; json.Deterministic sorts any Hash keys and the
// FormatNil* options keep a mandatory nil container's `null` spelling
// (REQ-052, Q6). The receiver is a value so a concrete instance sitting
// in a polymorphic interface slot by value — the shape the like-interface
// accessors admit — still carries its `_type` (REQ-052 substitution).
func (r ReferenceRange[T]) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, &struct {
		Type string `json:"_type"`
		*rawReferenceRange[T]
	}{"REFERENCE_RANGE", (*rawReferenceRange[T])(&r)}, typereg.MarshalOptions(enc))
}
