// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/xml"
	"fmt"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
	"github.com/cadasto/openehr-sdk-go/openehr/serialize/canxml"
)

// BMM package: org.openehr.rm.data_structures.item_structure — canonical-XML UnmarshalXML companions

// UnmarshalXML decodes canonical openEHR XML into ItemList.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are read from _start.Attr.
func (i *ItemList) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for _, _a := range _start.Attr {
		if _a.Name.Local == "archetype_node_id" && _a.Name.Space == "" {
			i.ArchetypeNodeID = _a.Value
			break
		}
	}
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "name":
				_v, _err := canxml.DecodeAsOrDefault[DVTextLike](_dec, _t, func() any { return new(DVText) })
				if _err != nil {
					return _err
				}
				i.Name = _v
			case "archetype_node_id":
				if _err := _dec.DecodeElement(&i.ArchetypeNodeID, &_t); _err != nil {
					return _err
				}
			case "uid":
				_v, _err := canxml.DecodeAs[UIDBasedID](_dec, _t)
				if _err != nil {
					return _err
				}
				i.UID = _v
			case "links":
				var _v Link
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				i.Links = append(i.Links, _v)
			case "archetype_details":
				_v := new(Archetyped)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				i.ArchetypeDetails = _v
			case "feeder_audit":
				_v := new(FeederAudit)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				i.FeederAudit = _v
			case "items":
				var _v Element
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				i.Items = append(i.Items, _v)
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// UnmarshalXML decodes canonical openEHR XML into ItemSingle.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are read from _start.Attr.
func (i *ItemSingle) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for _, _a := range _start.Attr {
		if _a.Name.Local == "archetype_node_id" && _a.Name.Space == "" {
			i.ArchetypeNodeID = _a.Value
			break
		}
	}
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "name":
				_v, _err := canxml.DecodeAsOrDefault[DVTextLike](_dec, _t, func() any { return new(DVText) })
				if _err != nil {
					return _err
				}
				i.Name = _v
			case "archetype_node_id":
				if _err := _dec.DecodeElement(&i.ArchetypeNodeID, &_t); _err != nil {
					return _err
				}
			case "uid":
				_v, _err := canxml.DecodeAs[UIDBasedID](_dec, _t)
				if _err != nil {
					return _err
				}
				i.UID = _v
			case "links":
				var _v Link
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				i.Links = append(i.Links, _v)
			case "archetype_details":
				_v := new(Archetyped)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				i.ArchetypeDetails = _v
			case "feeder_audit":
				_v := new(FeederAudit)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				i.FeederAudit = _v
			case "item":
				if _err := _dec.DecodeElement(&i.Item, &_t); _err != nil {
					return _err
				}
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// UnmarshalXML decodes canonical openEHR XML into ItemTable.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are read from _start.Attr.
func (i *ItemTable) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for _, _a := range _start.Attr {
		if _a.Name.Local == "archetype_node_id" && _a.Name.Space == "" {
			i.ArchetypeNodeID = _a.Value
			break
		}
	}
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "name":
				_v, _err := canxml.DecodeAsOrDefault[DVTextLike](_dec, _t, func() any { return new(DVText) })
				if _err != nil {
					return _err
				}
				i.Name = _v
			case "archetype_node_id":
				if _err := _dec.DecodeElement(&i.ArchetypeNodeID, &_t); _err != nil {
					return _err
				}
			case "uid":
				_v, _err := canxml.DecodeAs[UIDBasedID](_dec, _t)
				if _err != nil {
					return _err
				}
				i.UID = _v
			case "links":
				var _v Link
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				i.Links = append(i.Links, _v)
			case "archetype_details":
				_v := new(Archetyped)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				i.ArchetypeDetails = _v
			case "feeder_audit":
				_v := new(FeederAudit)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				i.FeederAudit = _v
			case "rows":
				var _v Cluster
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				i.Rows = append(i.Rows, _v)
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// UnmarshalXML decodes canonical openEHR XML into ItemTree.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are read from _start.Attr.
func (i *ItemTree) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for _, _a := range _start.Attr {
		if _a.Name.Local == "archetype_node_id" && _a.Name.Space == "" {
			i.ArchetypeNodeID = _a.Value
			break
		}
	}
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "name":
				_v, _err := canxml.DecodeAsOrDefault[DVTextLike](_dec, _t, func() any { return new(DVText) })
				if _err != nil {
					return _err
				}
				i.Name = _v
			case "archetype_node_id":
				if _err := _dec.DecodeElement(&i.ArchetypeNodeID, &_t); _err != nil {
					return _err
				}
			case "uid":
				_v, _err := canxml.DecodeAs[UIDBasedID](_dec, _t)
				if _err != nil {
					return _err
				}
				i.UID = _v
			case "links":
				var _v Link
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				i.Links = append(i.Links, _v)
			case "archetype_details":
				_v := new(Archetyped)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				i.ArchetypeDetails = _v
			case "feeder_audit":
				_v := new(FeederAudit)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				i.FeederAudit = _v
			case "items":
				_v, _err := canxml.DecodeAs[Item](_dec, _t)
				if _err != nil {
					return _err
				}
				i.Items = append(i.Items, _v)
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

var (
	_ = typereg.ErrMissingType
	_ = fmt.Sprintf
	_ = canxml.NSDefault
)
