// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/xml"
	"fmt"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
	"github.com/cadasto/openehr-sdk-go/openehr/serialize/canxml"
)

// BMM package: org.openehr.rm.data_types.encapsulated — canonical-XML UnmarshalXML companions

// UnmarshalXML decodes canonical openEHR XML into DVMultimedia.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are read from _start.Attr.
func (d *DVMultimedia) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "charset":
				_v := new(CodePhrase)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				d.Charset = _v
			case "language":
				_v := new(CodePhrase)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				d.Language = _v
			case "alternate_text":
				var _v string
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				d.AlternateText = &_v
			case "uri":
				_v, _err := canxml.DecodeAsOrDefault[DVURILike](_dec, _t, func() any { return new(DVURI) })
				if _err != nil {
					return _err
				}
				d.URI = _v
			case "data":
				var _v byte
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				d.Data = append(d.Data, _v)
			case "media_type":
				if _err := _dec.DecodeElement(&d.MediaType, &_t); _err != nil {
					return _err
				}
			case "compression_algorithm":
				_v := new(CodePhrase)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				d.CompressionAlgorithm = _v
			case "integrity_check":
				var _v byte
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				d.IntegrityCheck = append(d.IntegrityCheck, _v)
			case "integrity_check_algorithm":
				_v := new(CodePhrase)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				d.IntegrityCheckAlgorithm = _v
			case "thumbnail":
				_v := new(DVMultimedia)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				d.Thumbnail = _v
			case "size":
				if _err := _dec.DecodeElement(&d.Size, &_t); _err != nil {
					return _err
				}
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// UnmarshalXML decodes canonical openEHR XML into DVParsable.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are read from _start.Attr.
func (d *DVParsable) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "charset":
				_v := new(CodePhrase)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				d.Charset = _v
			case "language":
				_v := new(CodePhrase)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				d.Language = _v
			case "value":
				if _err := _dec.DecodeElement(&d.Value, &_t); _err != nil {
					return _err
				}
			case "formalism":
				if _err := _dec.DecodeElement(&d.Formalism, &_t); _err != nil {
					return _err
				}
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

var (
	_ = typereg.ErrMissingType
	_ = fmt.Sprintf
	_ = canxml.NSDefault
)
