// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/xml"

	"github.com/cadasto/openehr-sdk-go/openehr/serialize/canxml"
)

// BMM package: org.openehr.rm.data_types.text — canonical-XML MarshalXML companions

// BMMName returns "CODE_PHRASE" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (c *CodePhrase) BMMName() string { return "CODE_PHRASE" }

// MarshalXML emits canonical openEHR XML for CodePhrase. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are appended to start.Attr before
// the start token is written.
func (c *CodePhrase) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("CODE_PHRASE")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeElement(&c.TerminologyID, xml.StartElement{Name: xml.Name{Local: "terminology_id"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(c.CodeString, xml.StartElement{Name: xml.Name{Local: "code_string"}}); err != nil {
		return err
	}
	if c.PreferredTerm != nil {
		if err := _e.EncodeElement(*c.PreferredTerm, xml.StartElement{Name: xml.Name{Local: "preferred_term"}}); err != nil {
			return err
		}
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "DV_CODED_TEXT" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (d *DVCodedText) BMMName() string { return "DV_CODED_TEXT" }

// MarshalXML emits canonical openEHR XML for DVCodedText. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are appended to start.Attr before
// the start token is written.
func (d *DVCodedText) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("DV_CODED_TEXT")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeElement(d.Value, xml.StartElement{Name: xml.Name{Local: "value"}}); err != nil {
		return err
	}
	if d.Hyperlink != nil {
		if err := canxml.EncodePoly(_e, "hyperlink", d.Hyperlink); err != nil {
			return err
		}
	}
	if d.Formatting != nil {
		if err := _e.EncodeElement(*d.Formatting, xml.StartElement{Name: xml.Name{Local: "formatting"}}); err != nil {
			return err
		}
	}
	for _idx := range d.Mappings {
		if err := _e.EncodeElement(&d.Mappings[_idx], xml.StartElement{Name: xml.Name{Local: "mappings"}}); err != nil {
			return err
		}
	}
	if d.Language != nil {
		if err := _e.EncodeElement(d.Language, xml.StartElement{Name: xml.Name{Local: "language"}}); err != nil {
			return err
		}
	}
	if d.Encoding != nil {
		if err := _e.EncodeElement(d.Encoding, xml.StartElement{Name: xml.Name{Local: "encoding"}}); err != nil {
			return err
		}
	}
	if err := _e.EncodeElement(&d.DefiningCode, xml.StartElement{Name: xml.Name{Local: "defining_code"}}); err != nil {
		return err
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "DV_PARAGRAPH" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (d *DVParagraph) BMMName() string { return "DV_PARAGRAPH" }

// MarshalXML emits canonical openEHR XML for DVParagraph. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are appended to start.Attr before
// the start token is written.
func (d *DVParagraph) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("DV_PARAGRAPH")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	for _, _item := range d.Items {
		if _item == nil {
			continue
		}
		if err := canxml.EncodePoly(_e, "items", _item); err != nil {
			return err
		}
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "DV_TEXT" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (d *DVText) BMMName() string { return "DV_TEXT" }

// MarshalXML emits canonical openEHR XML for DVText. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are appended to start.Attr before
// the start token is written.
func (d *DVText) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("DV_TEXT")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeElement(d.Value, xml.StartElement{Name: xml.Name{Local: "value"}}); err != nil {
		return err
	}
	if d.Hyperlink != nil {
		if err := canxml.EncodePoly(_e, "hyperlink", d.Hyperlink); err != nil {
			return err
		}
	}
	if d.Formatting != nil {
		if err := _e.EncodeElement(*d.Formatting, xml.StartElement{Name: xml.Name{Local: "formatting"}}); err != nil {
			return err
		}
	}
	for _idx := range d.Mappings {
		if err := _e.EncodeElement(&d.Mappings[_idx], xml.StartElement{Name: xml.Name{Local: "mappings"}}); err != nil {
			return err
		}
	}
	if d.Language != nil {
		if err := _e.EncodeElement(d.Language, xml.StartElement{Name: xml.Name{Local: "language"}}); err != nil {
			return err
		}
	}
	if d.Encoding != nil {
		if err := _e.EncodeElement(d.Encoding, xml.StartElement{Name: xml.Name{Local: "encoding"}}); err != nil {
			return err
		}
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "TERM_MAPPING" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (t *TermMapping) BMMName() string { return "TERM_MAPPING" }

// MarshalXML emits canonical openEHR XML for TermMapping. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are appended to start.Attr before
// the start token is written.
func (t *TermMapping) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("TERM_MAPPING")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeElement(t.Match, xml.StartElement{Name: xml.Name{Local: "match"}}); err != nil {
		return err
	}
	if t.Purpose != nil {
		if err := _e.EncodeElement(t.Purpose, xml.StartElement{Name: xml.Name{Local: "purpose"}}); err != nil {
			return err
		}
	}
	if err := _e.EncodeElement(&t.Target, xml.StartElement{Name: xml.Name{Local: "target"}}); err != nil {
		return err
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}
