// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/json/jsontext"
	json "encoding/json/v2"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
)

// BMM package: org.openehr.rm.data_structures.item_structure — canonical-JSON MarshalJSONTo companions

// rawItemList is the method-free canonical-JSON alias for ItemList. The alias
// drops the codec methods so marshalling the anonymous wrapper below
// does not recurse; the class embeds no marshaler-bearing concrete
// ancestor, so nothing is promoted (ADR 0022).
type rawItemList ItemList

// MarshalJSONTo emits canonical openEHR JSON for ItemList with `_type`
// (value "ITEM_LIST") as the leading member. Field order otherwise follows the
// struct declaration; json.Deterministic sorts any Hash keys and the
// FormatNil* options keep a mandatory nil container's `null` spelling
// (REQ-052, Q6). The receiver is a value so a concrete instance sitting
// in a polymorphic interface slot by value — the shape the like-interface
// accessors admit — still carries its `_type` (REQ-052 substitution).
func (i ItemList) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, &struct {
		Type string `json:"_type"`
		*rawItemList
	}{"ITEM_LIST", (*rawItemList)(&i)}, typereg.MarshalOptions(enc))
}

// rawItemSingle is the method-free canonical-JSON alias for ItemSingle. The alias
// drops the codec methods so marshalling the anonymous wrapper below
// does not recurse; the class embeds no marshaler-bearing concrete
// ancestor, so nothing is promoted (ADR 0022).
type rawItemSingle ItemSingle

// MarshalJSONTo emits canonical openEHR JSON for ItemSingle with `_type`
// (value "ITEM_SINGLE") as the leading member. Field order otherwise follows the
// struct declaration; json.Deterministic sorts any Hash keys and the
// FormatNil* options keep a mandatory nil container's `null` spelling
// (REQ-052, Q6). The receiver is a value so a concrete instance sitting
// in a polymorphic interface slot by value — the shape the like-interface
// accessors admit — still carries its `_type` (REQ-052 substitution).
func (i ItemSingle) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, &struct {
		Type string `json:"_type"`
		*rawItemSingle
	}{"ITEM_SINGLE", (*rawItemSingle)(&i)}, typereg.MarshalOptions(enc))
}

// rawItemTable is the method-free canonical-JSON alias for ItemTable. The alias
// drops the codec methods so marshalling the anonymous wrapper below
// does not recurse; the class embeds no marshaler-bearing concrete
// ancestor, so nothing is promoted (ADR 0022).
type rawItemTable ItemTable

// MarshalJSONTo emits canonical openEHR JSON for ItemTable with `_type`
// (value "ITEM_TABLE") as the leading member. Field order otherwise follows the
// struct declaration; json.Deterministic sorts any Hash keys and the
// FormatNil* options keep a mandatory nil container's `null` spelling
// (REQ-052, Q6). The receiver is a value so a concrete instance sitting
// in a polymorphic interface slot by value — the shape the like-interface
// accessors admit — still carries its `_type` (REQ-052 substitution).
func (i ItemTable) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, &struct {
		Type string `json:"_type"`
		*rawItemTable
	}{"ITEM_TABLE", (*rawItemTable)(&i)}, typereg.MarshalOptions(enc))
}

// rawItemTree is the method-free canonical-JSON alias for ItemTree. The alias
// drops the codec methods so marshalling the anonymous wrapper below
// does not recurse; the class embeds no marshaler-bearing concrete
// ancestor, so nothing is promoted (ADR 0022).
type rawItemTree ItemTree

// MarshalJSONTo emits canonical openEHR JSON for ItemTree with `_type`
// (value "ITEM_TREE") as the leading member. Field order otherwise follows the
// struct declaration; json.Deterministic sorts any Hash keys and the
// FormatNil* options keep a mandatory nil container's `null` spelling
// (REQ-052, Q6). The receiver is a value so a concrete instance sitting
// in a polymorphic interface slot by value — the shape the like-interface
// accessors admit — still carries its `_type` (REQ-052 substitution).
func (i ItemTree) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, &struct {
		Type string `json:"_type"`
		*rawItemTree
	}{"ITEM_TREE", (*rawItemTree)(&i)}, typereg.MarshalOptions(enc))
}
