// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/json/jsontext"
	"fmt"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
)

// BMM package org.openehr.rm.data_types.quantity: canonical-JSON UnmarshalJSONFrom companions

// UnmarshalJSONFrom decodes canonical openEHR JSON into DVCount.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError, keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (d *DVCount) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if d == nil {
		return fmt.Errorf("canjson: DV_COUNT: %w", typereg.ErrNilReceiver)
	}
	w := struct {
		Type string `json:"_type"`
		*rawDVCount
	}{rawDVCount: (*rawDVCount)(d)}
	return typereg.DecodeInto(dec, "DV_COUNT", &w, &w.Type)
}

// UnmarshalJSONFrom decodes canonical openEHR JSON into DVInterval.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError, keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (d *DVInterval[T]) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if d == nil {
		return fmt.Errorf("canjson: DV_INTERVAL: %w", typereg.ErrNilReceiver)
	}
	w := struct {
		Type string `json:"_type"`
		*rawDVInterval[T]
	}{rawDVInterval: (*rawDVInterval[T])(d)}
	return typereg.DecodeInto(dec, "DV_INTERVAL", &w, &w.Type)
}

// UnmarshalJSONFrom decodes canonical openEHR JSON into DVOrdinal.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError, keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (d *DVOrdinal) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if d == nil {
		return fmt.Errorf("canjson: DV_ORDINAL: %w", typereg.ErrNilReceiver)
	}
	w := struct {
		Type string `json:"_type"`
		*rawDVOrdinal
	}{rawDVOrdinal: (*rawDVOrdinal)(d)}
	return typereg.DecodeInto(dec, "DV_ORDINAL", &w, &w.Type)
}

// UnmarshalJSONFrom decodes canonical openEHR JSON into DVProportion.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError, keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (d *DVProportion) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if d == nil {
		return fmt.Errorf("canjson: DV_PROPORTION: %w", typereg.ErrNilReceiver)
	}
	w := struct {
		Type string `json:"_type"`
		*rawDVProportion
	}{rawDVProportion: (*rawDVProportion)(d)}
	return typereg.DecodeInto(dec, "DV_PROPORTION", &w, &w.Type)
}

// UnmarshalJSONFrom decodes canonical openEHR JSON into DVQuantity.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError, keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (d *DVQuantity) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if d == nil {
		return fmt.Errorf("canjson: DV_QUANTITY: %w", typereg.ErrNilReceiver)
	}
	w := struct {
		Type string `json:"_type"`
		*rawDVQuantity
	}{rawDVQuantity: (*rawDVQuantity)(d)}
	return typereg.DecodeInto(dec, "DV_QUANTITY", &w, &w.Type)
}

// UnmarshalJSONFrom decodes canonical openEHR JSON into DVScale.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError, keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (d *DVScale) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if d == nil {
		return fmt.Errorf("canjson: DV_SCALE: %w", typereg.ErrNilReceiver)
	}
	w := struct {
		Type string `json:"_type"`
		*rawDVScale
	}{rawDVScale: (*rawDVScale)(d)}
	return typereg.DecodeInto(dec, "DV_SCALE", &w, &w.Type)
}

// UnmarshalJSONFrom decodes canonical openEHR JSON into ReferenceRange.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError, keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (r *ReferenceRange[T]) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if r == nil {
		return fmt.Errorf("canjson: REFERENCE_RANGE: %w", typereg.ErrNilReceiver)
	}
	w := struct {
		Type string `json:"_type"`
		*rawReferenceRange[T]
	}{rawReferenceRange: (*rawReferenceRange[T])(r)}
	return typereg.DecodeInto(dec, "REFERENCE_RANGE", &w, &w.Type)
}
