// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/json"
	"fmt"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
)

// BMM package: org.openehr.rm.data_types.quantity.date_time — canonical-JSON UnmarshalJSON companions

type DVDateJSONUnmarshaller struct {
	Class string `json:"_type"`
	// MagnitudeStatus Optional status of magnitude with values:
	//
	// * `"="`   :   magnitude is a point value
	// * `"<"`   :   value is < magnitude
	// * `">"`   :   value is > magnitude
	// * `"<="` : value is <= magnitude
	// * `">="` : value is >= magnitude
	// * `"~"`   :   value is approximately magnitude
	//
	// If not present, assumed meaning is  `"="` .
	MagnitudeStatus *string `json:"magnitude_status,omitempty"`
	// Accuracy Time accuracy, expressed as a duration.
	Accuracy *DVDuration `json:"accuracy,omitempty"`
	// NormalStatus Optional normal status indicator of value with respect to normal range for this value. Often included by lab, even if the normal range itself is not included. Coded by ordinals in series HHH, HH, H, (nothing), L, LL, LLL; see openEHR terminology group  `normal_status`.
	NormalStatus *CodePhrase `json:"normal_status,omitempty"`
	// NormalRange Optional normal range.
	NormalRange *DVInterval[DVOrdered] `json:"normal_range,omitempty"`
	// OtherReferenceRanges Optional tagged other reference ranges for this value in its particular measurement context.
	OtherReferenceRanges []ReferenceRange[DVOrdered] `json:"other_reference_ranges,omitempty"`
	// Value ISO8601 date string.
	Value string `json:"value"`
}

// UnmarshalJSON decodes canonical openEHR JSON into DVDate.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (d *DVDate) UnmarshalJSON(data []byte) error {
	var aux DVDateJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: DV_DATE: %w", err)
	}
	if aux.Class != "" && aux.Class != "DV_DATE" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q, got %q: %w", "DV_DATE", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	d.MagnitudeStatus = aux.MagnitudeStatus
	d.Accuracy = aux.Accuracy
	d.NormalStatus = aux.NormalStatus
	d.NormalRange = aux.NormalRange
	d.OtherReferenceRanges = aux.OtherReferenceRanges
	d.Value = aux.Value
	return nil
}

type DVDateTimeJSONUnmarshaller struct {
	Class string `json:"_type"`
	// MagnitudeStatus Optional status of magnitude with values:
	//
	// * `"="`   :   magnitude is a point value
	// * `"<"`   :   value is < magnitude
	// * `">"`   :   value is > magnitude
	// * `"<="` : value is <= magnitude
	// * `">="` : value is >= magnitude
	// * `"~"`   :   value is approximately magnitude
	//
	// If not present, assumed meaning is  `"="` .
	MagnitudeStatus *string `json:"magnitude_status,omitempty"`
	// Accuracy Time accuracy, expressed as a duration.
	Accuracy *DVDuration `json:"accuracy,omitempty"`
	// NormalStatus Optional normal status indicator of value with respect to normal range for this value. Often included by lab, even if the normal range itself is not included. Coded by ordinals in series HHH, HH, H, (nothing), L, LL, LLL; see openEHR terminology group  `normal_status`.
	NormalStatus *CodePhrase `json:"normal_status,omitempty"`
	// NormalRange Optional normal range.
	NormalRange *DVInterval[DVOrdered] `json:"normal_range,omitempty"`
	// OtherReferenceRanges Optional tagged other reference ranges for this value in its particular measurement context.
	OtherReferenceRanges []ReferenceRange[DVOrdered] `json:"other_reference_ranges,omitempty"`
	// Value ISO8601 date/time string.
	Value string `json:"value"`
}

// UnmarshalJSON decodes canonical openEHR JSON into DVDateTime.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (d *DVDateTime) UnmarshalJSON(data []byte) error {
	var aux DVDateTimeJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: DV_DATE_TIME: %w", err)
	}
	if aux.Class != "" && aux.Class != "DV_DATE_TIME" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q, got %q: %w", "DV_DATE_TIME", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	d.MagnitudeStatus = aux.MagnitudeStatus
	d.Accuracy = aux.Accuracy
	d.NormalStatus = aux.NormalStatus
	d.NormalRange = aux.NormalRange
	d.OtherReferenceRanges = aux.OtherReferenceRanges
	d.Value = aux.Value
	return nil
}

type DVDurationJSONUnmarshaller struct {
	Class string `json:"_type"`
	// AccuracyIsPercent If `True`, indicates that when this object was created, `_accuracy_` was recorded as a percent value; if `False`, as an absolute quantity value.
	AccuracyIsPercent *bool `json:"accuracy_is_percent,omitempty"`
	// MagnitudeStatus Optional status of magnitude with values:
	//
	// * `"="`   :   magnitude is a point value
	// * `"<"`   :   value is < magnitude
	// * `">"`   :   value is > magnitude
	// * `"<="` : value is <= magnitude
	// * `">="` : value is >= magnitude
	// * `"~"`   :   value is approximately magnitude
	//
	// If not present, assumed meaning is  `"="` .
	MagnitudeStatus *string `json:"magnitude_status,omitempty"`
	// Accuracy Accuracy of measurement, expressed either as a half-range percent value (`_accuracy_is_percent_` = `True`) or a half-range quantity. A value of `0` means that accuracy is 100%, i.e. no error.
	//
	// A value of `_unknown_accuracy_value_` means that accuracy was not recorded.
	Accuracy *Real `json:"accuracy,omitempty"`
	// NormalStatus Optional normal status indicator of value with respect to normal range for this value. Often included by lab, even if the normal range itself is not included. Coded by ordinals in series HHH, HH, H, (nothing), L, LL, LLL; see openEHR terminology group  `normal_status`.
	NormalStatus *CodePhrase `json:"normal_status,omitempty"`
	// NormalRange Optional normal range.
	NormalRange *DVInterval[DVOrdered] `json:"normal_range,omitempty"`
	// OtherReferenceRanges Optional tagged other reference ranges for this value in its particular measurement context.
	OtherReferenceRanges []ReferenceRange[DVOrdered] `json:"other_reference_ranges,omitempty"`
	// Value ISO8601 duration string, including described deviations to support negative values and weeks.
	Value string `json:"value"`
}

// UnmarshalJSON decodes canonical openEHR JSON into DVDuration.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (d *DVDuration) UnmarshalJSON(data []byte) error {
	var aux DVDurationJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: DV_DURATION: %w", err)
	}
	if aux.Class != "" && aux.Class != "DV_DURATION" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q, got %q: %w", "DV_DURATION", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	d.AccuracyIsPercent = aux.AccuracyIsPercent
	d.MagnitudeStatus = aux.MagnitudeStatus
	d.Accuracy = aux.Accuracy
	d.NormalStatus = aux.NormalStatus
	d.NormalRange = aux.NormalRange
	d.OtherReferenceRanges = aux.OtherReferenceRanges
	d.Value = aux.Value
	return nil
}

type DVTimeJSONUnmarshaller struct {
	Class string `json:"_type"`
	// MagnitudeStatus Optional status of magnitude with values:
	//
	// * `"="`   :   magnitude is a point value
	// * `"<"`   :   value is < magnitude
	// * `">"`   :   value is > magnitude
	// * `"<="` : value is <= magnitude
	// * `">="` : value is >= magnitude
	// * `"~"`   :   value is approximately magnitude
	//
	// If not present, assumed meaning is  `"="` .
	MagnitudeStatus *string `json:"magnitude_status,omitempty"`
	// Accuracy Time accuracy, expressed as a duration.
	Accuracy *DVDuration `json:"accuracy,omitempty"`
	// NormalStatus Optional normal status indicator of value with respect to normal range for this value. Often included by lab, even if the normal range itself is not included. Coded by ordinals in series HHH, HH, H, (nothing), L, LL, LLL; see openEHR terminology group  `normal_status`.
	NormalStatus *CodePhrase `json:"normal_status,omitempty"`
	// NormalRange Optional normal range.
	NormalRange *DVInterval[DVOrdered] `json:"normal_range,omitempty"`
	// OtherReferenceRanges Optional tagged other reference ranges for this value in its particular measurement context.
	OtherReferenceRanges []ReferenceRange[DVOrdered] `json:"other_reference_ranges,omitempty"`
	// Value ISO8601 time string
	Value string `json:"value"`
}

// UnmarshalJSON decodes canonical openEHR JSON into DVTime.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (d *DVTime) UnmarshalJSON(data []byte) error {
	var aux DVTimeJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: DV_TIME: %w", err)
	}
	if aux.Class != "" && aux.Class != "DV_TIME" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q, got %q: %w", "DV_TIME", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	d.MagnitudeStatus = aux.MagnitudeStatus
	d.Accuracy = aux.Accuracy
	d.NormalStatus = aux.NormalStatus
	d.NormalRange = aux.NormalRange
	d.OtherReferenceRanges = aux.OtherReferenceRanges
	d.Value = aux.Value
	return nil
}
