// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/json/jsontext"
	json "encoding/json/v2"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
)

// BMM package: org.openehr.rm.data_types.quantity.date_time — canonical-JSON MarshalJSONTo companions

// rawDVDate is the method-free canonical-JSON alias for DVDate. The alias
// drops the codec methods so marshalling the anonymous wrapper below
// does not recurse; the class embeds no marshaler-bearing concrete
// ancestor, so nothing is promoted (ADR 0022).
type rawDVDate DVDate

// MarshalJSONTo emits canonical openEHR JSON for DVDate with `_type`
// (value "DV_DATE") as the leading member. Field order otherwise follows the
// struct declaration; json.Deterministic sorts any Hash keys and the
// FormatNil* options keep a mandatory nil container's `null` spelling
// (REQ-052, Q6). The receiver is a value so a concrete instance sitting
// in a polymorphic interface slot by value — the shape the like-interface
// accessors admit — still carries its `_type` (REQ-052 substitution).
func (d DVDate) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, &struct {
		Type string `json:"_type"`
		*rawDVDate
	}{"DV_DATE", (*rawDVDate)(&d)}, typereg.MarshalOptions(enc))
}

// rawDVDateTime is the method-free canonical-JSON alias for DVDateTime. The alias
// drops the codec methods so marshalling the anonymous wrapper below
// does not recurse; the class embeds no marshaler-bearing concrete
// ancestor, so nothing is promoted (ADR 0022).
type rawDVDateTime DVDateTime

// MarshalJSONTo emits canonical openEHR JSON for DVDateTime with `_type`
// (value "DV_DATE_TIME") as the leading member. Field order otherwise follows the
// struct declaration; json.Deterministic sorts any Hash keys and the
// FormatNil* options keep a mandatory nil container's `null` spelling
// (REQ-052, Q6). The receiver is a value so a concrete instance sitting
// in a polymorphic interface slot by value — the shape the like-interface
// accessors admit — still carries its `_type` (REQ-052 substitution).
func (d DVDateTime) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, &struct {
		Type string `json:"_type"`
		*rawDVDateTime
	}{"DV_DATE_TIME", (*rawDVDateTime)(&d)}, typereg.MarshalOptions(enc))
}

// rawDVDuration is the method-free canonical-JSON alias for DVDuration. The alias
// drops the codec methods so marshalling the anonymous wrapper below
// does not recurse; the class embeds no marshaler-bearing concrete
// ancestor, so nothing is promoted (ADR 0022).
type rawDVDuration DVDuration

// MarshalJSONTo emits canonical openEHR JSON for DVDuration with `_type`
// (value "DV_DURATION") as the leading member. Field order otherwise follows the
// struct declaration; json.Deterministic sorts any Hash keys and the
// FormatNil* options keep a mandatory nil container's `null` spelling
// (REQ-052, Q6). The receiver is a value so a concrete instance sitting
// in a polymorphic interface slot by value — the shape the like-interface
// accessors admit — still carries its `_type` (REQ-052 substitution).
func (d DVDuration) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, &struct {
		Type string `json:"_type"`
		*rawDVDuration
	}{"DV_DURATION", (*rawDVDuration)(&d)}, typereg.MarshalOptions(enc))
}

// rawDVTime is the method-free canonical-JSON alias for DVTime. The alias
// drops the codec methods so marshalling the anonymous wrapper below
// does not recurse; the class embeds no marshaler-bearing concrete
// ancestor, so nothing is promoted (ADR 0022).
type rawDVTime DVTime

// MarshalJSONTo emits canonical openEHR JSON for DVTime with `_type`
// (value "DV_TIME") as the leading member. Field order otherwise follows the
// struct declaration; json.Deterministic sorts any Hash keys and the
// FormatNil* options keep a mandatory nil container's `null` spelling
// (REQ-052, Q6). The receiver is a value so a concrete instance sitting
// in a polymorphic interface slot by value — the shape the like-interface
// accessors admit — still carries its `_type` (REQ-052 substitution).
func (d DVTime) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, &struct {
		Type string `json:"_type"`
		*rawDVTime
	}{"DV_TIME", (*rawDVTime)(&d)}, typereg.MarshalOptions(enc))
}
