// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/xml"
	"fmt"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
	"github.com/cadasto/openehr-sdk-go/openehr/serialize/canxml"
)

// BMM package: org.openehr.rm.data_structures.history — canonical-XML UnmarshalXML companions

// UnmarshalXML decodes canonical openEHR XML into History.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are read from _start.Attr.
func (h *History[T]) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for _, _a := range _start.Attr {
		if _a.Name.Local == "archetype_node_id" && _a.Name.Space == "" {
			h.ArchetypeNodeID = _a.Value
			break
		}
	}
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "name":
				if _err := _dec.DecodeElement(&h.Name, &_t); _err != nil {
					return _err
				}
			case "archetype_node_id":
				if _err := _dec.DecodeElement(&h.ArchetypeNodeID, &_t); _err != nil {
					return _err
				}
			case "uid":
				_v, _err := canxml.DecodeAs[UIDBasedID](_dec, _t)
				if _err != nil {
					return _err
				}
				h.UID = _v
			case "links":
				var _v Link
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				h.Links = append(h.Links, _v)
			case "archetype_details":
				_v := new(Archetyped)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				h.ArchetypeDetails = _v
			case "feeder_audit":
				_v := new(FeederAudit)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				h.FeederAudit = _v
			case "origin":
				if _err := _dec.DecodeElement(&h.Origin, &_t); _err != nil {
					return _err
				}
			case "period":
				_v := new(DVDuration)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				h.Period = _v
			case "duration":
				_v := new(DVDuration)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				h.Duration = _v
			case "summary":
				_v, _err := canxml.DecodeAs[ItemStructure](_dec, _t)
				if _err != nil {
					return _err
				}
				h.Summary = _v
			case "events":
				_v, _err := canxml.DecodeAs[Event](_dec, _t)
				if _err != nil {
					return _err
				}
				h.Events = append(h.Events, _v)
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// UnmarshalXML decodes canonical openEHR XML into IntervalEvent.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are read from _start.Attr.
func (i *IntervalEvent[T]) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for _, _a := range _start.Attr {
		if _a.Name.Local == "archetype_node_id" && _a.Name.Space == "" {
			i.ArchetypeNodeID = _a.Value
			break
		}
	}
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "time":
				if _err := _dec.DecodeElement(&i.Time, &_t); _err != nil {
					return _err
				}
			case "state":
				_v, _err := canxml.DecodeAs[ItemStructure](_dec, _t)
				if _err != nil {
					return _err
				}
				i.State = _v
			case "data":
				_v, _err := canxml.DecodeAs[T](_dec, _t)
				if _err != nil {
					return _err
				}
				i.Data = _v
			case "name":
				if _err := _dec.DecodeElement(&i.Name, &_t); _err != nil {
					return _err
				}
			case "archetype_node_id":
				if _err := _dec.DecodeElement(&i.ArchetypeNodeID, &_t); _err != nil {
					return _err
				}
			case "uid":
				_v, _err := canxml.DecodeAs[UIDBasedID](_dec, _t)
				if _err != nil {
					return _err
				}
				i.UID = _v
			case "links":
				var _v Link
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				i.Links = append(i.Links, _v)
			case "archetype_details":
				_v := new(Archetyped)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				i.ArchetypeDetails = _v
			case "feeder_audit":
				_v := new(FeederAudit)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				i.FeederAudit = _v
			case "width":
				if _err := _dec.DecodeElement(&i.Width, &_t); _err != nil {
					return _err
				}
			case "sample_count":
				var _v Integer
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				i.SampleCount = &_v
			case "math_function":
				if _err := _dec.DecodeElement(&i.MathFunction, &_t); _err != nil {
					return _err
				}
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// UnmarshalXML decodes canonical openEHR XML into PointEvent.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are read from _start.Attr.
func (p *PointEvent[T]) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for _, _a := range _start.Attr {
		if _a.Name.Local == "archetype_node_id" && _a.Name.Space == "" {
			p.ArchetypeNodeID = _a.Value
			break
		}
	}
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "time":
				if _err := _dec.DecodeElement(&p.Time, &_t); _err != nil {
					return _err
				}
			case "state":
				_v, _err := canxml.DecodeAs[ItemStructure](_dec, _t)
				if _err != nil {
					return _err
				}
				p.State = _v
			case "data":
				_v, _err := canxml.DecodeAs[T](_dec, _t)
				if _err != nil {
					return _err
				}
				p.Data = _v
			case "name":
				if _err := _dec.DecodeElement(&p.Name, &_t); _err != nil {
					return _err
				}
			case "archetype_node_id":
				if _err := _dec.DecodeElement(&p.ArchetypeNodeID, &_t); _err != nil {
					return _err
				}
			case "uid":
				_v, _err := canxml.DecodeAs[UIDBasedID](_dec, _t)
				if _err != nil {
					return _err
				}
				p.UID = _v
			case "links":
				var _v Link
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				p.Links = append(p.Links, _v)
			case "archetype_details":
				_v := new(Archetyped)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				p.ArchetypeDetails = _v
			case "feeder_audit":
				_v := new(FeederAudit)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				p.FeederAudit = _v
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

var (
	_ = typereg.ErrMissingType
	_ = fmt.Sprintf
	_ = canxml.NSDefault
)
