// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/json/jsontext"
	"fmt"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
)

// BMM package org.openehr.rm.data_types.text: canonical-JSON UnmarshalJSONFrom companions

// UnmarshalJSONFrom decodes canonical openEHR JSON into CodePhrase.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError, keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (c *CodePhrase) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if c == nil {
		return fmt.Errorf("canjson: CODE_PHRASE: %w", typereg.ErrNilReceiver)
	}
	return typereg.DecodeInto(dec, "CODE_PHRASE", &struct {
		Type string `json:"_type"`
		*rawCodePhrase
	}{rawCodePhrase: (*rawCodePhrase)(c)})
}

// UnmarshalJSONFrom decodes canonical openEHR JSON into DVCodedText.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError, keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (d *DVCodedText) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if d == nil {
		return fmt.Errorf("canjson: DV_CODED_TEXT: %w", typereg.ErrNilReceiver)
	}
	var wire jsonWireDVCodedText
	if err := typereg.DecodeInto(dec, "DV_CODED_TEXT", &wire); err != nil {
		return err
	}
	d.Value = wire.Value
	d.Hyperlink = wire.Hyperlink
	d.Formatting = wire.Formatting
	d.Mappings = wire.Mappings
	d.Language = wire.Language
	d.Encoding = wire.Encoding
	d.DefiningCode = wire.DefiningCode
	return nil
}

// UnmarshalJSONFrom decodes canonical openEHR JSON into DVParagraph.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError, keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (d *DVParagraph) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if d == nil {
		return fmt.Errorf("canjson: DV_PARAGRAPH: %w", typereg.ErrNilReceiver)
	}
	return typereg.DecodeInto(dec, "DV_PARAGRAPH", &struct {
		Type string `json:"_type"`
		*rawDVParagraph
	}{rawDVParagraph: (*rawDVParagraph)(d)})
}

// UnmarshalJSONFrom decodes canonical openEHR JSON into DVText.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError, keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (d *DVText) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if d == nil {
		return fmt.Errorf("canjson: DV_TEXT: %w", typereg.ErrNilReceiver)
	}
	return typereg.DecodeInto(dec, "DV_TEXT", &struct {
		Type string `json:"_type"`
		*rawDVText
	}{rawDVText: (*rawDVText)(d)})
}

// UnmarshalJSONFrom decodes canonical openEHR JSON into TermMapping.
// A nil receiver is refused with typereg.ErrNilReceiver rather than
// dereferenced (REQ-025). The shared helper checks the `_type`
// discriminator, threads the polymorphic decode hooks so every nested
// slot resolves, and wraps a whole-value shape failure through
// typereg.WrapShapeError, keeping the `canjson: <RM_TYPE>:` text and
// adding typereg.ErrInvalidShape (REQ-052, ADR 0022).
func (t *TermMapping) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if t == nil {
		return fmt.Errorf("canjson: TERM_MAPPING: %w", typereg.ErrNilReceiver)
	}
	return typereg.DecodeInto(dec, "TERM_MAPPING", &struct {
		Type string `json:"_type"`
		*rawTermMapping
	}{rawTermMapping: (*rawTermMapping)(t)})
}
