// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/xml"

	"github.com/cadasto/openehr-sdk-go/openehr/serialize/canxml"
)

// BMM package: org.openehr.rm.demographic — canonical-XML MarshalXML companions

// BMMName returns "ADDRESS" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (a *Address) BMMName() string { return "ADDRESS" }

// MarshalXML emits canonical openEHR XML for Address. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are appended to start.Attr before
// the start token is written.
func (a *Address) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("ADDRESS")}
	}
	_start.Attr = append(_start.Attr, xml.Attr{Name: xml.Name{Local: "archetype_node_id"}, Value: a.ArchetypeNodeID})
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if a.Name != nil {
		if err := canxml.EncodePoly(_e, "name", a.Name); err != nil {
			return err
		}
	}
	if a.UID != nil {
		if err := canxml.EncodePoly(_e, "uid", a.UID); err != nil {
			return err
		}
	}
	for _idx := range a.Links {
		if err := _e.EncodeElement(&a.Links[_idx], xml.StartElement{Name: xml.Name{Local: "links"}}); err != nil {
			return err
		}
	}
	if a.ArchetypeDetails != nil {
		if err := _e.EncodeElement(a.ArchetypeDetails, xml.StartElement{Name: xml.Name{Local: "archetype_details"}}); err != nil {
			return err
		}
	}
	if a.FeederAudit != nil {
		if err := _e.EncodeElement(a.FeederAudit, xml.StartElement{Name: xml.Name{Local: "feeder_audit"}}); err != nil {
			return err
		}
	}
	if a.Details != nil {
		if err := canxml.EncodePoly(_e, "details", a.Details); err != nil {
			return err
		}
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "AGENT" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (a *Agent) BMMName() string { return "AGENT" }

// MarshalXML emits canonical openEHR XML for Agent. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are appended to start.Attr before
// the start token is written.
func (a *Agent) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("AGENT")}
	}
	_start.Attr = append(_start.Attr, xml.Attr{Name: xml.Name{Local: "archetype_node_id"}, Value: a.ArchetypeNodeID})
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	for _, _item := range a.Languages {
		if _item == nil {
			continue
		}
		if err := canxml.EncodePoly(_e, "languages", _item); err != nil {
			return err
		}
	}
	for _idx := range a.Roles {
		if err := _e.EncodeElement(&a.Roles[_idx], xml.StartElement{Name: xml.Name{Local: "roles"}}); err != nil {
			return err
		}
	}
	for _idx := range a.Identities {
		if err := _e.EncodeElement(&a.Identities[_idx], xml.StartElement{Name: xml.Name{Local: "identities"}}); err != nil {
			return err
		}
	}
	for _idx := range a.Contacts {
		if err := _e.EncodeElement(&a.Contacts[_idx], xml.StartElement{Name: xml.Name{Local: "contacts"}}); err != nil {
			return err
		}
	}
	if a.Details != nil {
		if err := canxml.EncodePoly(_e, "details", a.Details); err != nil {
			return err
		}
	}
	for _idx := range a.Relationships {
		if err := _e.EncodeElement(&a.Relationships[_idx], xml.StartElement{Name: xml.Name{Local: "relationships"}}); err != nil {
			return err
		}
	}
	if a.Name != nil {
		if err := canxml.EncodePoly(_e, "name", a.Name); err != nil {
			return err
		}
	}
	if a.UID != nil {
		if err := canxml.EncodePoly(_e, "uid", a.UID); err != nil {
			return err
		}
	}
	for _idx := range a.Links {
		if err := _e.EncodeElement(&a.Links[_idx], xml.StartElement{Name: xml.Name{Local: "links"}}); err != nil {
			return err
		}
	}
	if a.ArchetypeDetails != nil {
		if err := _e.EncodeElement(a.ArchetypeDetails, xml.StartElement{Name: xml.Name{Local: "archetype_details"}}); err != nil {
			return err
		}
	}
	if a.FeederAudit != nil {
		if err := _e.EncodeElement(a.FeederAudit, xml.StartElement{Name: xml.Name{Local: "feeder_audit"}}); err != nil {
			return err
		}
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "CAPABILITY" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (c *Capability) BMMName() string { return "CAPABILITY" }

// MarshalXML emits canonical openEHR XML for Capability. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are appended to start.Attr before
// the start token is written.
func (c *Capability) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("CAPABILITY")}
	}
	_start.Attr = append(_start.Attr, xml.Attr{Name: xml.Name{Local: "archetype_node_id"}, Value: c.ArchetypeNodeID})
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if c.Name != nil {
		if err := canxml.EncodePoly(_e, "name", c.Name); err != nil {
			return err
		}
	}
	if c.UID != nil {
		if err := canxml.EncodePoly(_e, "uid", c.UID); err != nil {
			return err
		}
	}
	for _idx := range c.Links {
		if err := _e.EncodeElement(&c.Links[_idx], xml.StartElement{Name: xml.Name{Local: "links"}}); err != nil {
			return err
		}
	}
	if c.ArchetypeDetails != nil {
		if err := _e.EncodeElement(c.ArchetypeDetails, xml.StartElement{Name: xml.Name{Local: "archetype_details"}}); err != nil {
			return err
		}
	}
	if c.FeederAudit != nil {
		if err := _e.EncodeElement(c.FeederAudit, xml.StartElement{Name: xml.Name{Local: "feeder_audit"}}); err != nil {
			return err
		}
	}
	if c.Credentials != nil {
		if err := canxml.EncodePoly(_e, "credentials", c.Credentials); err != nil {
			return err
		}
	}
	if c.TimeValidity != nil {
		if err := _e.EncodeElement(c.TimeValidity, xml.StartElement{Name: xml.Name{Local: "time_validity"}}); err != nil {
			return err
		}
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "CONTACT" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (c *Contact) BMMName() string { return "CONTACT" }

// MarshalXML emits canonical openEHR XML for Contact. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are appended to start.Attr before
// the start token is written.
func (c *Contact) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("CONTACT")}
	}
	_start.Attr = append(_start.Attr, xml.Attr{Name: xml.Name{Local: "archetype_node_id"}, Value: c.ArchetypeNodeID})
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if c.Name != nil {
		if err := canxml.EncodePoly(_e, "name", c.Name); err != nil {
			return err
		}
	}
	if c.UID != nil {
		if err := canxml.EncodePoly(_e, "uid", c.UID); err != nil {
			return err
		}
	}
	for _idx := range c.Links {
		if err := _e.EncodeElement(&c.Links[_idx], xml.StartElement{Name: xml.Name{Local: "links"}}); err != nil {
			return err
		}
	}
	if c.ArchetypeDetails != nil {
		if err := _e.EncodeElement(c.ArchetypeDetails, xml.StartElement{Name: xml.Name{Local: "archetype_details"}}); err != nil {
			return err
		}
	}
	if c.FeederAudit != nil {
		if err := _e.EncodeElement(c.FeederAudit, xml.StartElement{Name: xml.Name{Local: "feeder_audit"}}); err != nil {
			return err
		}
	}
	for _idx := range c.Addresses {
		if err := _e.EncodeElement(&c.Addresses[_idx], xml.StartElement{Name: xml.Name{Local: "addresses"}}); err != nil {
			return err
		}
	}
	if c.TimeValidity != nil {
		if err := _e.EncodeElement(c.TimeValidity, xml.StartElement{Name: xml.Name{Local: "time_validity"}}); err != nil {
			return err
		}
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "GROUP" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (g *Group) BMMName() string { return "GROUP" }

// MarshalXML emits canonical openEHR XML for Group. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are appended to start.Attr before
// the start token is written.
func (g *Group) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("GROUP")}
	}
	_start.Attr = append(_start.Attr, xml.Attr{Name: xml.Name{Local: "archetype_node_id"}, Value: g.ArchetypeNodeID})
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	for _, _item := range g.Languages {
		if _item == nil {
			continue
		}
		if err := canxml.EncodePoly(_e, "languages", _item); err != nil {
			return err
		}
	}
	for _idx := range g.Roles {
		if err := _e.EncodeElement(&g.Roles[_idx], xml.StartElement{Name: xml.Name{Local: "roles"}}); err != nil {
			return err
		}
	}
	for _idx := range g.Identities {
		if err := _e.EncodeElement(&g.Identities[_idx], xml.StartElement{Name: xml.Name{Local: "identities"}}); err != nil {
			return err
		}
	}
	for _idx := range g.Contacts {
		if err := _e.EncodeElement(&g.Contacts[_idx], xml.StartElement{Name: xml.Name{Local: "contacts"}}); err != nil {
			return err
		}
	}
	if g.Details != nil {
		if err := canxml.EncodePoly(_e, "details", g.Details); err != nil {
			return err
		}
	}
	for _idx := range g.Relationships {
		if err := _e.EncodeElement(&g.Relationships[_idx], xml.StartElement{Name: xml.Name{Local: "relationships"}}); err != nil {
			return err
		}
	}
	if g.Name != nil {
		if err := canxml.EncodePoly(_e, "name", g.Name); err != nil {
			return err
		}
	}
	if g.UID != nil {
		if err := canxml.EncodePoly(_e, "uid", g.UID); err != nil {
			return err
		}
	}
	for _idx := range g.Links {
		if err := _e.EncodeElement(&g.Links[_idx], xml.StartElement{Name: xml.Name{Local: "links"}}); err != nil {
			return err
		}
	}
	if g.ArchetypeDetails != nil {
		if err := _e.EncodeElement(g.ArchetypeDetails, xml.StartElement{Name: xml.Name{Local: "archetype_details"}}); err != nil {
			return err
		}
	}
	if g.FeederAudit != nil {
		if err := _e.EncodeElement(g.FeederAudit, xml.StartElement{Name: xml.Name{Local: "feeder_audit"}}); err != nil {
			return err
		}
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "ORGANISATION" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (o *Organisation) BMMName() string { return "ORGANISATION" }

// MarshalXML emits canonical openEHR XML for Organisation. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are appended to start.Attr before
// the start token is written.
func (o *Organisation) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("ORGANISATION")}
	}
	_start.Attr = append(_start.Attr, xml.Attr{Name: xml.Name{Local: "archetype_node_id"}, Value: o.ArchetypeNodeID})
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	for _, _item := range o.Languages {
		if _item == nil {
			continue
		}
		if err := canxml.EncodePoly(_e, "languages", _item); err != nil {
			return err
		}
	}
	for _idx := range o.Roles {
		if err := _e.EncodeElement(&o.Roles[_idx], xml.StartElement{Name: xml.Name{Local: "roles"}}); err != nil {
			return err
		}
	}
	for _idx := range o.Identities {
		if err := _e.EncodeElement(&o.Identities[_idx], xml.StartElement{Name: xml.Name{Local: "identities"}}); err != nil {
			return err
		}
	}
	for _idx := range o.Contacts {
		if err := _e.EncodeElement(&o.Contacts[_idx], xml.StartElement{Name: xml.Name{Local: "contacts"}}); err != nil {
			return err
		}
	}
	if o.Details != nil {
		if err := canxml.EncodePoly(_e, "details", o.Details); err != nil {
			return err
		}
	}
	for _idx := range o.Relationships {
		if err := _e.EncodeElement(&o.Relationships[_idx], xml.StartElement{Name: xml.Name{Local: "relationships"}}); err != nil {
			return err
		}
	}
	if o.Name != nil {
		if err := canxml.EncodePoly(_e, "name", o.Name); err != nil {
			return err
		}
	}
	if o.UID != nil {
		if err := canxml.EncodePoly(_e, "uid", o.UID); err != nil {
			return err
		}
	}
	for _idx := range o.Links {
		if err := _e.EncodeElement(&o.Links[_idx], xml.StartElement{Name: xml.Name{Local: "links"}}); err != nil {
			return err
		}
	}
	if o.ArchetypeDetails != nil {
		if err := _e.EncodeElement(o.ArchetypeDetails, xml.StartElement{Name: xml.Name{Local: "archetype_details"}}); err != nil {
			return err
		}
	}
	if o.FeederAudit != nil {
		if err := _e.EncodeElement(o.FeederAudit, xml.StartElement{Name: xml.Name{Local: "feeder_audit"}}); err != nil {
			return err
		}
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "PARTY_IDENTITY" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (p *PartyIdentity) BMMName() string { return "PARTY_IDENTITY" }

// MarshalXML emits canonical openEHR XML for PartyIdentity. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are appended to start.Attr before
// the start token is written.
func (p *PartyIdentity) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("PARTY_IDENTITY")}
	}
	_start.Attr = append(_start.Attr, xml.Attr{Name: xml.Name{Local: "archetype_node_id"}, Value: p.ArchetypeNodeID})
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if p.Name != nil {
		if err := canxml.EncodePoly(_e, "name", p.Name); err != nil {
			return err
		}
	}
	if p.UID != nil {
		if err := canxml.EncodePoly(_e, "uid", p.UID); err != nil {
			return err
		}
	}
	for _idx := range p.Links {
		if err := _e.EncodeElement(&p.Links[_idx], xml.StartElement{Name: xml.Name{Local: "links"}}); err != nil {
			return err
		}
	}
	if p.ArchetypeDetails != nil {
		if err := _e.EncodeElement(p.ArchetypeDetails, xml.StartElement{Name: xml.Name{Local: "archetype_details"}}); err != nil {
			return err
		}
	}
	if p.FeederAudit != nil {
		if err := _e.EncodeElement(p.FeederAudit, xml.StartElement{Name: xml.Name{Local: "feeder_audit"}}); err != nil {
			return err
		}
	}
	if p.Details != nil {
		if err := canxml.EncodePoly(_e, "details", p.Details); err != nil {
			return err
		}
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "PARTY_RELATIONSHIP" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (p *PartyRelationship) BMMName() string { return "PARTY_RELATIONSHIP" }

// MarshalXML emits canonical openEHR XML for PartyRelationship. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are appended to start.Attr before
// the start token is written.
func (p *PartyRelationship) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("PARTY_RELATIONSHIP")}
	}
	_start.Attr = append(_start.Attr, xml.Attr{Name: xml.Name{Local: "archetype_node_id"}, Value: p.ArchetypeNodeID})
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if p.Name != nil {
		if err := canxml.EncodePoly(_e, "name", p.Name); err != nil {
			return err
		}
	}
	if p.UID != nil {
		if err := canxml.EncodePoly(_e, "uid", p.UID); err != nil {
			return err
		}
	}
	for _idx := range p.Links {
		if err := _e.EncodeElement(&p.Links[_idx], xml.StartElement{Name: xml.Name{Local: "links"}}); err != nil {
			return err
		}
	}
	if p.ArchetypeDetails != nil {
		if err := _e.EncodeElement(p.ArchetypeDetails, xml.StartElement{Name: xml.Name{Local: "archetype_details"}}); err != nil {
			return err
		}
	}
	if p.FeederAudit != nil {
		if err := _e.EncodeElement(p.FeederAudit, xml.StartElement{Name: xml.Name{Local: "feeder_audit"}}); err != nil {
			return err
		}
	}
	if p.Details != nil {
		if err := canxml.EncodePoly(_e, "details", p.Details); err != nil {
			return err
		}
	}
	if err := _e.EncodeElement(&p.Target, xml.StartElement{Name: xml.Name{Local: "target"}}); err != nil {
		return err
	}
	if p.TimeValidity != nil {
		if err := _e.EncodeElement(p.TimeValidity, xml.StartElement{Name: xml.Name{Local: "time_validity"}}); err != nil {
			return err
		}
	}
	if err := _e.EncodeElement(&p.Source, xml.StartElement{Name: xml.Name{Local: "source"}}); err != nil {
		return err
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "PERSON" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (p *Person) BMMName() string { return "PERSON" }

// MarshalXML emits canonical openEHR XML for Person. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are appended to start.Attr before
// the start token is written.
func (p *Person) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("PERSON")}
	}
	_start.Attr = append(_start.Attr, xml.Attr{Name: xml.Name{Local: "archetype_node_id"}, Value: p.ArchetypeNodeID})
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	for _, _item := range p.Languages {
		if _item == nil {
			continue
		}
		if err := canxml.EncodePoly(_e, "languages", _item); err != nil {
			return err
		}
	}
	for _idx := range p.Roles {
		if err := _e.EncodeElement(&p.Roles[_idx], xml.StartElement{Name: xml.Name{Local: "roles"}}); err != nil {
			return err
		}
	}
	for _idx := range p.Identities {
		if err := _e.EncodeElement(&p.Identities[_idx], xml.StartElement{Name: xml.Name{Local: "identities"}}); err != nil {
			return err
		}
	}
	for _idx := range p.Contacts {
		if err := _e.EncodeElement(&p.Contacts[_idx], xml.StartElement{Name: xml.Name{Local: "contacts"}}); err != nil {
			return err
		}
	}
	if p.Details != nil {
		if err := canxml.EncodePoly(_e, "details", p.Details); err != nil {
			return err
		}
	}
	for _idx := range p.Relationships {
		if err := _e.EncodeElement(&p.Relationships[_idx], xml.StartElement{Name: xml.Name{Local: "relationships"}}); err != nil {
			return err
		}
	}
	if p.Name != nil {
		if err := canxml.EncodePoly(_e, "name", p.Name); err != nil {
			return err
		}
	}
	if p.UID != nil {
		if err := canxml.EncodePoly(_e, "uid", p.UID); err != nil {
			return err
		}
	}
	for _idx := range p.Links {
		if err := _e.EncodeElement(&p.Links[_idx], xml.StartElement{Name: xml.Name{Local: "links"}}); err != nil {
			return err
		}
	}
	if p.ArchetypeDetails != nil {
		if err := _e.EncodeElement(p.ArchetypeDetails, xml.StartElement{Name: xml.Name{Local: "archetype_details"}}); err != nil {
			return err
		}
	}
	if p.FeederAudit != nil {
		if err := _e.EncodeElement(p.FeederAudit, xml.StartElement{Name: xml.Name{Local: "feeder_audit"}}); err != nil {
			return err
		}
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "ROLE" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (r *Role) BMMName() string { return "ROLE" }

// MarshalXML emits canonical openEHR XML for Role. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are appended to start.Attr before
// the start token is written.
func (r *Role) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("ROLE")}
	}
	_start.Attr = append(_start.Attr, xml.Attr{Name: xml.Name{Local: "archetype_node_id"}, Value: r.ArchetypeNodeID})
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	for _idx := range r.Identities {
		if err := _e.EncodeElement(&r.Identities[_idx], xml.StartElement{Name: xml.Name{Local: "identities"}}); err != nil {
			return err
		}
	}
	for _idx := range r.Contacts {
		if err := _e.EncodeElement(&r.Contacts[_idx], xml.StartElement{Name: xml.Name{Local: "contacts"}}); err != nil {
			return err
		}
	}
	if r.Details != nil {
		if err := canxml.EncodePoly(_e, "details", r.Details); err != nil {
			return err
		}
	}
	for _idx := range r.Relationships {
		if err := _e.EncodeElement(&r.Relationships[_idx], xml.StartElement{Name: xml.Name{Local: "relationships"}}); err != nil {
			return err
		}
	}
	if r.Name != nil {
		if err := canxml.EncodePoly(_e, "name", r.Name); err != nil {
			return err
		}
	}
	if r.UID != nil {
		if err := canxml.EncodePoly(_e, "uid", r.UID); err != nil {
			return err
		}
	}
	for _idx := range r.Links {
		if err := _e.EncodeElement(&r.Links[_idx], xml.StartElement{Name: xml.Name{Local: "links"}}); err != nil {
			return err
		}
	}
	if r.ArchetypeDetails != nil {
		if err := _e.EncodeElement(r.ArchetypeDetails, xml.StartElement{Name: xml.Name{Local: "archetype_details"}}); err != nil {
			return err
		}
	}
	if r.FeederAudit != nil {
		if err := _e.EncodeElement(r.FeederAudit, xml.StartElement{Name: xml.Name{Local: "feeder_audit"}}); err != nil {
			return err
		}
	}
	if r.TimeValidity != nil {
		if err := _e.EncodeElement(r.TimeValidity, xml.StartElement{Name: xml.Name{Local: "time_validity"}}); err != nil {
			return err
		}
	}
	if err := _e.EncodeElement(&r.Performer, xml.StartElement{Name: xml.Name{Local: "performer"}}); err != nil {
		return err
	}
	for _idx := range r.Capabilities {
		if err := _e.EncodeElement(&r.Capabilities[_idx], xml.StartElement{Name: xml.Name{Local: "capabilities"}}); err != nil {
			return err
		}
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "VERSIONED_PARTY" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (v *VersionedParty) BMMName() string { return "VERSIONED_PARTY" }

// MarshalXML emits canonical openEHR XML for VersionedParty. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are appended to start.Attr before
// the start token is written.
func (v *VersionedParty) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("VERSIONED_PARTY")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeElement(&v.UID, xml.StartElement{Name: xml.Name{Local: "uid"}}); err != nil {
		return err
	}
	if v.OwnerID != nil {
		if err := canxml.EncodePoly(_e, "owner_id", v.OwnerID); err != nil {
			return err
		}
	}
	if err := _e.EncodeElement(&v.TimeCreated, xml.StartElement{Name: xml.Name{Local: "time_created"}}); err != nil {
		return err
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}
