// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/xml"
	"fmt"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
	"github.com/cadasto/openehr-sdk-go/openehr/serialize/canxml"
)

// BMM package: org.openehr.rm.demographic — canonical-XML UnmarshalXML companions

// UnmarshalXML decodes canonical openEHR XML into Address.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are read from _start.Attr.
func (a *Address) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for _, _a := range _start.Attr {
		if _a.Name.Local == "archetype_node_id" && _a.Name.Space == "" {
			a.ArchetypeNodeID = _a.Value
			break
		}
	}
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "name":
				_v, _err := DecodeDataValueTextXML(_dec, _t)
				if _err != nil {
					return _err
				}
				a.Name = _v
			case "archetype_node_id":
				if _err := _dec.DecodeElement(&a.ArchetypeNodeID, &_t); _err != nil {
					return _err
				}
			case "uid":
				_v, _err := canxml.DecodeAs[UIDBasedID](_dec, _t)
				if _err != nil {
					return _err
				}
				a.UID = _v
			case "links":
				var _v Link
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				a.Links = append(a.Links, _v)
			case "archetype_details":
				_v := new(Archetyped)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				a.ArchetypeDetails = _v
			case "feeder_audit":
				_v := new(FeederAudit)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				a.FeederAudit = _v
			case "details":
				_v, _err := canxml.DecodeAs[ItemStructure](_dec, _t)
				if _err != nil {
					return _err
				}
				a.Details = _v
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// UnmarshalXML decodes canonical openEHR XML into Agent.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are read from _start.Attr.
func (a *Agent) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for _, _a := range _start.Attr {
		if _a.Name.Local == "archetype_node_id" && _a.Name.Space == "" {
			a.ArchetypeNodeID = _a.Value
			break
		}
	}
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "languages":
				_v, _err := canxml.DecodeAs[DataValueText](_dec, _t)
				if _err != nil {
					return _err
				}
				a.Languages = append(a.Languages, _v)
			case "roles":
				var _v PartyRef
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				a.Roles = append(a.Roles, _v)
			case "identities":
				var _v PartyIdentity
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				a.Identities = append(a.Identities, _v)
			case "contacts":
				var _v Contact
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				a.Contacts = append(a.Contacts, _v)
			case "details":
				_v, _err := canxml.DecodeAs[ItemStructure](_dec, _t)
				if _err != nil {
					return _err
				}
				a.Details = _v
			case "relationships":
				var _v PartyRelationship
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				a.Relationships = append(a.Relationships, _v)
			case "name":
				_v, _err := DecodeDataValueTextXML(_dec, _t)
				if _err != nil {
					return _err
				}
				a.Name = _v
			case "archetype_node_id":
				if _err := _dec.DecodeElement(&a.ArchetypeNodeID, &_t); _err != nil {
					return _err
				}
			case "uid":
				_v, _err := canxml.DecodeAs[UIDBasedID](_dec, _t)
				if _err != nil {
					return _err
				}
				a.UID = _v
			case "links":
				var _v Link
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				a.Links = append(a.Links, _v)
			case "archetype_details":
				_v := new(Archetyped)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				a.ArchetypeDetails = _v
			case "feeder_audit":
				_v := new(FeederAudit)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				a.FeederAudit = _v
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// UnmarshalXML decodes canonical openEHR XML into Capability.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are read from _start.Attr.
func (c *Capability) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for _, _a := range _start.Attr {
		if _a.Name.Local == "archetype_node_id" && _a.Name.Space == "" {
			c.ArchetypeNodeID = _a.Value
			break
		}
	}
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "name":
				_v, _err := DecodeDataValueTextXML(_dec, _t)
				if _err != nil {
					return _err
				}
				c.Name = _v
			case "archetype_node_id":
				if _err := _dec.DecodeElement(&c.ArchetypeNodeID, &_t); _err != nil {
					return _err
				}
			case "uid":
				_v, _err := canxml.DecodeAs[UIDBasedID](_dec, _t)
				if _err != nil {
					return _err
				}
				c.UID = _v
			case "links":
				var _v Link
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				c.Links = append(c.Links, _v)
			case "archetype_details":
				_v := new(Archetyped)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				c.ArchetypeDetails = _v
			case "feeder_audit":
				_v := new(FeederAudit)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				c.FeederAudit = _v
			case "credentials":
				_v, _err := canxml.DecodeAs[ItemStructure](_dec, _t)
				if _err != nil {
					return _err
				}
				c.Credentials = _v
			case "time_validity":
				_v := new(DVInterval[DVDate])
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				c.TimeValidity = _v
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// UnmarshalXML decodes canonical openEHR XML into Contact.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are read from _start.Attr.
func (c *Contact) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for _, _a := range _start.Attr {
		if _a.Name.Local == "archetype_node_id" && _a.Name.Space == "" {
			c.ArchetypeNodeID = _a.Value
			break
		}
	}
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "name":
				_v, _err := DecodeDataValueTextXML(_dec, _t)
				if _err != nil {
					return _err
				}
				c.Name = _v
			case "archetype_node_id":
				if _err := _dec.DecodeElement(&c.ArchetypeNodeID, &_t); _err != nil {
					return _err
				}
			case "uid":
				_v, _err := canxml.DecodeAs[UIDBasedID](_dec, _t)
				if _err != nil {
					return _err
				}
				c.UID = _v
			case "links":
				var _v Link
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				c.Links = append(c.Links, _v)
			case "archetype_details":
				_v := new(Archetyped)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				c.ArchetypeDetails = _v
			case "feeder_audit":
				_v := new(FeederAudit)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				c.FeederAudit = _v
			case "addresses":
				var _v Address
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				c.Addresses = append(c.Addresses, _v)
			case "time_validity":
				_v := new(DVInterval[DVDate])
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				c.TimeValidity = _v
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// UnmarshalXML decodes canonical openEHR XML into Group.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are read from _start.Attr.
func (g *Group) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for _, _a := range _start.Attr {
		if _a.Name.Local == "archetype_node_id" && _a.Name.Space == "" {
			g.ArchetypeNodeID = _a.Value
			break
		}
	}
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "languages":
				_v, _err := canxml.DecodeAs[DataValueText](_dec, _t)
				if _err != nil {
					return _err
				}
				g.Languages = append(g.Languages, _v)
			case "roles":
				var _v PartyRef
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				g.Roles = append(g.Roles, _v)
			case "identities":
				var _v PartyIdentity
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				g.Identities = append(g.Identities, _v)
			case "contacts":
				var _v Contact
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				g.Contacts = append(g.Contacts, _v)
			case "details":
				_v, _err := canxml.DecodeAs[ItemStructure](_dec, _t)
				if _err != nil {
					return _err
				}
				g.Details = _v
			case "relationships":
				var _v PartyRelationship
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				g.Relationships = append(g.Relationships, _v)
			case "name":
				_v, _err := DecodeDataValueTextXML(_dec, _t)
				if _err != nil {
					return _err
				}
				g.Name = _v
			case "archetype_node_id":
				if _err := _dec.DecodeElement(&g.ArchetypeNodeID, &_t); _err != nil {
					return _err
				}
			case "uid":
				_v, _err := canxml.DecodeAs[UIDBasedID](_dec, _t)
				if _err != nil {
					return _err
				}
				g.UID = _v
			case "links":
				var _v Link
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				g.Links = append(g.Links, _v)
			case "archetype_details":
				_v := new(Archetyped)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				g.ArchetypeDetails = _v
			case "feeder_audit":
				_v := new(FeederAudit)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				g.FeederAudit = _v
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// UnmarshalXML decodes canonical openEHR XML into Organisation.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are read from _start.Attr.
func (o *Organisation) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for _, _a := range _start.Attr {
		if _a.Name.Local == "archetype_node_id" && _a.Name.Space == "" {
			o.ArchetypeNodeID = _a.Value
			break
		}
	}
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "languages":
				_v, _err := canxml.DecodeAs[DataValueText](_dec, _t)
				if _err != nil {
					return _err
				}
				o.Languages = append(o.Languages, _v)
			case "roles":
				var _v PartyRef
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				o.Roles = append(o.Roles, _v)
			case "identities":
				var _v PartyIdentity
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				o.Identities = append(o.Identities, _v)
			case "contacts":
				var _v Contact
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				o.Contacts = append(o.Contacts, _v)
			case "details":
				_v, _err := canxml.DecodeAs[ItemStructure](_dec, _t)
				if _err != nil {
					return _err
				}
				o.Details = _v
			case "relationships":
				var _v PartyRelationship
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				o.Relationships = append(o.Relationships, _v)
			case "name":
				_v, _err := DecodeDataValueTextXML(_dec, _t)
				if _err != nil {
					return _err
				}
				o.Name = _v
			case "archetype_node_id":
				if _err := _dec.DecodeElement(&o.ArchetypeNodeID, &_t); _err != nil {
					return _err
				}
			case "uid":
				_v, _err := canxml.DecodeAs[UIDBasedID](_dec, _t)
				if _err != nil {
					return _err
				}
				o.UID = _v
			case "links":
				var _v Link
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				o.Links = append(o.Links, _v)
			case "archetype_details":
				_v := new(Archetyped)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				o.ArchetypeDetails = _v
			case "feeder_audit":
				_v := new(FeederAudit)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				o.FeederAudit = _v
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// UnmarshalXML decodes canonical openEHR XML into PartyIdentity.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are read from _start.Attr.
func (p *PartyIdentity) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for _, _a := range _start.Attr {
		if _a.Name.Local == "archetype_node_id" && _a.Name.Space == "" {
			p.ArchetypeNodeID = _a.Value
			break
		}
	}
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "name":
				_v, _err := DecodeDataValueTextXML(_dec, _t)
				if _err != nil {
					return _err
				}
				p.Name = _v
			case "archetype_node_id":
				if _err := _dec.DecodeElement(&p.ArchetypeNodeID, &_t); _err != nil {
					return _err
				}
			case "uid":
				_v, _err := canxml.DecodeAs[UIDBasedID](_dec, _t)
				if _err != nil {
					return _err
				}
				p.UID = _v
			case "links":
				var _v Link
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				p.Links = append(p.Links, _v)
			case "archetype_details":
				_v := new(Archetyped)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				p.ArchetypeDetails = _v
			case "feeder_audit":
				_v := new(FeederAudit)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				p.FeederAudit = _v
			case "details":
				_v, _err := canxml.DecodeAs[ItemStructure](_dec, _t)
				if _err != nil {
					return _err
				}
				p.Details = _v
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// UnmarshalXML decodes canonical openEHR XML into PartyRelationship.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are read from _start.Attr.
func (p *PartyRelationship) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for _, _a := range _start.Attr {
		if _a.Name.Local == "archetype_node_id" && _a.Name.Space == "" {
			p.ArchetypeNodeID = _a.Value
			break
		}
	}
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "name":
				_v, _err := DecodeDataValueTextXML(_dec, _t)
				if _err != nil {
					return _err
				}
				p.Name = _v
			case "archetype_node_id":
				if _err := _dec.DecodeElement(&p.ArchetypeNodeID, &_t); _err != nil {
					return _err
				}
			case "uid":
				_v, _err := canxml.DecodeAs[UIDBasedID](_dec, _t)
				if _err != nil {
					return _err
				}
				p.UID = _v
			case "links":
				var _v Link
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				p.Links = append(p.Links, _v)
			case "archetype_details":
				_v := new(Archetyped)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				p.ArchetypeDetails = _v
			case "feeder_audit":
				_v := new(FeederAudit)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				p.FeederAudit = _v
			case "details":
				_v, _err := canxml.DecodeAs[ItemStructure](_dec, _t)
				if _err != nil {
					return _err
				}
				p.Details = _v
			case "target":
				if _err := _dec.DecodeElement(&p.Target, &_t); _err != nil {
					return _err
				}
			case "time_validity":
				_v := new(DVInterval[DVDate])
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				p.TimeValidity = _v
			case "source":
				if _err := _dec.DecodeElement(&p.Source, &_t); _err != nil {
					return _err
				}
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// UnmarshalXML decodes canonical openEHR XML into Person.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are read from _start.Attr.
func (p *Person) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for _, _a := range _start.Attr {
		if _a.Name.Local == "archetype_node_id" && _a.Name.Space == "" {
			p.ArchetypeNodeID = _a.Value
			break
		}
	}
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "languages":
				_v, _err := canxml.DecodeAs[DataValueText](_dec, _t)
				if _err != nil {
					return _err
				}
				p.Languages = append(p.Languages, _v)
			case "roles":
				var _v PartyRef
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				p.Roles = append(p.Roles, _v)
			case "identities":
				var _v PartyIdentity
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				p.Identities = append(p.Identities, _v)
			case "contacts":
				var _v Contact
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				p.Contacts = append(p.Contacts, _v)
			case "details":
				_v, _err := canxml.DecodeAs[ItemStructure](_dec, _t)
				if _err != nil {
					return _err
				}
				p.Details = _v
			case "relationships":
				var _v PartyRelationship
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				p.Relationships = append(p.Relationships, _v)
			case "name":
				_v, _err := DecodeDataValueTextXML(_dec, _t)
				if _err != nil {
					return _err
				}
				p.Name = _v
			case "archetype_node_id":
				if _err := _dec.DecodeElement(&p.ArchetypeNodeID, &_t); _err != nil {
					return _err
				}
			case "uid":
				_v, _err := canxml.DecodeAs[UIDBasedID](_dec, _t)
				if _err != nil {
					return _err
				}
				p.UID = _v
			case "links":
				var _v Link
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				p.Links = append(p.Links, _v)
			case "archetype_details":
				_v := new(Archetyped)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				p.ArchetypeDetails = _v
			case "feeder_audit":
				_v := new(FeederAudit)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				p.FeederAudit = _v
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// UnmarshalXML decodes canonical openEHR XML into Role.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are read from _start.Attr.
func (r *Role) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for _, _a := range _start.Attr {
		if _a.Name.Local == "archetype_node_id" && _a.Name.Space == "" {
			r.ArchetypeNodeID = _a.Value
			break
		}
	}
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "identities":
				var _v PartyIdentity
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				r.Identities = append(r.Identities, _v)
			case "contacts":
				var _v Contact
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				r.Contacts = append(r.Contacts, _v)
			case "details":
				_v, _err := canxml.DecodeAs[ItemStructure](_dec, _t)
				if _err != nil {
					return _err
				}
				r.Details = _v
			case "relationships":
				var _v PartyRelationship
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				r.Relationships = append(r.Relationships, _v)
			case "name":
				_v, _err := DecodeDataValueTextXML(_dec, _t)
				if _err != nil {
					return _err
				}
				r.Name = _v
			case "archetype_node_id":
				if _err := _dec.DecodeElement(&r.ArchetypeNodeID, &_t); _err != nil {
					return _err
				}
			case "uid":
				_v, _err := canxml.DecodeAs[UIDBasedID](_dec, _t)
				if _err != nil {
					return _err
				}
				r.UID = _v
			case "links":
				var _v Link
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				r.Links = append(r.Links, _v)
			case "archetype_details":
				_v := new(Archetyped)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				r.ArchetypeDetails = _v
			case "feeder_audit":
				_v := new(FeederAudit)
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				r.FeederAudit = _v
			case "time_validity":
				_v := new(DVInterval[DVDate])
				if _err := _dec.DecodeElement(_v, &_t); _err != nil {
					return _err
				}
				r.TimeValidity = _v
			case "performer":
				if _err := _dec.DecodeElement(&r.Performer, &_t); _err != nil {
					return _err
				}
			case "capabilities":
				var _v Capability
				if _err := _dec.DecodeElement(&_v, &_t); _err != nil {
					return _err
				}
				r.Capabilities = append(r.Capabilities, _v)
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

// UnmarshalXML decodes canonical openEHR XML into VersionedParty.
// Polymorphic fields are routed through canxml.DecodeAs so the
// concrete type is selected by `xsi:type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *canxml.DecodeError for errors.Is / errors.As.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are read from _start.Attr.
func (v *VersionedParty) UnmarshalXML(_dec *xml.Decoder, _start xml.StartElement) error {
	for {
		_tok, _err := _dec.Token()
		if _err != nil {
			return _err
		}
		switch _t := _tok.(type) {
		case xml.StartElement:
			switch _t.Name.Local {
			case "uid":
				if _err := _dec.DecodeElement(&v.UID, &_t); _err != nil {
					return _err
				}
			case "owner_id":
				if _err := _dec.DecodeElement(&v.OwnerID, &_t); _err != nil {
					return _err
				}
			case "time_created":
				if _err := _dec.DecodeElement(&v.TimeCreated, &_t); _err != nil {
					return _err
				}
			default:
				if _err := _dec.Skip(); _err != nil {
					return _err
				}
			}
		case xml.EndElement:
			return nil
		}
	}
}

var (
	_ = typereg.ErrMissingType
	_ = fmt.Sprintf
	_ = canxml.NSDefault
)
