// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/json"
	"fmt"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
)

// BMM package: org.openehr.rm.demographic — canonical-JSON UnmarshalJSON companions

type AddressJSONUnmarshaller struct {
	Class string          `json:"_type"`
	Name  json.RawMessage `json:"name"` // polymorphic DataValueText
	// ArchetypeNodeID Design-time archetype identifier of this node taken from its generating archetype; used to build archetype paths. Always in the form of an at-code, e.g.  `at0005`. This value enables a 'standardised' name for this node to be generated, by referring to the generating archetype local terminology.
	//
	// At an archetype root point, the value of this attribute is always the stringified form of the `_archetype_id_` found in the `_archetype_details_` object.
	ArchetypeNodeID string          `json:"archetype_node_id"`
	UID             json.RawMessage `json:"uid,omitempty"` // polymorphic UIDBasedID
	// Links Links to other archetyped structures (data whose root object inherits from `ARCHETYPED`, such as `ENTRY`, `SECTION` and so on). Links may be to structures in other compositions.
	Links []Link `json:"links,omitempty"`
	// ArchetypeDetails Details of archetyping used on this node.
	ArchetypeDetails *Archetyped `json:"archetype_details,omitempty"`
	// FeederAudit Audit trail from non-openEHR system of original commit of information forming the content of this node, or from a conversion gateway which has synthesised this node.
	FeederAudit *FeederAudit    `json:"feeder_audit,omitempty"`
	Details     json.RawMessage `json:"details"` // polymorphic ItemStructure
}

// UnmarshalJSON decodes canonical openEHR JSON into Address.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (a *Address) UnmarshalJSON(data []byte) error {
	var aux AddressJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: ADDRESS: %w", err)
	}
	if aux.Class != "" && aux.Class != "ADDRESS" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "ADDRESS", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	if len(aux.Name) > 0 && string(aux.Name) != "null" {
		dv, err := DecodeDataValueText(aux.Name)
		if err != nil {
			return &typereg.DecodeError{Path: "/name", Inner: err}
		}
		a.Name = dv
	}
	a.ArchetypeNodeID = aux.ArchetypeNodeID
	if len(aux.UID) > 0 && string(aux.UID) != "null" {
		dv, err := typereg.DecodeAs[UIDBasedID](aux.UID)
		if err != nil {
			return &typereg.DecodeError{Path: "/uid", Inner: err}
		}
		a.UID = dv
	}
	a.Links = aux.Links
	a.ArchetypeDetails = aux.ArchetypeDetails
	a.FeederAudit = aux.FeederAudit
	if len(aux.Details) > 0 && string(aux.Details) != "null" {
		dv, err := typereg.DecodeAs[ItemStructure](aux.Details)
		if err != nil {
			return &typereg.DecodeError{Path: "/details", Inner: err}
		}
		a.Details = dv
	}
	return nil
}

type AgentJSONUnmarshaller struct {
	Class     string            `json:"_type"`
	Languages []json.RawMessage `json:"languages,omitempty"` // polymorphic []DataValueText
	// Roles Identifiers of the Version container for each Role played by this Party.
	Roles []PartyRef `json:"roles,omitempty"`
	// Identities Identities used by the party to identify itself, such as legal name, stage names, aliases, nicknames and so on.
	Identities []PartyIdentity `json:"identities"`
	// Contacts Contacts for this party.
	Contacts []Contact       `json:"contacts,omitempty"`
	Details  json.RawMessage `json:"details,omitempty"` // polymorphic ItemStructure
	// Relationships Relationships in which this Party takes part as source.
	Relationships []PartyRelationship `json:"relationships,omitempty"`
	Name          json.RawMessage     `json:"name"` // polymorphic DataValueText
	// ArchetypeNodeID Design-time archetype identifier of this node taken from its generating archetype; used to build archetype paths. Always in the form of an at-code, e.g.  `at0005`. This value enables a 'standardised' name for this node to be generated, by referring to the generating archetype local terminology.
	//
	// At an archetype root point, the value of this attribute is always the stringified form of the `_archetype_id_` found in the `_archetype_details_` object.
	ArchetypeNodeID string          `json:"archetype_node_id"`
	UID             json.RawMessage `json:"uid,omitempty"` // polymorphic UIDBasedID
	// Links Links to other archetyped structures (data whose root object inherits from `ARCHETYPED`, such as `ENTRY`, `SECTION` and so on). Links may be to structures in other compositions.
	Links []Link `json:"links,omitempty"`
	// ArchetypeDetails Details of archetyping used on this node.
	ArchetypeDetails *Archetyped `json:"archetype_details,omitempty"`
	// FeederAudit Audit trail from non-openEHR system of original commit of information forming the content of this node, or from a conversion gateway which has synthesised this node.
	FeederAudit *FeederAudit `json:"feeder_audit,omitempty"`
}

// UnmarshalJSON decodes canonical openEHR JSON into Agent.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (a *Agent) UnmarshalJSON(data []byte) error {
	var aux AgentJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: AGENT: %w", err)
	}
	if aux.Class != "" && aux.Class != "AGENT" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "AGENT", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	if aux.Languages != nil {
		a.Languages = make([]DataValueText, len(aux.Languages))
		for idx, raw := range aux.Languages {
			if len(raw) == 0 || string(raw) == "null" {
				continue
			}
			dv, err := typereg.DecodeAs[DataValueText](raw)
			if err != nil {
				return &typereg.DecodeError{Path: fmt.Sprintf("/languages/%d", idx), Inner: err}
			}
			a.Languages[idx] = dv
		}
	}
	a.Roles = aux.Roles
	a.Identities = aux.Identities
	a.Contacts = aux.Contacts
	if len(aux.Details) > 0 && string(aux.Details) != "null" {
		dv, err := typereg.DecodeAs[ItemStructure](aux.Details)
		if err != nil {
			return &typereg.DecodeError{Path: "/details", Inner: err}
		}
		a.Details = dv
	}
	a.Relationships = aux.Relationships
	if len(aux.Name) > 0 && string(aux.Name) != "null" {
		dv, err := DecodeDataValueText(aux.Name)
		if err != nil {
			return &typereg.DecodeError{Path: "/name", Inner: err}
		}
		a.Name = dv
	}
	a.ArchetypeNodeID = aux.ArchetypeNodeID
	if len(aux.UID) > 0 && string(aux.UID) != "null" {
		dv, err := typereg.DecodeAs[UIDBasedID](aux.UID)
		if err != nil {
			return &typereg.DecodeError{Path: "/uid", Inner: err}
		}
		a.UID = dv
	}
	a.Links = aux.Links
	a.ArchetypeDetails = aux.ArchetypeDetails
	a.FeederAudit = aux.FeederAudit
	return nil
}

type CapabilityJSONUnmarshaller struct {
	Class string          `json:"_type"`
	Name  json.RawMessage `json:"name"` // polymorphic DataValueText
	// ArchetypeNodeID Design-time archetype identifier of this node taken from its generating archetype; used to build archetype paths. Always in the form of an at-code, e.g.  `at0005`. This value enables a 'standardised' name for this node to be generated, by referring to the generating archetype local terminology.
	//
	// At an archetype root point, the value of this attribute is always the stringified form of the `_archetype_id_` found in the `_archetype_details_` object.
	ArchetypeNodeID string          `json:"archetype_node_id"`
	UID             json.RawMessage `json:"uid,omitempty"` // polymorphic UIDBasedID
	// Links Links to other archetyped structures (data whose root object inherits from `ARCHETYPED`, such as `ENTRY`, `SECTION` and so on). Links may be to structures in other compositions.
	Links []Link `json:"links,omitempty"`
	// ArchetypeDetails Details of archetyping used on this node.
	ArchetypeDetails *Archetyped `json:"archetype_details,omitempty"`
	// FeederAudit Audit trail from non-openEHR system of original commit of information forming the content of this node, or from a conversion gateway which has synthesised this node.
	FeederAudit *FeederAudit    `json:"feeder_audit,omitempty"`
	Credentials json.RawMessage `json:"credentials"` // polymorphic ItemStructure
	// TimeValidity Valid time interval for the credentials of this capability.
	TimeValidity *DVInterval[DVDate] `json:"time_validity,omitempty"`
}

// UnmarshalJSON decodes canonical openEHR JSON into Capability.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (c *Capability) UnmarshalJSON(data []byte) error {
	var aux CapabilityJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: CAPABILITY: %w", err)
	}
	if aux.Class != "" && aux.Class != "CAPABILITY" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "CAPABILITY", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	if len(aux.Name) > 0 && string(aux.Name) != "null" {
		dv, err := DecodeDataValueText(aux.Name)
		if err != nil {
			return &typereg.DecodeError{Path: "/name", Inner: err}
		}
		c.Name = dv
	}
	c.ArchetypeNodeID = aux.ArchetypeNodeID
	if len(aux.UID) > 0 && string(aux.UID) != "null" {
		dv, err := typereg.DecodeAs[UIDBasedID](aux.UID)
		if err != nil {
			return &typereg.DecodeError{Path: "/uid", Inner: err}
		}
		c.UID = dv
	}
	c.Links = aux.Links
	c.ArchetypeDetails = aux.ArchetypeDetails
	c.FeederAudit = aux.FeederAudit
	if len(aux.Credentials) > 0 && string(aux.Credentials) != "null" {
		dv, err := typereg.DecodeAs[ItemStructure](aux.Credentials)
		if err != nil {
			return &typereg.DecodeError{Path: "/credentials", Inner: err}
		}
		c.Credentials = dv
	}
	c.TimeValidity = aux.TimeValidity
	return nil
}

type ContactJSONUnmarshaller struct {
	Class string          `json:"_type"`
	Name  json.RawMessage `json:"name"` // polymorphic DataValueText
	// ArchetypeNodeID Design-time archetype identifier of this node taken from its generating archetype; used to build archetype paths. Always in the form of an at-code, e.g.  `at0005`. This value enables a 'standardised' name for this node to be generated, by referring to the generating archetype local terminology.
	//
	// At an archetype root point, the value of this attribute is always the stringified form of the `_archetype_id_` found in the `_archetype_details_` object.
	ArchetypeNodeID string          `json:"archetype_node_id"`
	UID             json.RawMessage `json:"uid,omitempty"` // polymorphic UIDBasedID
	// Links Links to other archetyped structures (data whose root object inherits from `ARCHETYPED`, such as `ENTRY`, `SECTION` and so on). Links may be to structures in other compositions.
	Links []Link `json:"links,omitempty"`
	// ArchetypeDetails Details of archetyping used on this node.
	ArchetypeDetails *Archetyped `json:"archetype_details,omitempty"`
	// FeederAudit Audit trail from non-openEHR system of original commit of information forming the content of this node, or from a conversion gateway which has synthesised this node.
	FeederAudit *FeederAudit `json:"feeder_audit,omitempty"`
	// Addresses A set of address alternatives for this contact purpose and time validity combination.
	Addresses []Address `json:"addresses"`
	// TimeValidity Valid time interval for this contact descriptor.
	TimeValidity *DVInterval[DVDate] `json:"time_validity,omitempty"`
}

// UnmarshalJSON decodes canonical openEHR JSON into Contact.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (c *Contact) UnmarshalJSON(data []byte) error {
	var aux ContactJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: CONTACT: %w", err)
	}
	if aux.Class != "" && aux.Class != "CONTACT" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "CONTACT", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	if len(aux.Name) > 0 && string(aux.Name) != "null" {
		dv, err := DecodeDataValueText(aux.Name)
		if err != nil {
			return &typereg.DecodeError{Path: "/name", Inner: err}
		}
		c.Name = dv
	}
	c.ArchetypeNodeID = aux.ArchetypeNodeID
	if len(aux.UID) > 0 && string(aux.UID) != "null" {
		dv, err := typereg.DecodeAs[UIDBasedID](aux.UID)
		if err != nil {
			return &typereg.DecodeError{Path: "/uid", Inner: err}
		}
		c.UID = dv
	}
	c.Links = aux.Links
	c.ArchetypeDetails = aux.ArchetypeDetails
	c.FeederAudit = aux.FeederAudit
	c.Addresses = aux.Addresses
	c.TimeValidity = aux.TimeValidity
	return nil
}

type GroupJSONUnmarshaller struct {
	Class     string            `json:"_type"`
	Languages []json.RawMessage `json:"languages,omitempty"` // polymorphic []DataValueText
	// Roles Identifiers of the Version container for each Role played by this Party.
	Roles []PartyRef `json:"roles,omitempty"`
	// Identities Identities used by the party to identify itself, such as legal name, stage names, aliases, nicknames and so on.
	Identities []PartyIdentity `json:"identities"`
	// Contacts Contacts for this party.
	Contacts []Contact       `json:"contacts,omitempty"`
	Details  json.RawMessage `json:"details,omitempty"` // polymorphic ItemStructure
	// Relationships Relationships in which this Party takes part as source.
	Relationships []PartyRelationship `json:"relationships,omitempty"`
	Name          json.RawMessage     `json:"name"` // polymorphic DataValueText
	// ArchetypeNodeID Design-time archetype identifier of this node taken from its generating archetype; used to build archetype paths. Always in the form of an at-code, e.g.  `at0005`. This value enables a 'standardised' name for this node to be generated, by referring to the generating archetype local terminology.
	//
	// At an archetype root point, the value of this attribute is always the stringified form of the `_archetype_id_` found in the `_archetype_details_` object.
	ArchetypeNodeID string          `json:"archetype_node_id"`
	UID             json.RawMessage `json:"uid,omitempty"` // polymorphic UIDBasedID
	// Links Links to other archetyped structures (data whose root object inherits from `ARCHETYPED`, such as `ENTRY`, `SECTION` and so on). Links may be to structures in other compositions.
	Links []Link `json:"links,omitempty"`
	// ArchetypeDetails Details of archetyping used on this node.
	ArchetypeDetails *Archetyped `json:"archetype_details,omitempty"`
	// FeederAudit Audit trail from non-openEHR system of original commit of information forming the content of this node, or from a conversion gateway which has synthesised this node.
	FeederAudit *FeederAudit `json:"feeder_audit,omitempty"`
}

// UnmarshalJSON decodes canonical openEHR JSON into Group.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (g *Group) UnmarshalJSON(data []byte) error {
	var aux GroupJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: GROUP: %w", err)
	}
	if aux.Class != "" && aux.Class != "GROUP" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "GROUP", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	if aux.Languages != nil {
		g.Languages = make([]DataValueText, len(aux.Languages))
		for idx, raw := range aux.Languages {
			if len(raw) == 0 || string(raw) == "null" {
				continue
			}
			dv, err := typereg.DecodeAs[DataValueText](raw)
			if err != nil {
				return &typereg.DecodeError{Path: fmt.Sprintf("/languages/%d", idx), Inner: err}
			}
			g.Languages[idx] = dv
		}
	}
	g.Roles = aux.Roles
	g.Identities = aux.Identities
	g.Contacts = aux.Contacts
	if len(aux.Details) > 0 && string(aux.Details) != "null" {
		dv, err := typereg.DecodeAs[ItemStructure](aux.Details)
		if err != nil {
			return &typereg.DecodeError{Path: "/details", Inner: err}
		}
		g.Details = dv
	}
	g.Relationships = aux.Relationships
	if len(aux.Name) > 0 && string(aux.Name) != "null" {
		dv, err := DecodeDataValueText(aux.Name)
		if err != nil {
			return &typereg.DecodeError{Path: "/name", Inner: err}
		}
		g.Name = dv
	}
	g.ArchetypeNodeID = aux.ArchetypeNodeID
	if len(aux.UID) > 0 && string(aux.UID) != "null" {
		dv, err := typereg.DecodeAs[UIDBasedID](aux.UID)
		if err != nil {
			return &typereg.DecodeError{Path: "/uid", Inner: err}
		}
		g.UID = dv
	}
	g.Links = aux.Links
	g.ArchetypeDetails = aux.ArchetypeDetails
	g.FeederAudit = aux.FeederAudit
	return nil
}

type OrganisationJSONUnmarshaller struct {
	Class     string            `json:"_type"`
	Languages []json.RawMessage `json:"languages,omitempty"` // polymorphic []DataValueText
	// Roles Identifiers of the Version container for each Role played by this Party.
	Roles []PartyRef `json:"roles,omitempty"`
	// Identities Identities used by the party to identify itself, such as legal name, stage names, aliases, nicknames and so on.
	Identities []PartyIdentity `json:"identities"`
	// Contacts Contacts for this party.
	Contacts []Contact       `json:"contacts,omitempty"`
	Details  json.RawMessage `json:"details,omitempty"` // polymorphic ItemStructure
	// Relationships Relationships in which this Party takes part as source.
	Relationships []PartyRelationship `json:"relationships,omitempty"`
	Name          json.RawMessage     `json:"name"` // polymorphic DataValueText
	// ArchetypeNodeID Design-time archetype identifier of this node taken from its generating archetype; used to build archetype paths. Always in the form of an at-code, e.g.  `at0005`. This value enables a 'standardised' name for this node to be generated, by referring to the generating archetype local terminology.
	//
	// At an archetype root point, the value of this attribute is always the stringified form of the `_archetype_id_` found in the `_archetype_details_` object.
	ArchetypeNodeID string          `json:"archetype_node_id"`
	UID             json.RawMessage `json:"uid,omitempty"` // polymorphic UIDBasedID
	// Links Links to other archetyped structures (data whose root object inherits from `ARCHETYPED`, such as `ENTRY`, `SECTION` and so on). Links may be to structures in other compositions.
	Links []Link `json:"links,omitempty"`
	// ArchetypeDetails Details of archetyping used on this node.
	ArchetypeDetails *Archetyped `json:"archetype_details,omitempty"`
	// FeederAudit Audit trail from non-openEHR system of original commit of information forming the content of this node, or from a conversion gateway which has synthesised this node.
	FeederAudit *FeederAudit `json:"feeder_audit,omitempty"`
}

// UnmarshalJSON decodes canonical openEHR JSON into Organisation.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (o *Organisation) UnmarshalJSON(data []byte) error {
	var aux OrganisationJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: ORGANISATION: %w", err)
	}
	if aux.Class != "" && aux.Class != "ORGANISATION" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "ORGANISATION", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	if aux.Languages != nil {
		o.Languages = make([]DataValueText, len(aux.Languages))
		for idx, raw := range aux.Languages {
			if len(raw) == 0 || string(raw) == "null" {
				continue
			}
			dv, err := typereg.DecodeAs[DataValueText](raw)
			if err != nil {
				return &typereg.DecodeError{Path: fmt.Sprintf("/languages/%d", idx), Inner: err}
			}
			o.Languages[idx] = dv
		}
	}
	o.Roles = aux.Roles
	o.Identities = aux.Identities
	o.Contacts = aux.Contacts
	if len(aux.Details) > 0 && string(aux.Details) != "null" {
		dv, err := typereg.DecodeAs[ItemStructure](aux.Details)
		if err != nil {
			return &typereg.DecodeError{Path: "/details", Inner: err}
		}
		o.Details = dv
	}
	o.Relationships = aux.Relationships
	if len(aux.Name) > 0 && string(aux.Name) != "null" {
		dv, err := DecodeDataValueText(aux.Name)
		if err != nil {
			return &typereg.DecodeError{Path: "/name", Inner: err}
		}
		o.Name = dv
	}
	o.ArchetypeNodeID = aux.ArchetypeNodeID
	if len(aux.UID) > 0 && string(aux.UID) != "null" {
		dv, err := typereg.DecodeAs[UIDBasedID](aux.UID)
		if err != nil {
			return &typereg.DecodeError{Path: "/uid", Inner: err}
		}
		o.UID = dv
	}
	o.Links = aux.Links
	o.ArchetypeDetails = aux.ArchetypeDetails
	o.FeederAudit = aux.FeederAudit
	return nil
}

type PartyIdentityJSONUnmarshaller struct {
	Class string          `json:"_type"`
	Name  json.RawMessage `json:"name"` // polymorphic DataValueText
	// ArchetypeNodeID Design-time archetype identifier of this node taken from its generating archetype; used to build archetype paths. Always in the form of an at-code, e.g.  `at0005`. This value enables a 'standardised' name for this node to be generated, by referring to the generating archetype local terminology.
	//
	// At an archetype root point, the value of this attribute is always the stringified form of the `_archetype_id_` found in the `_archetype_details_` object.
	ArchetypeNodeID string          `json:"archetype_node_id"`
	UID             json.RawMessage `json:"uid,omitempty"` // polymorphic UIDBasedID
	// Links Links to other archetyped structures (data whose root object inherits from `ARCHETYPED`, such as `ENTRY`, `SECTION` and so on). Links may be to structures in other compositions.
	Links []Link `json:"links,omitempty"`
	// ArchetypeDetails Details of archetyping used on this node.
	ArchetypeDetails *Archetyped `json:"archetype_details,omitempty"`
	// FeederAudit Audit trail from non-openEHR system of original commit of information forming the content of this node, or from a conversion gateway which has synthesised this node.
	FeederAudit *FeederAudit    `json:"feeder_audit,omitempty"`
	Details     json.RawMessage `json:"details"` // polymorphic ItemStructure
}

// UnmarshalJSON decodes canonical openEHR JSON into PartyIdentity.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (p *PartyIdentity) UnmarshalJSON(data []byte) error {
	var aux PartyIdentityJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: PARTY_IDENTITY: %w", err)
	}
	if aux.Class != "" && aux.Class != "PARTY_IDENTITY" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "PARTY_IDENTITY", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	if len(aux.Name) > 0 && string(aux.Name) != "null" {
		dv, err := DecodeDataValueText(aux.Name)
		if err != nil {
			return &typereg.DecodeError{Path: "/name", Inner: err}
		}
		p.Name = dv
	}
	p.ArchetypeNodeID = aux.ArchetypeNodeID
	if len(aux.UID) > 0 && string(aux.UID) != "null" {
		dv, err := typereg.DecodeAs[UIDBasedID](aux.UID)
		if err != nil {
			return &typereg.DecodeError{Path: "/uid", Inner: err}
		}
		p.UID = dv
	}
	p.Links = aux.Links
	p.ArchetypeDetails = aux.ArchetypeDetails
	p.FeederAudit = aux.FeederAudit
	if len(aux.Details) > 0 && string(aux.Details) != "null" {
		dv, err := typereg.DecodeAs[ItemStructure](aux.Details)
		if err != nil {
			return &typereg.DecodeError{Path: "/details", Inner: err}
		}
		p.Details = dv
	}
	return nil
}

type PartyRelationshipJSONUnmarshaller struct {
	Class string          `json:"_type"`
	Name  json.RawMessage `json:"name"` // polymorphic DataValueText
	// ArchetypeNodeID Design-time archetype identifier of this node taken from its generating archetype; used to build archetype paths. Always in the form of an at-code, e.g.  `at0005`. This value enables a 'standardised' name for this node to be generated, by referring to the generating archetype local terminology.
	//
	// At an archetype root point, the value of this attribute is always the stringified form of the `_archetype_id_` found in the `_archetype_details_` object.
	ArchetypeNodeID string          `json:"archetype_node_id"`
	UID             json.RawMessage `json:"uid,omitempty"` // polymorphic UIDBasedID
	// Links Links to other archetyped structures (data whose root object inherits from `ARCHETYPED`, such as `ENTRY`, `SECTION` and so on). Links may be to structures in other compositions.
	Links []Link `json:"links,omitempty"`
	// ArchetypeDetails Details of archetyping used on this node.
	ArchetypeDetails *Archetyped `json:"archetype_details,omitempty"`
	// FeederAudit Audit trail from non-openEHR system of original commit of information forming the content of this node, or from a conversion gateway which has synthesised this node.
	FeederAudit *FeederAudit    `json:"feeder_audit,omitempty"`
	Details     json.RawMessage `json:"details,omitempty"` // polymorphic ItemStructure
	// Target Target of relationship.
	Target PartyRef `json:"target"`
	// TimeValidity Valid time interval for this relationship.
	TimeValidity *DVInterval[DVDate] `json:"time_validity,omitempty"`
	// Source Source of relationship.
	Source PartyRef `json:"source"`
}

// UnmarshalJSON decodes canonical openEHR JSON into PartyRelationship.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (p *PartyRelationship) UnmarshalJSON(data []byte) error {
	var aux PartyRelationshipJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: PARTY_RELATIONSHIP: %w", err)
	}
	if aux.Class != "" && aux.Class != "PARTY_RELATIONSHIP" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "PARTY_RELATIONSHIP", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	if len(aux.Name) > 0 && string(aux.Name) != "null" {
		dv, err := DecodeDataValueText(aux.Name)
		if err != nil {
			return &typereg.DecodeError{Path: "/name", Inner: err}
		}
		p.Name = dv
	}
	p.ArchetypeNodeID = aux.ArchetypeNodeID
	if len(aux.UID) > 0 && string(aux.UID) != "null" {
		dv, err := typereg.DecodeAs[UIDBasedID](aux.UID)
		if err != nil {
			return &typereg.DecodeError{Path: "/uid", Inner: err}
		}
		p.UID = dv
	}
	p.Links = aux.Links
	p.ArchetypeDetails = aux.ArchetypeDetails
	p.FeederAudit = aux.FeederAudit
	if len(aux.Details) > 0 && string(aux.Details) != "null" {
		dv, err := typereg.DecodeAs[ItemStructure](aux.Details)
		if err != nil {
			return &typereg.DecodeError{Path: "/details", Inner: err}
		}
		p.Details = dv
	}
	p.Target = aux.Target
	p.TimeValidity = aux.TimeValidity
	p.Source = aux.Source
	return nil
}

type PersonJSONUnmarshaller struct {
	Class     string            `json:"_type"`
	Languages []json.RawMessage `json:"languages,omitempty"` // polymorphic []DataValueText
	// Roles Identifiers of the Version container for each Role played by this Party.
	Roles []PartyRef `json:"roles,omitempty"`
	// Identities Identities used by the party to identify itself, such as legal name, stage names, aliases, nicknames and so on.
	Identities []PartyIdentity `json:"identities"`
	// Contacts Contacts for this party.
	Contacts []Contact       `json:"contacts,omitempty"`
	Details  json.RawMessage `json:"details,omitempty"` // polymorphic ItemStructure
	// Relationships Relationships in which this Party takes part as source.
	Relationships []PartyRelationship `json:"relationships,omitempty"`
	Name          json.RawMessage     `json:"name"` // polymorphic DataValueText
	// ArchetypeNodeID Design-time archetype identifier of this node taken from its generating archetype; used to build archetype paths. Always in the form of an at-code, e.g.  `at0005`. This value enables a 'standardised' name for this node to be generated, by referring to the generating archetype local terminology.
	//
	// At an archetype root point, the value of this attribute is always the stringified form of the `_archetype_id_` found in the `_archetype_details_` object.
	ArchetypeNodeID string          `json:"archetype_node_id"`
	UID             json.RawMessage `json:"uid,omitempty"` // polymorphic UIDBasedID
	// Links Links to other archetyped structures (data whose root object inherits from `ARCHETYPED`, such as `ENTRY`, `SECTION` and so on). Links may be to structures in other compositions.
	Links []Link `json:"links,omitempty"`
	// ArchetypeDetails Details of archetyping used on this node.
	ArchetypeDetails *Archetyped `json:"archetype_details,omitempty"`
	// FeederAudit Audit trail from non-openEHR system of original commit of information forming the content of this node, or from a conversion gateway which has synthesised this node.
	FeederAudit *FeederAudit `json:"feeder_audit,omitempty"`
}

// UnmarshalJSON decodes canonical openEHR JSON into Person.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (p *Person) UnmarshalJSON(data []byte) error {
	var aux PersonJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: PERSON: %w", err)
	}
	if aux.Class != "" && aux.Class != "PERSON" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "PERSON", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	if aux.Languages != nil {
		p.Languages = make([]DataValueText, len(aux.Languages))
		for idx, raw := range aux.Languages {
			if len(raw) == 0 || string(raw) == "null" {
				continue
			}
			dv, err := typereg.DecodeAs[DataValueText](raw)
			if err != nil {
				return &typereg.DecodeError{Path: fmt.Sprintf("/languages/%d", idx), Inner: err}
			}
			p.Languages[idx] = dv
		}
	}
	p.Roles = aux.Roles
	p.Identities = aux.Identities
	p.Contacts = aux.Contacts
	if len(aux.Details) > 0 && string(aux.Details) != "null" {
		dv, err := typereg.DecodeAs[ItemStructure](aux.Details)
		if err != nil {
			return &typereg.DecodeError{Path: "/details", Inner: err}
		}
		p.Details = dv
	}
	p.Relationships = aux.Relationships
	if len(aux.Name) > 0 && string(aux.Name) != "null" {
		dv, err := DecodeDataValueText(aux.Name)
		if err != nil {
			return &typereg.DecodeError{Path: "/name", Inner: err}
		}
		p.Name = dv
	}
	p.ArchetypeNodeID = aux.ArchetypeNodeID
	if len(aux.UID) > 0 && string(aux.UID) != "null" {
		dv, err := typereg.DecodeAs[UIDBasedID](aux.UID)
		if err != nil {
			return &typereg.DecodeError{Path: "/uid", Inner: err}
		}
		p.UID = dv
	}
	p.Links = aux.Links
	p.ArchetypeDetails = aux.ArchetypeDetails
	p.FeederAudit = aux.FeederAudit
	return nil
}

type RoleJSONUnmarshaller struct {
	Class string `json:"_type"`
	// Identities Identities used by the party to identify itself, such as legal name, stage names, aliases, nicknames and so on.
	Identities []PartyIdentity `json:"identities"`
	// Contacts Contacts for this party.
	Contacts []Contact       `json:"contacts,omitempty"`
	Details  json.RawMessage `json:"details,omitempty"` // polymorphic ItemStructure
	// Relationships Relationships in which this Party takes part as source.
	Relationships []PartyRelationship `json:"relationships,omitempty"`
	Name          json.RawMessage     `json:"name"` // polymorphic DataValueText
	// ArchetypeNodeID Design-time archetype identifier of this node taken from its generating archetype; used to build archetype paths. Always in the form of an at-code, e.g.  `at0005`. This value enables a 'standardised' name for this node to be generated, by referring to the generating archetype local terminology.
	//
	// At an archetype root point, the value of this attribute is always the stringified form of the `_archetype_id_` found in the `_archetype_details_` object.
	ArchetypeNodeID string          `json:"archetype_node_id"`
	UID             json.RawMessage `json:"uid,omitempty"` // polymorphic UIDBasedID
	// Links Links to other archetyped structures (data whose root object inherits from `ARCHETYPED`, such as `ENTRY`, `SECTION` and so on). Links may be to structures in other compositions.
	Links []Link `json:"links,omitempty"`
	// ArchetypeDetails Details of archetyping used on this node.
	ArchetypeDetails *Archetyped `json:"archetype_details,omitempty"`
	// FeederAudit Audit trail from non-openEHR system of original commit of information forming the content of this node, or from a conversion gateway which has synthesised this node.
	FeederAudit *FeederAudit `json:"feeder_audit,omitempty"`
	// TimeValidity Valid time interval for this role.
	TimeValidity *DVInterval[DVDate] `json:"time_validity,omitempty"`
	// Performer Reference to Version container of Actor playing the role.
	Performer PartyRef `json:"performer"`
	// Capabilities The capabilities of this role.
	Capabilities []Capability `json:"capabilities,omitempty"`
}

// UnmarshalJSON decodes canonical openEHR JSON into Role.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (r *Role) UnmarshalJSON(data []byte) error {
	var aux RoleJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: ROLE: %w", err)
	}
	if aux.Class != "" && aux.Class != "ROLE" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "ROLE", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	r.Identities = aux.Identities
	r.Contacts = aux.Contacts
	if len(aux.Details) > 0 && string(aux.Details) != "null" {
		dv, err := typereg.DecodeAs[ItemStructure](aux.Details)
		if err != nil {
			return &typereg.DecodeError{Path: "/details", Inner: err}
		}
		r.Details = dv
	}
	r.Relationships = aux.Relationships
	if len(aux.Name) > 0 && string(aux.Name) != "null" {
		dv, err := DecodeDataValueText(aux.Name)
		if err != nil {
			return &typereg.DecodeError{Path: "/name", Inner: err}
		}
		r.Name = dv
	}
	r.ArchetypeNodeID = aux.ArchetypeNodeID
	if len(aux.UID) > 0 && string(aux.UID) != "null" {
		dv, err := typereg.DecodeAs[UIDBasedID](aux.UID)
		if err != nil {
			return &typereg.DecodeError{Path: "/uid", Inner: err}
		}
		r.UID = dv
	}
	r.Links = aux.Links
	r.ArchetypeDetails = aux.ArchetypeDetails
	r.FeederAudit = aux.FeederAudit
	r.TimeValidity = aux.TimeValidity
	r.Performer = aux.Performer
	r.Capabilities = aux.Capabilities
	return nil
}

type VersionedPartyJSONUnmarshaller struct {
	Class string `json:"_type"`
	// UID Unique identifier of this version container in the form of a UID with no extension. This id will be the same in all instances of the same container in a distributed environment, meaning that it can be understood as the uid of the  virtual version tree.
	UID HierObjectID `json:"uid"`
	// OwnerID Reference to object to which this version container belongs, e.g. the id of the containing EHR or other relevant owning entity.
	OwnerID ObjectRef `json:"owner_id"`
	// TimeCreated Time of initial creation of this versioned object.
	TimeCreated DVDateTime `json:"time_created"`
}

// UnmarshalJSON decodes canonical openEHR JSON into VersionedParty.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (v *VersionedParty) UnmarshalJSON(data []byte) error {
	var aux VersionedPartyJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: VERSIONED_PARTY: %w", err)
	}
	if aux.Class != "" && aux.Class != "VERSIONED_PARTY" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "VERSIONED_PARTY", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	v.UID = aux.UID
	v.OwnerID = aux.OwnerID
	v.TimeCreated = aux.TimeCreated
	return nil
}
