// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/json"
	"fmt"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
)

// BMM package: org.openehr.rm.ehr — canonical-JSON UnmarshalJSON companions

type EHRJSONUnmarshaller struct {
	Class string `json:"_type"`
	// SystemID The identifier of the logical EHR management system in which this EHR was created.
	SystemID HierObjectID `json:"system_id"`
	// EHRID The unique identifier of this EHR.
	//
	// NOTE: is is strongly recommended that a UUID always be used for this field.
	EHRID HierObjectID `json:"ehr_id"`
	// Contributions List of contributions causing changes to this EHR. Each contribution contains a list of versions, which may include references to any number of `VERSION` instances, i.e. items of type `VERSIONED_COMPOSITION` and `VERSIONED_FOLDER`.
	Contributions []ObjectRef `json:"contributions,omitempty"`
	// EHRStatus Reference to `EHR_STATUS` object for this EHR.
	EHRStatus ObjectRef `json:"ehr_status"`
	// EHRAccess Reference to `EHR_ACCESS` object for this EHR.
	EHRAccess ObjectRef `json:"ehr_access"`
	// Compositions Master list of all Versioned Composition references in this EHR.
	Compositions []ObjectRef `json:"compositions,omitempty"`
	// Directory Optional directory structure for this EHR. If present, this is a reference to the first member of `_folders_`.
	Directory *ObjectRef `json:"directory,omitempty"`
	// TimeCreated Time of creation of the EHR.
	TimeCreated DVDateTime `json:"time_created"`
	// Folders Optional additional Folder structures for this EHR. If set, the `_directory_` attribute refers to the first member.
	Folders []ObjectRef `json:"folders,omitempty"`
	// Tags Optional list of tags associated with this EHR. Tag `_target_` values can only be within the same EHR.
	Tags []ObjectRef `json:"tags,omitempty"`
}

// UnmarshalJSON decodes canonical openEHR JSON into EHR.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (e *EHR) UnmarshalJSON(data []byte) error {
	var aux EHRJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: EHR: %w", err)
	}
	if aux.Class != "" && aux.Class != "EHR" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "EHR", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	e.SystemID = aux.SystemID
	e.EHRID = aux.EHRID
	e.Contributions = aux.Contributions
	e.EHRStatus = aux.EHRStatus
	e.EHRAccess = aux.EHRAccess
	e.Compositions = aux.Compositions
	e.Directory = aux.Directory
	e.TimeCreated = aux.TimeCreated
	e.Folders = aux.Folders
	e.Tags = aux.Tags
	return nil
}

type EHRAccessJSONUnmarshaller struct {
	Class string          `json:"_type"`
	Name  json.RawMessage `json:"name"` // polymorphic DataValueText
	// ArchetypeNodeID Design-time archetype identifier of this node taken from its generating archetype; used to build archetype paths. Always in the form of an at-code, e.g.  `at0005`. This value enables a 'standardised' name for this node to be generated, by referring to the generating archetype local terminology.
	//
	// At an archetype root point, the value of this attribute is always the stringified form of the `_archetype_id_` found in the `_archetype_details_` object.
	ArchetypeNodeID string          `json:"archetype_node_id"`
	UID             json.RawMessage `json:"uid,omitempty"` // polymorphic UIDBasedID
	// Links Links to other archetyped structures (data whose root object inherits from `ARCHETYPED`, such as `ENTRY`, `SECTION` and so on). Links may be to structures in other compositions.
	Links []Link `json:"links,omitempty"`
	// ArchetypeDetails Details of archetyping used on this node.
	ArchetypeDetails *Archetyped `json:"archetype_details,omitempty"`
	// FeederAudit Audit trail from non-openEHR system of original commit of information forming the content of this node, or from a conversion gateway which has synthesised this node.
	FeederAudit *FeederAudit    `json:"feeder_audit,omitempty"`
	Settings    json.RawMessage `json:"settings,omitempty"` // polymorphic AccessControlSettings
}

// UnmarshalJSON decodes canonical openEHR JSON into EHRAccess.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (e *EHRAccess) UnmarshalJSON(data []byte) error {
	var aux EHRAccessJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: EHR_ACCESS: %w", err)
	}
	if aux.Class != "" && aux.Class != "EHR_ACCESS" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "EHR_ACCESS", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	if len(aux.Name) > 0 && string(aux.Name) != "null" {
		dv, err := DecodeDataValueText(aux.Name)
		if err != nil {
			return &typereg.DecodeError{Path: "/name", Inner: err}
		}
		e.Name = dv
	}
	e.ArchetypeNodeID = aux.ArchetypeNodeID
	if len(aux.UID) > 0 && string(aux.UID) != "null" {
		dv, err := typereg.DecodeAs[UIDBasedID](aux.UID)
		if err != nil {
			return &typereg.DecodeError{Path: "/uid", Inner: err}
		}
		e.UID = dv
	}
	e.Links = aux.Links
	e.ArchetypeDetails = aux.ArchetypeDetails
	e.FeederAudit = aux.FeederAudit
	if len(aux.Settings) > 0 && string(aux.Settings) != "null" {
		dv, err := typereg.DecodeAs[AccessControlSettings](aux.Settings)
		if err != nil {
			return &typereg.DecodeError{Path: "/settings", Inner: err}
		}
		e.Settings = dv
	}
	return nil
}

type EHRStatusJSONUnmarshaller struct {
	Class string          `json:"_type"`
	Name  json.RawMessage `json:"name"` // polymorphic DataValueText
	// ArchetypeNodeID Design-time archetype identifier of this node taken from its generating archetype; used to build archetype paths. Always in the form of an at-code, e.g.  `at0005`. This value enables a 'standardised' name for this node to be generated, by referring to the generating archetype local terminology.
	//
	// At an archetype root point, the value of this attribute is always the stringified form of the `_archetype_id_` found in the `_archetype_details_` object.
	ArchetypeNodeID string          `json:"archetype_node_id"`
	UID             json.RawMessage `json:"uid,omitempty"` // polymorphic UIDBasedID
	// Links Links to other archetyped structures (data whose root object inherits from `ARCHETYPED`, such as `ENTRY`, `SECTION` and so on). Links may be to structures in other compositions.
	Links []Link `json:"links,omitempty"`
	// ArchetypeDetails Details of archetyping used on this node.
	ArchetypeDetails *Archetyped `json:"archetype_details,omitempty"`
	// FeederAudit Audit trail from non-openEHR system of original commit of information forming the content of this node, or from a conversion gateway which has synthesised this node.
	FeederAudit *FeederAudit `json:"feeder_audit,omitempty"`
	// Subject The subject of this EHR. The `_external_ref_` attribute can be used to contain a direct reference to the subject in a demographic or identity service. Alternatively, the association between patients and their records may be done elsewhere for security reasons.
	Subject PartySelf `json:"subject"`
	// IsQueryable True if this EHR should be included in population queries, i.e. if this EHR is considered active in the population.
	IsQueryable bool `json:"is_queryable"`
	// IsModifiable True if the EHR, other than the `EHR_STATUS` object, is allowed to be written to. The `EHR_STATUS` object itself can always be written to.
	IsModifiable bool            `json:"is_modifiable"`
	OtherDetails json.RawMessage `json:"other_details,omitempty"` // polymorphic ItemStructure
}

// UnmarshalJSON decodes canonical openEHR JSON into EHRStatus.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (e *EHRStatus) UnmarshalJSON(data []byte) error {
	var aux EHRStatusJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: EHR_STATUS: %w", err)
	}
	if aux.Class != "" && aux.Class != "EHR_STATUS" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "EHR_STATUS", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	if len(aux.Name) > 0 && string(aux.Name) != "null" {
		dv, err := DecodeDataValueText(aux.Name)
		if err != nil {
			return &typereg.DecodeError{Path: "/name", Inner: err}
		}
		e.Name = dv
	}
	e.ArchetypeNodeID = aux.ArchetypeNodeID
	if len(aux.UID) > 0 && string(aux.UID) != "null" {
		dv, err := typereg.DecodeAs[UIDBasedID](aux.UID)
		if err != nil {
			return &typereg.DecodeError{Path: "/uid", Inner: err}
		}
		e.UID = dv
	}
	e.Links = aux.Links
	e.ArchetypeDetails = aux.ArchetypeDetails
	e.FeederAudit = aux.FeederAudit
	e.Subject = aux.Subject
	e.IsQueryable = aux.IsQueryable
	e.IsModifiable = aux.IsModifiable
	if len(aux.OtherDetails) > 0 && string(aux.OtherDetails) != "null" {
		dv, err := typereg.DecodeAs[ItemStructure](aux.OtherDetails)
		if err != nil {
			return &typereg.DecodeError{Path: "/other_details", Inner: err}
		}
		e.OtherDetails = dv
	}
	return nil
}

type VersionedCompositionJSONUnmarshaller struct {
	Class string `json:"_type"`
	// UID Unique identifier of this version container in the form of a UID with no extension. This id will be the same in all instances of the same container in a distributed environment, meaning that it can be understood as the uid of the  virtual version tree.
	UID HierObjectID `json:"uid"`
	// OwnerID Reference to object to which this version container belongs, e.g. the id of the containing EHR or other relevant owning entity.
	OwnerID ObjectRef `json:"owner_id"`
	// TimeCreated Time of initial creation of this versioned object.
	TimeCreated DVDateTime `json:"time_created"`
}

// UnmarshalJSON decodes canonical openEHR JSON into VersionedComposition.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (v *VersionedComposition) UnmarshalJSON(data []byte) error {
	var aux VersionedCompositionJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: VERSIONED_COMPOSITION: %w", err)
	}
	if aux.Class != "" && aux.Class != "VERSIONED_COMPOSITION" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "VERSIONED_COMPOSITION", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	v.UID = aux.UID
	v.OwnerID = aux.OwnerID
	v.TimeCreated = aux.TimeCreated
	return nil
}

type VersionedEHRAccessJSONUnmarshaller struct {
	Class string `json:"_type"`
	// UID Unique identifier of this version container in the form of a UID with no extension. This id will be the same in all instances of the same container in a distributed environment, meaning that it can be understood as the uid of the  virtual version tree.
	UID HierObjectID `json:"uid"`
	// OwnerID Reference to object to which this version container belongs, e.g. the id of the containing EHR or other relevant owning entity.
	OwnerID ObjectRef `json:"owner_id"`
	// TimeCreated Time of initial creation of this versioned object.
	TimeCreated DVDateTime `json:"time_created"`
}

// UnmarshalJSON decodes canonical openEHR JSON into VersionedEHRAccess.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (v *VersionedEHRAccess) UnmarshalJSON(data []byte) error {
	var aux VersionedEHRAccessJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: VERSIONED_EHR_ACCESS: %w", err)
	}
	if aux.Class != "" && aux.Class != "VERSIONED_EHR_ACCESS" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "VERSIONED_EHR_ACCESS", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	v.UID = aux.UID
	v.OwnerID = aux.OwnerID
	v.TimeCreated = aux.TimeCreated
	return nil
}

type VersionedEHRStatusJSONUnmarshaller struct {
	Class string `json:"_type"`
	// UID Unique identifier of this version container in the form of a UID with no extension. This id will be the same in all instances of the same container in a distributed environment, meaning that it can be understood as the uid of the  virtual version tree.
	UID HierObjectID `json:"uid"`
	// OwnerID Reference to object to which this version container belongs, e.g. the id of the containing EHR or other relevant owning entity.
	OwnerID ObjectRef `json:"owner_id"`
	// TimeCreated Time of initial creation of this versioned object.
	TimeCreated DVDateTime `json:"time_created"`
}

// UnmarshalJSON decodes canonical openEHR JSON into VersionedEHRStatus.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (v *VersionedEHRStatus) UnmarshalJSON(data []byte) error {
	var aux VersionedEHRStatusJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: VERSIONED_EHR_STATUS: %w", err)
	}
	if aux.Class != "" && aux.Class != "VERSIONED_EHR_STATUS" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "VERSIONED_EHR_STATUS", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	v.UID = aux.UID
	v.OwnerID = aux.OwnerID
	v.TimeCreated = aux.TimeCreated
	return nil
}
