// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

// BMM package: org.openehr.rm.ehr

// AccessControlSettings Access Control Settings for the EHR and components. Intended to support multiple access control schemes. Currently implementation dependent.
type AccessControlSettings interface {
	isAccessControlSettings()
}

// EHR The EHR object is the root object and access point of an EHR for a subject of care.
type EHR struct {
	// Compositions Master list of all Versioned Composition references in this EHR.
	Compositions []ObjectRefLike `json:"compositions,omitempty"`
	// Contributions List of contributions causing changes to this EHR. Each contribution contains a list of versions, which may include references to any number of `VERSION` instances, i.e. items of type `VERSIONED_COMPOSITION` and `VERSIONED_FOLDER`.
	Contributions []ObjectRefLike `json:"contributions,omitempty"`
	// Directory Optional directory structure for this EHR. If present, this is a reference to the first member of `_folders_`.
	Directory ObjectRefLike `json:"directory,omitempty"`
	// EHRAccess Reference to `EHR_ACCESS` object for this EHR.
	EHRAccess ObjectRefLike `json:"ehr_access"`
	// EHRID The unique identifier of this EHR.
	//
	// NOTE: is is strongly recommended that a UUID always be used for this field.
	EHRID HierObjectID `json:"ehr_id"`
	// EHRStatus Reference to `EHR_STATUS` object for this EHR.
	EHRStatus ObjectRefLike `json:"ehr_status"`
	// Folders Optional additional Folder structures for this EHR. If set, the `_directory_` attribute refers to the first member.
	Folders []ObjectRefLike `json:"folders,omitempty"`
	// SystemID The identifier of the logical EHR management system in which this EHR was created.
	SystemID HierObjectID `json:"system_id"`
	// Tags Optional list of tags associated with this EHR. Tag `_target_` values can only be within the same EHR.
	Tags []ObjectRefLike `json:"tags,omitempty"`
	// TimeCreated Time of creation of the EHR.
	TimeCreated DVDateTime `json:"time_created"`
}

// EHRAccess EHR-wide access control object. All access decisions to data in the EHR must be made in accordance with the policies and rules in this object.
//
// NOTE: It is strongly recommended that the inherited attribute `_uid_` be populated in `EHR_ACCESS` objects, using the UID copied from the `_object_id()_` of the `_uid_` field of the enclosing `VERSION` object. +
// For example, the `ORIGINAL_VERSION.uid` `87284370-2D4B-4e3d-A3F3-F303D2F4F34B::uk.nhs.ehr1::2` would be copied to the `_uid_` field of the `EHR_ACCESS` object.
type EHRAccess struct {
	// ArchetypeDetails Details of archetyping used on this node.
	ArchetypeDetails *Archetyped `json:"archetype_details,omitempty"`
	// ArchetypeNodeID Design-time archetype identifier of this node taken from its generating archetype; used to build archetype paths. Always in the form of an at-code, e.g.  `at0005`. This value enables a 'standardised' name for this node to be generated, by referring to the generating archetype local terminology.
	//
	// At an archetype root point, the value of this attribute is always the stringified form of the `_archetype_id_` found in the `_archetype_details_` object.
	ArchetypeNodeID string `json:"archetype_node_id"`
	// FeederAudit Audit trail from non-openEHR system of original commit of information forming the content of this node, or from a conversion gateway which has synthesised this node.
	FeederAudit *FeederAudit `json:"feeder_audit,omitempty"`
	// Links Links to other archetyped structures (data whose root object inherits from `ARCHETYPED`, such as `ENTRY`, `SECTION` and so on). Links may be to structures in other compositions.
	Links []Link `json:"links,omitempty"`
	// Name Runtime name of this fragment, used to build runtime paths. This is the term provided via a clinical application or batch process to name this EHR construct: its retention in the EHR faithfully preserves the original label by which this entry was known to end users.
	Name DVTextLike `json:"name"`
	// Settings Access control settings for the EHR. Instance is a subtype of the type `ACCESS_CONTROL_SETTINGS`, allowing for the use of different access control schemes.
	Settings AccessControlSettings `json:"settings,omitempty"`
	// UID Optional globally unique object identifier for root points of archetyped structures.
	UID UIDBasedID `json:"uid,omitempty"`
}

// Scheme The name of the access control scheme in use; corresponds to the concrete instance of the settings attribute.
func (e *EHRAccess) Scheme() string {
	panic("not implemented: EHR_ACCESS.scheme — implement in a non-generated file")
}

// EHRStatus Single object per EHR containing various EHR-wide status flags and settings, including whether this EHR can be queried, modified etc. This object is always modifiable, in order to change the status of the EHR as a whole.
//
// NOTE: It is strongly recommended that the inherited attribute `_uid_` be populated in `EHR_STATUS` objects, using the UID copied from the `_object_id()_` of the `_uid_` field of the enclosing `VERSION` object. +
// For example, the `ORIGINAL_VERSION.uid` `87284370-2D4B-4e3d-A3F3-F303D2F4F34B::uk.nhs.ehr1::2`  would be copied to the `_uid_` field of the `EHR_STATUS` object.
type EHRStatus struct {
	// ArchetypeDetails Details of archetyping used on this node.
	ArchetypeDetails *Archetyped `json:"archetype_details,omitempty"`
	// ArchetypeNodeID Design-time archetype identifier of this node taken from its generating archetype; used to build archetype paths. Always in the form of an at-code, e.g.  `at0005`. This value enables a 'standardised' name for this node to be generated, by referring to the generating archetype local terminology.
	//
	// At an archetype root point, the value of this attribute is always the stringified form of the `_archetype_id_` found in the `_archetype_details_` object.
	ArchetypeNodeID string `json:"archetype_node_id"`
	// FeederAudit Audit trail from non-openEHR system of original commit of information forming the content of this node, or from a conversion gateway which has synthesised this node.
	FeederAudit *FeederAudit `json:"feeder_audit,omitempty"`
	// IsModifiable True if the EHR, other than the `EHR_STATUS` object, is allowed to be written to. The `EHR_STATUS` object itself can always be written to.
	IsModifiable bool `json:"is_modifiable"`
	// IsQueryable True if this EHR should be included in population queries, i.e. if this EHR is considered active in the population.
	IsQueryable bool `json:"is_queryable"`
	// Links Links to other archetyped structures (data whose root object inherits from `ARCHETYPED`, such as `ENTRY`, `SECTION` and so on). Links may be to structures in other compositions.
	Links []Link `json:"links,omitempty"`
	// Name Runtime name of this fragment, used to build runtime paths. This is the term provided via a clinical application or batch process to name this EHR construct: its retention in the EHR faithfully preserves the original label by which this entry was known to end users.
	Name DVTextLike `json:"name"`
	// OtherDetails Any other details of the EHR summary object, in the form of an archetyped `ITEM_STRUCTURE`.
	OtherDetails ItemStructure `json:"other_details,omitempty"`
	// Subject The subject of this EHR. The `_external_ref_` attribute can be used to contain a direct reference to the subject in a demographic or identity service. Alternatively, the association between patients and their records may be done elsewhere for security reasons.
	Subject PartySelf `json:"subject"`
	// UID Optional globally unique object identifier for root points of archetyped structures.
	UID UIDBasedID `json:"uid,omitempty"`
}

// VersionedComposition Version-controlled composition abstraction, defined by inheriting `VERSIONED_OBJECT<COMPOSITION>`.
type VersionedComposition struct {
	VersionedObject[any]
}

// IsPersistent Indicates whether this composition set is persistent; derived from first version.
func (v *VersionedComposition) IsPersistent() bool {
	panic("not implemented: VERSIONED_COMPOSITION.is_persistent — implement in a non-generated file")
}

// VersionedEHRAccess Version container for `EHR_ACCESS` instance.
type VersionedEHRAccess struct {
	VersionedObject[any]
}

// VersionedEHRStatus Version container for `EHR_STATUS` instance.
type VersionedEHRStatus struct {
	VersionedObject[any]
}
