// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/json/jsontext"
	json "encoding/json/v2"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
)

// BMM package: org.openehr.base.foundation_types.interval — canonical-JSON MarshalJSONTo companions

// rawPointInterval is the method-free canonical-JSON alias for PointInterval. The alias
// drops the codec methods so marshalling the anonymous wrapper below
// does not recurse; the class embeds no marshaler-bearing concrete
// ancestor, so nothing is promoted (ADR 0022).
type rawPointInterval[T any] PointInterval[T]

// MarshalJSONTo emits canonical openEHR JSON for PointInterval with `_type`
// (value "Point_interval") as the leading member. Field order otherwise follows the
// struct declaration; json.Deterministic sorts any Hash keys and the
// FormatNil* options keep a mandatory nil container's `null` spelling
// (REQ-052, Q6). The receiver is a value so a concrete instance sitting
// in a polymorphic interface slot by value — the shape the like-interface
// accessors admit — still carries its `_type` (REQ-052 substitution).
func (p PointInterval[T]) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, &struct {
		Type string `json:"_type"`
		*rawPointInterval[T]
	}{"Point_interval", (*rawPointInterval[T])(&p)}, typereg.MarshalOptions(enc))
}

// rawProperInterval is the method-free canonical-JSON alias for ProperInterval. The alias
// drops the codec methods so marshalling the anonymous wrapper below
// does not recurse; the class embeds no marshaler-bearing concrete
// ancestor, so nothing is promoted (ADR 0022).
type rawProperInterval[T any] ProperInterval[T]

// MarshalJSONTo emits canonical openEHR JSON for ProperInterval with `_type`
// (value "Proper_interval") as the leading member. Field order otherwise follows the
// struct declaration; json.Deterministic sorts any Hash keys and the
// FormatNil* options keep a mandatory nil container's `null` spelling
// (REQ-052, Q6). The receiver is a value so a concrete instance sitting
// in a polymorphic interface slot by value — the shape the like-interface
// accessors admit — still carries its `_type` (REQ-052 substitution).
func (p ProperInterval[T]) MarshalJSONTo(enc *jsontext.Encoder) error {
	return json.MarshalEncode(enc, &struct {
		Type string `json:"_type"`
		*rawProperInterval[T]
	}{"Proper_interval", (*rawProperInterval[T])(&p)}, typereg.MarshalOptions(enc))
}
