// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/json"
	"fmt"

	"github.com/cadasto/openehr-sdk-go/openehr/rm/typereg"
)

// BMM package: org.openehr.base.foundation_types.time — canonical-JSON UnmarshalJSON companions

type ISO8601TimezoneJSONUnmarshaller struct {
	Class string `json:"_type"`
}

// UnmarshalJSON decodes canonical openEHR JSON into ISO8601Timezone.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (i *ISO8601Timezone) UnmarshalJSON(data []byte) error {
	var aux ISO8601TimezoneJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: Iso8601_timezone: %w", err)
	}
	if aux.Class != "" && aux.Class != "Iso8601_timezone" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "Iso8601_timezone", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	return nil
}

type TimeDefinitionsJSONUnmarshaller struct {
	Class string `json:"_type"`
}

// UnmarshalJSON decodes canonical openEHR JSON into TimeDefinitions.
// Polymorphic fields are routed through typereg.DecodeAs so the
// concrete type is selected by `_type` at each polymorphic site.
// Missing/unknown/type-mismatch dispatch failures wrap typereg
// sentinels inside *typereg.DecodeError for errors.Is / errors.As.
func (t *TimeDefinitions) UnmarshalJSON(data []byte) error {
	var aux TimeDefinitionsJSONUnmarshaller
	if err := json.Unmarshal(data, &aux); err != nil {
		return fmt.Errorf("canjson: Time_Definitions: %w", err)
	}
	if aux.Class != "" && aux.Class != "Time_Definitions" {
		return &typereg.DecodeError{
			Path:  "/_type",
			Inner: fmt.Errorf("canjson: expected %q (or a descendant), got %q: %w", "Time_Definitions", aux.Class, typereg.ErrTypeMismatch),
		}
	}
	return nil
}
