// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import "encoding/json"

// BMM package: org.openehr.base.foundation_types.time — canonical-JSON MarshalJSON companions

type ISO8601TimezoneJSONMarshaller struct {
	Class string `json:"_type"`
}

// MarshalJSON emits canonical openEHR JSON for ISO8601Timezone with `_type`
// (value "Iso8601_timezone") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (i *ISO8601Timezone) MarshalJSON() ([]byte, error) {
	return json.Marshal(&ISO8601TimezoneJSONMarshaller{
		Class: "Iso8601_timezone",
	})
}

type TimeDefinitionsJSONMarshaller struct {
	Class string `json:"_type"`
}

// MarshalJSON emits canonical openEHR JSON for TimeDefinitions with `_type`
// (value "Time_Definitions") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (t *TimeDefinitions) MarshalJSON() ([]byte, error) {
	return json.Marshal(&TimeDefinitionsJSONMarshaller{
		Class: "Time_Definitions",
	})
}
