// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/xml"

	"github.com/cadasto/openehr-sdk-go/openehr/serialize/canxml"
)

// BMM package: org.openehr.base.foundation_types.interval — canonical-XML MarshalXML companions

// BMMName returns "Point_interval" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (p *PointInterval[T]) BMMName() string { return "Point_interval" }

// MarshalXML emits canonical openEHR XML for PointInterval. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are appended to start.Attr before
// the start token is written.
func (p *PointInterval[T]) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("Point_interval")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeElement(&p.Lower, xml.StartElement{Name: xml.Name{Local: "lower"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(&p.Upper, xml.StartElement{Name: xml.Name{Local: "upper"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(p.LowerUnbounded, xml.StartElement{Name: xml.Name{Local: "lower_unbounded"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(p.UpperUnbounded, xml.StartElement{Name: xml.Name{Local: "upper_unbounded"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(p.LowerIncluded, xml.StartElement{Name: xml.Name{Local: "lower_included"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(p.UpperIncluded, xml.StartElement{Name: xml.Name{Local: "upper_included"}}); err != nil {
		return err
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}

// BMMName returns "Proper_interval" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (p *ProperInterval[T]) BMMName() string { return "Proper_interval" }

// MarshalXML emits canonical openEHR XML for ProperInterval. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
// Properties typed as XML attributes per the openEHR ITS-XML XSDs
// (currently `archetype_node_id`) are appended to start.Attr before
// the start token is written.
func (p *ProperInterval[T]) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("Proper_interval")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeElement(&p.Lower, xml.StartElement{Name: xml.Name{Local: "lower"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(&p.Upper, xml.StartElement{Name: xml.Name{Local: "upper"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(p.LowerUnbounded, xml.StartElement{Name: xml.Name{Local: "lower_unbounded"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(p.UpperUnbounded, xml.StartElement{Name: xml.Name{Local: "upper_unbounded"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(p.LowerIncluded, xml.StartElement{Name: xml.Name{Local: "lower_included"}}); err != nil {
		return err
	}
	if err := _e.EncodeElement(p.UpperIncluded, xml.StartElement{Name: xml.Name{Local: "upper_included"}}); err != nil {
		return err
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}
