// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import "encoding/json"

// BMM package: org.openehr.rm.integration — canonical-JSON MarshalJSON companions

type GenericEntryJSONMarshaller struct {
	Class string `json:"_type"`
	// Name Runtime name of this fragment, used to build runtime paths. This is the term provided via a clinical application or batch process to name this EHR construct: its retention in the EHR faithfully preserves the original label by which this entry was known to end users.
	Name DataValueText `json:"name"`
	// ArchetypeNodeID Design-time archetype identifier of this node taken from its generating archetype; used to build archetype paths. Always in the form of an at-code, e.g.  `at0005`. This value enables a 'standardised' name for this node to be generated, by referring to the generating archetype local terminology.
	//
	// At an archetype root point, the value of this attribute is always the stringified form of the `_archetype_id_` found in the `_archetype_details_` object.
	ArchetypeNodeID string `json:"archetype_node_id"`
	// UID Optional globally unique object identifier for root points of archetyped structures.
	UID UIDBasedID `json:"uid,omitempty"`
	// Links Links to other archetyped structures (data whose root object inherits from `ARCHETYPED`, such as `ENTRY`, `SECTION` and so on). Links may be to structures in other compositions.
	Links []Link `json:"links,omitempty"`
	// ArchetypeDetails Details of archetyping used on this node.
	ArchetypeDetails *Archetyped `json:"archetype_details,omitempty"`
	// FeederAudit Audit trail from non-openEHR system of original commit of information forming the content of this node, or from a conversion gateway which has synthesised this node.
	FeederAudit *FeederAudit `json:"feeder_audit,omitempty"`
	// Data The data from the source message or record. May be recorded in any structural openEHR representation.
	Data Item `json:"data"`
}

// MarshalJSON emits canonical openEHR JSON for GenericEntry with `_type`
// (value "GENERIC_ENTRY") as the leading object key. Field order matches the
// concrete struct's declaration order — embedded-ancestor fields
// first (in their original order), then own + flattened-abstract
// ancestor fields in BMM property declaration order.
func (g *GenericEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(&GenericEntryJSONMarshaller{
		Class:            "GENERIC_ENTRY",
		Name:             g.Name,
		ArchetypeNodeID:  g.ArchetypeNodeID,
		UID:              g.UID,
		Links:            g.Links,
		ArchetypeDetails: g.ArchetypeDetails,
		FeederAudit:      g.FeederAudit,
		Data:             g.Data,
	})
}
