// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

// BMM package: org.openehr.base.resource

// ResourceAnnotations Object representing annotations on an archetype. These can be of various forms, with a documentation form defined so far, which has a multi-level tabular structure [ [ [String value, String key], path key], language key]. Example instance, showing the documentation structure.
//
// --------
// documentation = <
// ["en"] = <
// ["/data[id2]"] = <
// ["ui"] = <"passthrough">
// >
// ["/data[id2]/items[id3]"] = <
// ["design note"] = <"this is a design note on Statement">
// ["requirements note"] = <"this is a requirements note on Statement">
// ["medline ref"] = <"this is a medline ref on Statement">
// >
// >
// >
// --------
//
// Other sub-structures might have different keys, e.g.  based on programming languages, UI toolkits etc.
type ResourceAnnotations struct {
	// Documentation Documentary annotations in a multi-level keyed structure.
	Documentation map[string]any `json:"documentation"`
}
