// Code generated by bmmgen; DO NOT EDIT.
// Source: openehr_rm_1.2.0.bmm.json + openehr_base_1.3.0.bmm.json

package rm

import (
	"encoding/xml"

	"github.com/cadasto/openehr-sdk-go/openehr/serialize/canxml"
)

// BMM package: org.openehr.rm.support.measurement — canonical-XML MarshalXML companions

// BMMName returns "MEASUREMENT_SERVICE" — the BMM class identifier used as the
// `xsi:type` polymorphic discriminator in canonical XML and the
// `_type` discriminator in canonical JSON.
func (m *MeasurementService) BMMName() string { return "MEASUREMENT_SERVICE" }

// MarshalXML emits canonical openEHR XML for MeasurementService. The default
// element local name is the snake-cased BMM class name when the
// parent did not set one. Child elements follow BMM property
// declaration order; nil-pointer optionals and empty containers are
// omitted. Polymorphic descendants are emitted via canxml.EncodePoly.
func (m *MeasurementService) MarshalXML(_e *xml.Encoder, _start xml.StartElement) error {
	if _start.Name.Local == "" {
		_start.Name = xml.Name{Local: canxml.ElementName("MEASUREMENT_SERVICE")}
	}
	if err := _e.EncodeToken(_start); err != nil {
		return err
	}
	if err := _e.EncodeToken(_start.End()); err != nil {
		return err
	}
	return nil
}
